/**
 * Client-side media conversion utilities.
 *
 * toWebP  — converts any image File to WebP (max 1920px, 85% quality).
 * toOpus  — converts WAV files to WebM/Opus (or OGG/Opus in Firefox) using
 *            the Web Audio API + MediaRecorder. Non-WAV files pass through
 *            unchanged. Falls back to the original file on any error or if
 *            the browser doesn't support Opus encoding (Safari).
 *
 * Both functions are pure: they never throw; they return the original file
 * on failure so callers don't need to handle errors.
 */

import { sniffImageFormat } from "@edge-shared/provenance/sniff.ts";
import { readXmpFromWebp, readXmpFromPng, readXmpFromJpeg, embedXmpInWebp, embedXmpInJpeg } from "@edge-shared/provenance/embed.ts";

// ── Image ────────────────────────────────────────────────────────────────

/**
 * Reads an XMP packet out of `bytes`, if any — format is sniffed from magic
 * bytes, never a caller-supplied label (AI-generated bytes decoded from
 * base64 are routinely mislabeled; see `sniffImageFormat`'s own doc).
 */
export function readEmbeddedXmp(bytes: Uint8Array): string | null {
  switch (sniffImageFormat(bytes)) {
    case "image/webp": return readXmpFromWebp(bytes);
    case "image/png":  return readXmpFromPng(bytes);
    case "image/jpeg": return readXmpFromJpeg(bytes);
    default:           return null;
  }
}

// Return type is intentionally inferred (not annotated `Uint8Array`), same
// reasoning as localKeyVault.ts's `fromBase64`: a bare `Uint8Array`
// annotation widens to `Uint8Array<ArrayBufferLike>` (embed.ts's own
// embedXmpIn*/mark.ts's markGeneratedImage return type), which newer
// lib.dom typings reject as a `BlobPart`. Re-wrapping via the
// `ArrayLike<number>` constructor overload always yields an
// `ArrayBuffer`-backed array regardless of the source's type parameter.
/** Re-embeds `xmpPacket` into freshly canvas-encoded bytes. Never throws — a malformed encode (shouldn't happen; canvas produced these bytes) falls back to the unmarked bytes rather than failing the conversion. */
export function reembedXmp(bytes: Uint8Array, xmpPacket: string, format: "image/webp" | "image/jpeg") {
  try {
    const marked = format === "image/webp" ? embedXmpInWebp(bytes, xmpPacket) : embedXmpInJpeg(bytes, xmpPacket);
    return new Uint8Array(marked);
  } catch {
    return new Uint8Array(bytes);
  }
}

/**
 * Converts any image File to WebP (max 1920px, 85% quality; falls back to
 * JPEG when the browser can't encode WebP).
 *
 * `toWebP` is the one canvas re-encode every image upload — AI-generated or
 * a plain user photo — is forced through (`useImageUpload`, the entity-image
 * generation paths, group-portrait upload). Canvas never preserves embedded
 * metadata, so if the INPUT already carries an XMP packet (EU AI Act Art
 * 50(2) disclosure on server- or local-marked AI art; a camera photo's own
 * XMP is equally worth keeping), the same packet is re-embedded into the
 * re-encoded output — otherwise the mark silently disappears at this single
 * chokepoint regardless of who marked it or why.
 */
export async function toWebP(file: File, maxPx = 1920, quality = 0.85): Promise<File> {
  const existingXmp = readEmbeddedXmp(new Uint8Array(await file.arrayBuffer()));

  return new Promise((resolve) => {
    const img = new Image();
    const objectUrl = URL.createObjectURL(file);
    img.onload = () => {
      URL.revokeObjectURL(objectUrl);
      const scale = Math.min(1, maxPx / Math.max(img.width, img.height));
      const w = Math.round(img.width * scale);
      const h = Math.round(img.height * scale);
      const canvas = document.createElement("canvas");
      canvas.width = w;
      canvas.height = h;
      canvas.getContext("2d")!.drawImage(img, 0, 0, w, h);
      canvas.toBlob(
        (blob) => {
          if (blob && blob.type === "image/webp") {
            void finalizeWebpOrJpeg(blob, existingXmp, "image/webp", file.name, ".webp").then(resolve);
          } else {
            // WebP encoding not supported (Safari < 16.1 returns PNG) — fall back to JPEG
            canvas.toBlob(
              (jpegBlob) => {
                if (jpegBlob) void finalizeWebpOrJpeg(jpegBlob, existingXmp, "image/jpeg", file.name, ".jpeg").then(resolve);
                else resolve(file);
              },
              "image/jpeg",
              quality,
            );
          }
        },
        "image/webp",
        quality,
      );
    };
    img.onerror = () => { URL.revokeObjectURL(objectUrl); resolve(file); };
    img.src = objectUrl;
  });
}

async function finalizeWebpOrJpeg(
  blob: Blob,
  existingXmp: string | null,
  format: "image/webp" | "image/jpeg",
  originalName: string,
  ext: string,
): Promise<File> {
  const marked = existingXmp
    ? new Blob([reembedXmp(new Uint8Array(await blob.arrayBuffer()), existingXmp, format)], { type: format })
    : blob;
  return new File([marked], originalName.replace(/\.[^.]+$/, ext), { type: format });
}

/**
 * Resize an image blob to a target width (height proportional). Never upscales.
 * Input must already be an image blob (WebP or JPEG) — no format fallback needed.
 * Returns the original blob on any canvas failure — never throws.
 */
export async function resizeToWebP(blob: Blob, width: number, quality = 0.8): Promise<Blob> {
  return new Promise((resolve) => {
    const img = new Image();
    const objectUrl = URL.createObjectURL(blob);
    img.onload = () => {
      URL.revokeObjectURL(objectUrl);
      const scale = Math.min(1, width / img.width);
      const w = Math.round(img.width * scale);
      const h = Math.round(img.height * scale);
      const canvas = document.createElement("canvas");
      canvas.width = w;
      canvas.height = h;
      canvas.getContext("2d")!.drawImage(img, 0, 0, w, h);
      canvas.toBlob((result) => resolve(result ?? blob), "image/webp", quality);
    };
    img.onerror = () => { URL.revokeObjectURL(objectUrl); resolve(blob); };
    img.src = objectUrl;
  });
}

// ── Audio ─────────────────────────────────────────────────────────────────

/**
 * Compress a WAV file to WebM/Opus (Chrome/Edge) or OGG/Opus (Firefox) using
 * the Web Audio API + MediaRecorder. Compression ratio is typically 10–20×.
 *
 * Note: encoding runs in real time (a 3-minute WAV takes ~3 minutes to
 * encode). Show a "Converting…" indicator while awaiting this function.
 *
 * Non-WAV files (MP3, OGG, M4A, AAC, FLAC, WebM) are already compressed and
 * are returned unchanged.
 */
export async function toOpus(file: File): Promise<File> {
  const isWav =
    file.type === "audio/wav" ||
    file.type === "audio/x-wav" ||
    file.name.toLowerCase().endsWith(".wav");
  if (!isWav) return file;

  // Prefer OGG/Opus — it plays in Chrome, Firefox, and Safari 14+.
  // Fall back to WebM/Opus (Chrome-only recording but wide playback).
  const mimeType =
    MediaRecorder.isTypeSupported("audio/ogg;codecs=opus")
      ? "audio/ogg;codecs=opus"
      : MediaRecorder.isTypeSupported("audio/webm;codecs=opus")
      ? "audio/webm;codecs=opus"
      : null;

  // No Opus encoder available (Safari) — upload original WAV.
  if (!mimeType) return file;

  try {
    const arrayBuffer = await file.arrayBuffer();

    // Decode WAV → AudioBuffer
    const decodeCtx = new AudioContext();
    const audioBuffer = await decodeCtx.decodeAudioData(arrayBuffer);
    await decodeCtx.close();

    // Pipe decoded audio through a MediaStreamDestination so MediaRecorder
    // can capture and encode it. This runs at real-time playback speed.
    const playCtx = new AudioContext();
    await playCtx.resume(); // browsers may auto-suspend AudioContexts
    const dest = playCtx.createMediaStreamDestination();
    const source = playCtx.createBufferSource();
    source.buffer = audioBuffer;
    source.connect(dest);

    return await new Promise<File>((resolve) => {
      const recorder = new MediaRecorder(dest.stream, { mimeType });
      const chunks: Blob[] = [];

      recorder.ondataavailable = (e) => {
        if (e.data.size > 0) chunks.push(e.data);
      };

      recorder.onstop = async () => {
        await playCtx.close();
        const blob = new Blob(chunks, { type: mimeType });
        const ext = mimeType.includes("ogg") ? "ogg" : "webm";
        resolve(new File([blob], file.name.replace(/\.[^.]+$/, `.${ext}`), { type: mimeType }));
      };

      recorder.start(250); // flush chunks every 250 ms
      source.start(0);
      source.onended = () => recorder.stop();
    });
  } catch {
    return file; // any error → upload original
  }
}
