/**
 * Curated 25mm base registry (SIMULACRUM_PLAN.md §2 BASELESS decision, #542).
 * Pure data — no Deno imports — so it's usable from edge functions
 * (poll-meshy-jobs, forge-mini) and from scripts/ingest-mini-bases.ts (tsx).
 *
 * Bases are first-party STL geometry generated by the sister repo "plinth"
 * (origin at base-bottom center, mm scale, 25mm footprint) — Jeffrey drops
 * outputs into art-src/bases/ and they get uploaded to
 * mini-models/bases/<id>.stl|.glb via `npm run ingest-mini-bases`. Two plinth
 * export layouts exist: early bases drop flat as art-src/bases/<id>.stl|.glb;
 * newer plinth exports nest each base under its own directory (e.g.
 * `art-src/bases/2026-07 lava flow 4/round25-1-2/round25-1-2.stl`) — for
 * those, set `src` below to the path stem (relative to art-src/bases/,
 * without extension). Until real plinth output lands, "plain" is generated
 * PROCEDURALLY (a plain cylinder, _shared/stl.ts generateCylinderStl) — see
 * ingest-mini-bases.ts.
 *
 * Adding a base = a registry entry below + `npm run ingest-mini-bases` —
 * NEVER a migration (minis.base_id is free text; see migration
 * 20260718000005_minis_base_and_scale.sql).
 */

export interface MiniBase {
  id: string;
  label: string;
  // Fallback flat baseColor for a DERIVED GLB (glb-compose.ts stlToGlb) — only
  // used when ingest-mini-bases.ts finds no art-src/bases/<id|src>.glb.
  // plinth can also export a Blender-baked, artist-colored GLB (vertex
  // colors/materials an STL can't carry); when that file exists it's
  // uploaded as-is and this color is ignored for that base.
  color: string;
  // Path stem RELATIVE to art-src/bases/, WITHOUT extension — only needed
  // for plinth's nested per-export directories (see the file comment above).
  // Falls back to the flat art-src/bases/<id>.stl|.glb convention when
  // omitted. Ingest-only: the frontend mirror (src/data/miniBases.ts) never
  // needs this field.
  src?: string;
}

export const MINI_BASES: MiniBase[] = [
  { id: "plain", label: "Plain", color: "#8a8a8a" },
  {
    id: "lava-flow",
    label: "Lava Flow",
    color: "#7a2e1e",
    src: "2026-07 lava flow 4/round25-1-2/round25-1-2",
  },
  // Coming from plinth (Phase 4.5 curated set, #542) — uncomment once the
  // matching art-src/bases/<id>.stl exists and ingest-mini-bases.ts has been
  // re-run:
  // { id: "cobblestone", label: "Cobblestone", color: "#7a7468" },
  // { id: "grass",       label: "Grass",       color: "#4c7a3d" },
  // { id: "lava",        label: "Lava",        color: "#7a2a12" },
];

export const DEFAULT_BASE_ID = "plain";

// Base files live at mini-models/bases/<id>.stl and mini-models/bases/<id>.glb
// — one shared prefix in the mini-models bucket, reused by every composed mini.
export const BASE_STORAGE_PREFIX = "bases";

export function getMiniBase(id: string): MiniBase | null {
  return MINI_BASES.find((base) => base.id === id) ?? null;
}
