/**
 * Storage upload/download helpers, shared by every edge function that
 * uploads generated bytes (chronicle images, mini style renders, mini model
 * files) or reads them back (mini composition — poll-meshy-jobs, forge-mini
 * `set_base`). Storage occasionally returns a transient 502/Bad Gateway on
 * upload — retry a few times with backoff before giving up. upsert:true so a
 * partially-written object from a failed attempt doesn't cause a 409.
 *
 * This is also the seam where server-generated bytes land in R2 rather than
 * Supabase Storage (#577 stage 2). Every server-side write already funnels
 * through `uploadWithRetry`, so routing here covers generate-chronicle-image,
 * generate-music, forge-mini and poll-meshy-jobs without touching any of them.
 *
 * There is deliberately no presigning on this path: an edge function running
 * with the service role has the R2 credentials already, and a presigned URL
 * would only add a round trip and a bearer credential with a lifetime.
 */
import type { SupabaseClient } from "@supabase/supabase-js";
import { r2ConfigFrom, r2ObjectKey, isR2Bucket } from "./r2/config.ts";
import { putObject } from "./r2/client.ts";
import { publicAssetUrl } from "./cdn-buckets.ts";

/**
 * The public URL of a stored object — the server-side counterpart of the
 * browser's `getPublicUrl` in src/lib/storage.ts.
 *
 * Every edge function that persists or re-fetches an asset URL should use this
 * rather than `admin.storage.from(...).getPublicUrl(...)`. Calling Supabase's
 * builder directly is how `generate-music` kept writing origin URLs for `sounds`
 * after stage 1 shipped, and after stage 2 it is worse than cosmetic: for an
 * R2-backed bucket the origin URL points at bytes that are not there.
 */
export function publicUrlFor(admin: SupabaseClient, bucket: string, path: string): string {
  return publicAssetUrl(
    bucket,
    path,
    Deno.env.get("ASSET_CDN_URL")?.trim() ?? null,
    () => admin.storage.from(bucket).getPublicUrl(path).data.publicUrl,
  );
}

/** Fetches raw bytes from a public URL — works for both https:// (Meshy/storage) and data: (MESHY_MOCK) URLs. */
export async function fetchBytes(url: string): Promise<Uint8Array> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch failed (${res.status}): ${url}`);
  return new Uint8Array(await res.arrayBuffer());
}

/**
 * Objects are immutable — a new image means a new UUID, never a mutated key —
 * so the CDN is told it may keep them for a month. Matches the Worker's own
 * override; stored here too so the value survives a direct R2 read.
 */
const IMMUTABLE_CACHE_CONTROL = "public, max-age=2678400, immutable";

export async function uploadWithRetry(
  admin: SupabaseClient,
  bucket: string,
  path: string,
  bytes: Uint8Array | Blob,
  contentType: string,
): Promise<void> {
  // ASSET_CDN_URL is part of the condition, not an afterthought: an R2 object is
  // only reachable through the Worker, so writing to R2 without a CDN hostname
  // configured would store bytes that no URL we can build points at. Falling back
  // to Supabase Storage in that state keeps a half-configured deploy working
  // exactly as it did before — the same no-op-until-configured rule as stage 1.
  const r2 =
    isR2Bucket(bucket) && Deno.env.get("ASSET_CDN_URL")?.trim()
      ? r2ConfigFrom((key) => Deno.env.get(key))
      : null;

  let lastErr = "";
  for (let attempt = 1; attempt <= 4; attempt++) {
    if (r2) {
      // R2 answers with an HTTP status, not a Supabase error object, so failure
      // arrives as a throw; catch it into the same retry shape as below.
      try {
        const body = bytes instanceof Uint8Array ? bytes : new Uint8Array(await bytes.arrayBuffer());
        await putObject(r2, {
          key: r2ObjectKey(bucket, path),
          body,
          contentType,
          cacheControl: IMMUTABLE_CACHE_CONTROL,
        });
        return;
      } catch (err) {
        lastErr = err instanceof Error ? err.message : String(err);
      }
    } else {
      const { error } = await admin.storage.from(bucket).upload(path, bytes, {
        contentType,
        upsert: true,
      });
      if (!error) return;
      lastErr = error.message;
    }
    if (attempt < 4) await new Promise((r) => setTimeout(r, 500 * attempt));
  }
  throw new Error(`Upload failed after 4 attempts (${path}): ${lastErr}`);
}
