/**
 * Storage upload/download helpers, shared by every edge function that
 * uploads generated bytes (chronicle images, mini style renders, mini model
 * files) or reads them back (mini composition — poll-meshy-jobs, forge-mini
 * `set_base`). Storage occasionally returns a transient 502/Bad Gateway on
 * upload — retry a few times with backoff before giving up. upsert:true so a
 * partially-written object from a failed attempt doesn't cause a 409.
 *
 * This is also the seam where server-generated bytes land in R2 rather than
 * Supabase Storage (#577 stage 2). Every server-side write already funnels
 * through `uploadWithRetry`, so routing here covers generate-chronicle-image,
 * generate-music, forge-mini and poll-meshy-jobs without touching any of them.
 *
 * There is deliberately no presigning on this path: an edge function running
 * with the service role has the R2 credentials already, and a presigned URL
 * would only add a round trip and a bearer credential with a lifetime.
 */
import type { SupabaseClient } from "@supabase/supabase-js";
import { r2ConfigFrom, r2ObjectKey, r2WritesEnabled, IMMUTABLE_CACHE_CONTROL } from "./r2/config.ts";
import { putObject } from "./r2/client.ts";
import { publicAssetUrl } from "./cdn-buckets.ts";

/**
 * The public URL of a stored object — the server-side counterpart of the
 * browser's `getPublicUrl` in src/lib/storage/urls.ts.
 *
 * Every edge function that persists or re-fetches an asset URL should use this
 * rather than `admin.storage.from(...).getPublicUrl(...)`. Calling Supabase's
 * builder directly is how `generate-music` kept writing origin URLs for `sounds`
 * after stage 1 shipped, and after stage 2 it is worse than cosmetic: for an
 * R2-backed bucket the origin URL points at bytes that are not there.
 */
export function publicUrlFor(admin: SupabaseClient, bucket: string, path: string): string {
  return publicAssetUrl(
    bucket,
    path,
    Deno.env.get("ASSET_CDN_URL")?.trim() ?? null,
    () => admin.storage.from(bucket).getPublicUrl(path).data.publicUrl,
  );
}

/** Fetches raw bytes from a public URL — works for both https:// (Meshy/storage) and data: (MESHY_MOCK) URLs. */
export async function fetchBytes(url: string): Promise<Uint8Array> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch failed (${res.status}): ${url}`);
  return new Uint8Array(await res.arrayBuffer());
}

export async function uploadWithRetry(
  admin: SupabaseClient,
  bucket: string,
  path: string,
  bytes: Uint8Array | Blob,
  contentType: string,
): Promise<void> {
  const r2 =
    r2WritesEnabled(bucket, Deno.env.get("ASSET_CDN_URL"))
      ? r2ConfigFrom((key) => Deno.env.get(key))
      : null;

  // Converted once, outside the retry loop — a 50 MB mini model re-read from
  // its Blob on every attempt would multiply memory churn by the retry count
  // for bytes that cannot change between attempts.
  const body = bytes instanceof Uint8Array ? bytes : new Uint8Array(await bytes.arrayBuffer());

  let lastErr = "";
  for (let attempt = 1; attempt <= 4; attempt++) {
    // Same rule as the browser path (src/lib/storage/r2.ts): R2 trouble is
    // infrastructure, not permission, and must degrade to Supabase Storage
    // rather than fail the caller — the Worker's dual-read serves either store.
    // Two attempts against R2, then the remaining attempts go to Supabase; an
    // R2 outage therefore costs two extra round trips, never a failed
    // generation. (There is no refusal case to preserve here: this path runs
    // with the service role, which the write policy does not constrain.)
    if (r2 && attempt <= 2) {
      try {
        await putObject(r2, {
          key: r2ObjectKey(bucket, path),
          body,
          contentType,
          cacheControl: IMMUTABLE_CACHE_CONTROL,
        });
        return;
      } catch (err) {
        lastErr = err instanceof Error ? err.message : String(err);
        if (attempt === 2) {
          console.warn(`uploadWithRetry: R2 unreachable for ${bucket}/${path}, falling back to Supabase Storage: ${lastErr}`);
        }
      }
    } else {
      const { error } = await admin.storage.from(bucket).upload(path, body, {
        contentType,
        upsert: true,
      });
      if (!error) return;
      lastErr = error.message;
    }
    if (attempt < 4) await new Promise((r) => setTimeout(r, 500 * attempt));
  }
  throw new Error(`Upload failed after 4 attempts (${path}): ${lastErr}`);
}
