/**
 * Storage upload/download helpers, shared by every edge function that
 * uploads generated bytes (chronicle images, mini style renders, mini model
 * files) or reads them back (mini composition — poll-meshy-jobs, forge-mini
 * `set_base`). Storage occasionally returns a transient 502/Bad Gateway on
 * upload — retry a few times with backoff before giving up. upsert:true so a
 * partially-written object from a failed attempt doesn't cause a 409.
 */
import type { SupabaseClient } from "@supabase/supabase-js";

/** Fetches raw bytes from a public URL — works for both https:// (Meshy/storage) and data: (MESHY_MOCK) URLs. */
export async function fetchBytes(url: string): Promise<Uint8Array> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch failed (${res.status}): ${url}`);
  return new Uint8Array(await res.arrayBuffer());
}

export async function uploadWithRetry(
  admin: SupabaseClient,
  bucket: string,
  path: string,
  bytes: Uint8Array | Blob,
  contentType: string,
): Promise<void> {
  let lastErr = "";
  for (let attempt = 1; attempt <= 4; attempt++) {
    const { error } = await admin.storage.from(bucket).upload(path, bytes, {
      contentType,
      upsert: true,
    });
    if (!error) return;
    lastErr = error.message;
    if (attempt < 4) await new Promise((r) => setTimeout(r, 500 * attempt));
  }
  throw new Error(`Upload failed after 4 attempts (${path}): ${lastErr}`);
}
