import { describe, expect, it } from "vitest";
import {
  GLYPH_SETS,
  INLINE_PAD,
  STANDALONE_PAD,
  assertGlyphName,
  glyphModule,
  inlineGlyph,
  normalizeTrace,
  previewSvg,
  readGlyph,
  spliceGlyph,
  standaloneSvg,
} from "./glyphTrace";

// The shape potrace -s --tight writes.
const trace = (w: number, h: number, d = "M0 0h10v10z") =>
  `<?xml version="1.0" standalone="no"?>
<svg version="1.0" xmlns="http://www.w3.org/2000/svg" width="${w}pt" height="${h}pt" viewBox="0 0 ${w} ${h}">
<g transform="translate(0,${h}) scale(0.1,-0.1)"
fill="#000000" stroke="none">
<path d="${d}"/>
</g>
</svg>`;

describe("normalizeTrace", () => {
  it("fits the long side to the box minus padding and centers the short one", () => {
    const t = normalizeTrace(trace(200, 100), INLINE_PAD);
    expect(t.scale).toBeCloseTo(88 / 200);
    expect(t.tx).toBeCloseTo(6);
    expect(t.ty).toBeCloseTo((100 - 100 * (88 / 200)) / 2);
  });

  it("refuses a file that is not a potrace trace", () => {
    expect(() => normalizeTrace("<svg/>", INLINE_PAD, "x.svg")).toThrow("no viewBox in x.svg");
    expect(() => normalizeTrace('<svg viewBox="0 0 1 1"></svg>', INLINE_PAD)).toThrow("no <g>");
  });
});

describe("inlineGlyph", () => {
  it("tints with currentColor and drops potrace's wrapper groups and whitespace", async () => {
    const inner = await inlineGlyph(normalizeTrace(trace(300, 300, "M0 0l100 0 0 100 -100 0z"), INLINE_PAD));
    expect(inner).toContain('fill="currentColor"');
    expect(inner).not.toContain("#000000");
    expect(inner).not.toContain("\n");
    expect(inner).not.toContain("translate(0,300)");
  });
});

describe("standaloneSvg", () => {
  it("wraps the untouched trace in the shared viewBox", () => {
    const svg = standaloneSvg(normalizeTrace(trace(80, 80), STANDALONE_PAD));
    expect(svg).toContain('viewBox="0 0 100 100"');
    expect(svg).toContain('<g transform="translate(10 10) scale(1)">');
    expect(svg).toContain('fill="#000000"');
  });
});

describe("glyphModule and spliceGlyph", () => {
  const mod = glyphModule(GLYPH_SETS.dice, [
    ["d4", "<g>four</g>"],
    ["d6", "<g>six</g>"],
  ]);

  it("writes a module the splicer can round-trip", () => {
    expect(mod).toBe(
      "// AUTO-GENERATED by scripts/glyphs — do not edit by hand.\n" +
        "// Inner SVG markup for custom polyhedral-dice glyphs, normalized to a 0 0 100 100 viewBox.\n" +
        'export const DICE_GLYPHS = {\n  d4: "<g>four</g>",\n  d6: "<g>six</g>",\n} as const;\n',
    );
    expect(spliceGlyph(mod, "d6", "<g>six</g>")).toBe(mod);
  });

  it("replaces an existing entry in place and leaves the others alone", () => {
    const out = spliceGlyph(mod, "d4", "<g>new</g>");
    expect(out).toContain('  d4: "<g>new</g>",\n  d6: "<g>six</g>",');
  });

  it("appends a new entry before the closing brace", () => {
    expect(spliceGlyph(mod, "d8", "<g>eight</g>")).toContain('  d6: "<g>six</g>",\n  d8: "<g>eight</g>",\n} as const;');
  });

  it("takes `$` in markup literally", () => {
    expect(spliceGlyph(mod, "d4", "<g>$&$1</g>")).toContain('  d4: "<g>$&$1</g>",');
  });

  it("reads back what it wrote, and null for a missing key", () => {
    const quoted = '<g fill="currentColor">x</g>';
    expect(readGlyph(spliceGlyph(mod, "d8", quoted), "d8")).toBe(quoted);
    expect(readGlyph(mod, "d20")).toBeNull();
  });
});

describe("previewSvg", () => {
  it("paints currentColor black on white so the glyph is visible as a PNG", () => {
    const svg = previewSvg("<g>x</g>");
    expect(svg).toContain('color="#000"');
    expect(svg).toContain('<rect width="100%" height="100%" fill="#fff"/><g>x</g>');
  });
});

describe("assertGlyphName", () => {
  it("accepts identifiers and refuses anything that would need quoting", () => {
    expect(() => assertGlyphName("d100")).not.toThrow();
    expect(() => assertGlyphName("hallOfTheFallen")).not.toThrow();
    expect(() => assertGlyphName("hall-of-the-fallen")).toThrow();
    expect(() => assertGlyphName("Fallen")).toThrow();
  });
});
