/**
 * The pure half of the glyph pipeline: turn a tight potrace trace into a
 * glyph normalized to the shared 0 0 100 100 box, and write or splice the
 * generated TS modules that `src/lib/icons.ts` reads. The CLI beside it does
 * the file and ImageMagick work; everything here is string in, string out.
 *
 * The source art is not in the repo. It lives in the maintainer's local,
 * gitignored `art-src/` dump; the committed output is the generated modules
 * (and `public/assets/damage-types/*.svg`). The `/glyph` skill
 * (`.agents/skills/glyph/`) is the procedure that drives a run.
 */

/** Every glyph is normalized into a square box of this side. */
export const GLYPH_BOX = 100;

/**
 * Padding inside the box. Inline glyphs sit tighter so they fill the space
 * like the Lucide icons beside them; standalone SVGs (damage-type masks,
 * one-off art) keep a wider margin.
 */
export const INLINE_PAD = 6;
export const STANDALONE_PAD = 10;

/** A generated module of inline glyph markup, as `glyph()` consumes it. */
export interface GlyphSet {
  /** Repo-relative path of the generated module. */
  file: string;
  exportName: string;
  /** Completes "Inner SVG markup for …" in the module header. */
  description: string;
}

export const GLYPH_SETS = {
  crafting: {
    file: "src/lib/craftingGlyphs.generated.ts",
    exportName: "CRAFTING_GLYPHS",
    description: "custom crafting-discipline glyphs",
  },
  dice: {
    file: "src/lib/diceGlyphs.generated.ts",
    exportName: "DICE_GLYPHS",
    description: "custom polyhedral-dice glyphs",
  },
  nav: {
    file: "src/lib/navGlyphs.generated.ts",
    exportName: "NAV_GLYPHS",
    description: "custom nav glyphs",
  },
  "nav-assets": {
    file: "src/lib/navGlyphs.assets.generated.ts",
    exportName: "NAV_GLYPHS",
    description: "custom nav glyphs",
  },
} as const satisfies Record<string, GlyphSet>;

export type GlyphSetName = keyof typeof GLYPH_SETS;

export function isGlyphSetName(value: string): value is GlyphSetName {
  return Object.hasOwn(GLYPH_SETS, value);
}

/** Keys are emitted unquoted, so a glyph name must be a plain identifier. */
export function assertGlyphName(name: string): void {
  if (!/^[a-z][A-Za-z0-9]*$/.test(name)) {
    throw new Error(`glyph name '${name}' must be a lowerCamel identifier`);
  }
}

export interface NormalizedTrace {
  /** potrace's `<g transform=…>…</g>`, untouched. */
  group: string;
  width: number;
  height: number;
  scale: number;
  tx: number;
  ty: number;
}

const round3 = (n: number) => Number(n.toFixed(3));

/** Scale a tight trace to fit the box minus `pad` on each side, centered. */
export function normalizeTrace(svg: string, pad: number, label = "trace"): NormalizedTrace {
  const vb = svg.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
  if (!vb) throw new Error(`no viewBox in ${label}`);
  const group = svg.match(/<g transform=[\s\S]*?<\/g>/)?.[0];
  if (!group) throw new Error(`no <g> in ${label}`);
  const width = parseFloat(vb[1]);
  const height = parseFloat(vb[2]);
  const scale = (GLYPH_BOX - pad * 2) / Math.max(width, height);
  return {
    group,
    width,
    height,
    scale,
    tx: (GLYPH_BOX - width * scale) / 2,
    ty: (GLYPH_BOX - height * scale) / 2,
  };
}

function transform(t: NormalizedTrace): string {
  return `translate(${round3(t.tx)} ${round3(t.ty)}) scale(${round3(t.scale)})`;
}

/**
 * Inner markup for `glyph()`. potrace hard-codes a black fill; rewriting it to
 * currentColor lets the glyph tint with the text around it. (potrace emits the
 * attribute on its own line, so match the attribute, not a leading space.)
 */
export function inlineGlyph(t: NormalizedTrace): string {
  const group = t.group.replace(/fill="#000000"/g, 'fill="currentColor"');
  return `<g transform="${transform(t)}">${group}</g>`;
}

/** A self-contained SVG file, fill left as traced (masks ignore colour). */
export function standaloneSvg(t: NormalizedTrace): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${GLYPH_BOX} ${GLYPH_BOX}">
<g transform="${transform(t)}">
${t.group}
</g>
</svg>
`;
}

function entryLine(name: string, inner: string): string {
  return `  ${name}: ${JSON.stringify(inner)},`;
}

/** The whole generated module for a set, entries in the order given. */
export function glyphModule(set: GlyphSet, entries: ReadonlyArray<readonly [string, string]>): string {
  const body = entries.map(([name, inner]) => entryLine(name, inner)).join("\n");
  return (
    `// AUTO-GENERATED by scripts/glyphs — do not edit by hand.\n` +
    `// Inner SVG markup for ${set.description}, normalized to a 0 0 100 100 viewBox.\n` +
    `export const ${set.exportName} = {\n${body}\n} as const;\n`
  );
}

/**
 * Add or replace one entry in an existing generated module, leaving every
 * other entry byte-identical — the other glyphs' traces are scratch and
 * usually long gone, so a full regeneration is rarely possible.
 */
export function spliceGlyph(source: string, name: string, inner: string): string {
  const entry = entryLine(name, inner);
  const existing = new RegExp(`^  ${name}: .*,$`, "m");
  const out = existing.test(source)
    ? source.replace(existing, () => entry)
    : source.replace(/^\} as const;$/m, () => `${entry}\n} as const;`);
  if (!out.includes(entry)) throw new Error(`failed to splice '${name}'`);
  return out;
}

/** One entry's inner markup from a generated module, or null when absent. */
export function readGlyph(source: string, name: string): string | null {
  const line = source.match(new RegExp(`^  ${name}: (".*"),$`, "m"));
  return line ? (JSON.parse(line[1]) as string) : null;
}

/** An entry as a black-on-white SVG, to rasterise and look at. */
export function previewSvg(inner: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${GLYPH_BOX} ${GLYPH_BOX}" width="256" height="256" color="#000"><rect width="100%" height="100%" fill="#fff"/>${inner}</svg>\n`;
}
