<template>
  <ListPageLayout title="Sound library credits">
    <template #actions>
      <RouterLink
        to="/soundboard"
        class="px-3 py-1.5 rounded-md border border-border text-caption text-muted-foreground hover:text-foreground transition-colors"
      >
        Back to soundboard
      </RouterLink>
    </template>

    <div class="space-y-5">
      <p class="text-body text-muted-foreground max-w-3xl">
        Every sound in the Grimoire library is either public domain (CC0) or Creative Commons
        Attribution. The attributed ones are credited below, and each credit travels with the sound
        onto your board — you don't have to reproduce any of this yourself.
      </p>

      <LoadingSpinner v-if="isPending" />

      <p v-else-if="isError" class="text-body text-destructive">
        Could not load the credits. {{ errorMessage }}
      </p>

      <template v-else-if="entries">
        <section class="space-y-2">
          <h2 class="font-cinzel text-body text-gold-300">
            Attribution required ({{ credited.length }})
          </h2>
          <p v-if="credited.length === 0" class="text-caption text-muted-foreground italic">
            Nothing in the library currently requires credit.
          </p>
          <ul v-else class="space-y-1.5">
            <li
              v-for="entry in credited"
              :key="entry.id"
              class="relative overflow-hidden rounded-md border border-border bg-card/30 px-3 py-2 pl-4"
            >
              <!-- Gold spine: this is the half of the catalogue that carries an
                   obligation, and it should look different from the courtesy
                   list below at a glance. -->
              <span class="absolute inset-y-0 left-0 w-0.75 bg-gold-500" />
              <p class="text-body-sm text-foreground">{{ entry.attribution }}</p>
              <p class="text-caption text-muted-foreground">
                {{ entry.collection }} · {{ entry.license }} ·
                <a
                  :href="entry.source_page"
                  target="_blank"
                  rel="noopener noreferrer"
                  class="underline hover:text-foreground"
                >
                  source
                </a>
              </p>
            </li>
          </ul>
        </section>

        <section class="space-y-2">
          <h2 class="font-cinzel text-body text-gold-300">
            Public domain ({{ publicDomain.length }})
          </h2>
          <p class="text-caption text-muted-foreground">
            CC0 — no credit required. Listed as a courtesy to the people who released them.
          </p>
          <ul class="flex flex-wrap gap-1.5">
            <li
              v-for="author in publicDomainAuthors"
              :key="author"
              class="rounded border border-border bg-card/30 px-2 py-0.5 text-caption text-muted-foreground"
            >
              {{ author }}
            </li>
          </ul>
        </section>
      </template>
    </div>
  </ListPageLayout>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { RouterLink } from "vue-router";
import { useQuery } from "@tanstack/vue-query";
import { supabase } from "@/lib/supabase";
import ListPageLayout from "@/components/common/ListPageLayout.vue";
import LoadingSpinner from "@/components/common/LoadingSpinner.vue";
import type { SoundLibraryEntry } from "@/types/sound.types";

/**
 * The in-app credits screen for the curated library.
 *
 * Read live from `sound_library` rather than shipped as a static list: the
 * catalogue grows, and a credits page that has to be regenerated by hand is a
 * credits page that will eventually be wrong. Being wrong here is a licence
 * breach, not a typo.
 */

type CreditRow = Pick<
  SoundLibraryEntry,
  "id" | "collection" | "license" | "attribution" | "source_page" | "author"
>;

const { data: entries, isPending, isError, error } = useQuery({
  queryKey: ["sound_library_credits"],
  queryFn: async (): Promise<CreditRow[]> => {
    const { data, error: err } = await supabase
      .from("sound_library")
      .select("id, collection, license, attribution, source_page, author")
      .order("attribution", { ascending: true, nullsFirst: false })
      .order("author", { ascending: true });
    if (err) throw err;
    if (data === null) throw new Error("sound_library returned no payload");
    return data as CreditRow[];
  },
  // The catalogue changes when we ship, not while a DM is looking at it.
  staleTime: 1000 * 60 * 60,
});

/** Undefined is useQuery's "not loaded yet"; the template gates on it separately. */
const loaded = computed<CreditRow[]>(() => (entries.value === undefined ? [] : entries.value));

const credited = computed(() => loaded.value.filter((e) => e.attribution !== null));
const publicDomain = computed(() => loaded.value.filter((e) => e.attribution === null));

/** CC0 needs no credit, so the courtesy list is by author rather than by file. */
const publicDomainAuthors = computed(() =>
  [...new Set(publicDomain.value.map((e) => e.author))].sort((a, b) => a.localeCompare(b)),
);

const errorMessage = computed(() => {
  if (!error.value) return "";
  return error.value instanceof Error ? error.value.message : "Unknown error";
});
</script>
