import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";

/**
 * A source-shape guard, for the same reason `admin_authorization_guards`'s
 * structural assertions are body-based: the behaviour this protects cannot be
 * observed in the test DOM. `normalizeGeneratedTile` runs the tile through
 * `createImageBitmap` → `drawImage` → `canvas.toBlob`, and happy-dom has no
 * canvas — so there is no way to assert "the XMP packet survived normalization"
 * by running the code.
 *
 * What can be asserted is that the marked blob is the one that leaves. The
 * edge function marks the generated bytes (EU AI Act Art 50, #889 S2), canvas
 * re-encoding drops embedded metadata unconditionally, and the re-embed here is
 * the only thing standing between a marked tile and an unmarked one reaching
 * storage. Delete it and every gate stays green while the disclosure quietly
 * stops shipping — which is precisely the failure this file exists to make loud.
 */
const SOURCE = readFileSync(
  path.join(process.cwd(), "src/composables/cartographer/useTilePacks.ts"),
  "utf8",
);

describe("useTilePacks — generated tiles keep their provenance", () => {
  it("re-embeds the source XMP into the normalized tile", () => {
    expect(SOURCE).toContain("readEmbeddedXmp");
    expect(SOURCE).toContain("inheritXmpIntoVariant");
  });

  it("sends the re-marked blob to the edge function, never the bare normalized one", () => {
    // `image_b64` is what gets persisted. If it is ever built from `normalized`
    // directly again, the canvas re-encode has already stripped the packet.
    expect(SOURCE).toMatch(/image_b64:\s*await toBase64\(markedNormalized\)/);
    expect(SOURCE).not.toMatch(/image_b64:\s*await toBase64\(normalized\)/);
  });

  it("keeps the style reference unmarked, deliberately", () => {
    // styleReferenceFrom's output is fed back into later generation calls and
    // is never shown to a user, so it carries no disclosure duty. The comment
    // saying so is load-bearing: without it the asymmetry looks like an
    // oversight and someone "fixes" it.
    expect(SOURCE).toMatch(/never shown to any user/i);
  });
});
