import type { DndSettingDef } from "./types";

export const darksunSetting: DndSettingDef = {
  id: "darksun",
  label: "Dark Sun",

  defaultAiPrompt:
    "Dying desert world with a brutal, sun-bleached palette — bone white, terracotta orange, ochre, obsidian black, and the sickly crimson of a sun too close and too hot. Cast harsh overhead shadows; midday on Athas has no mercy. " +
    "There is no metal — weapons and armour are stone, bone, chitin, obsidian, and hardened leather. Show this: a sword made of bone with sinew wrapping and a chipped edge, armour of beetle carapace stitched with gut. Everything is maintained, repaired, precious. " +
    "Characters wear minimal cloth against the heat — wrapped linen, open shoulders, tattoos and scarification as cultural markers, psionic focus crystals worn or carried. Gladiators show arena scars and sponsor brands. Slaves show restraint marks. " +
    "Water is the true currency. Show it only where it matters: a waterskin strapped close, a cracked lip, the relief on a face finding a shaded well. Its absence should feel like tension. " +
    "The landscape is actively hostile: silt dust on every surface, heat shimmer distorting the horizon, dead trees bleached to sculpture, carcasses stripped clean by the sun. Vegetation, when it exists, should feel miraculous. " +
    "Sorcerer-kings should look like they have absorbed centuries of power — ancient and terrible, their templars wearing the city's colours like a brand. The Dragon is not a creature. It is a catastrophe. " +
    "Keep the mood brutal, defiant, and survival-driven — beauty exists here, but it is hard-edged and costs something.",

  calendar: {
    name: "Dark Sun (Calendar of Athas)",
    epochName: "FY",
    defaultYear: 190,
    weekStyle: "tenday",
    weekRowNames: ["First Tenday", "Second Tenday", "Third Tenday"],
    months: [
      { name: "Scorch",             alias: "High Sun I",      days: 30 },
      { name: "Morrow",             alias: "High Sun II",     days: 30 },
      { name: "Rest",               alias: "High Sun III",    days: 30 },
      { name: "Gather",             alias: "High Sun IV",     days: 30 },
      { name: "Cooling",            alias: "Low Sun I",       days: 30 },
      { name: "Haze",               alias: "Low Sun II",      days: 30 },
      { name: "Wind",               alias: "Low Sun III",     days: 30 },
      { name: "Sorrow",             alias: "Low Sun IV",      days: 30 },
      { name: "Smolder",            alias: "Wind & Fire I",   days: 30 },
      { name: "Desert's Vengeance", alias: "Wind & Fire II",  days: 30 },
      { name: "Bloom",              alias: "Wind & Fire III", days: 30 },
      { name: "Embers",             alias: "Wind & Fire IV",  days: 30 },
    ],
    intercalaryDays: [
      { name: "Festival of the Highest Sun", afterMonth: 4,  description: "The scorching midpoint of High Sun — a brutal day when even the sorcerer-kings' templars retreat indoors. Gladiatorial games are held in shaded arenas." },
      { name: "Day of Rest",                 afterMonth: 8,  description: "The sole intercalary day all city-states observe. Even slave labour halts. Defilers and preservers alike feel the draw of the dying land on this day." },
      { name: "Storm's Crown",               afterMonth: 11, description: "The peak of Wind & Fire season — violent dust storms sweep the Tablelands. Caravans shelter and psions meditate on the Way amidst the howling dark." },
    ],
    leapYearRule: "none",
  },

  locations: [
    { name: "Athas",               location_type: "world",     notes: "A dying world stripped of life by defiling magic. No gods answer prayers here; psionics and primal power fill the void. The sun burns crimson.", tags: ["dying world", "defiling magic", "dark sun", "crimson sun"] },
    { name: "The Tablelands",      location_type: "region",    parent: "Athas",              notes: "The primary region of Athas — a rocky plateau dominated by seven City-States of the sorcerer-kings, separated by vast desert wastelands.", tags: ["city-states", "sorcerer-kings", "plateau"] },
    { name: "Tyr",                 location_type: "city",      parent: "The Tablelands",     notes: "The City of Freedom — the only city-state where the sorcerer-king Kalak was slain. Tyr struggles to maintain a fragile republic.", tags: ["freedom", "kalak dead", "republic", "gladiators"] },
    { name: "Urik",                location_type: "city",      parent: "The Tablelands",     notes: "The City of Lions — ruled by the calculating sorcerer-king Hamanu. The most militaristic city-state, disciplined and expansionist.", tags: ["hamanu", "military", "lions", "obsidian"] },
    { name: "Nibenay",             location_type: "city",      parent: "The Tablelands",     notes: "The City of Spires — ruled by the enigmatic sorcerer-king Nibenay (the Shadow King). A city of intrigue and strict gender roles.", tags: ["nibenay", "shadow king", "spires", "templars"] },
    { name: "Gulg",                location_type: "city",      parent: "The Tablelands",     notes: "The Forest City — ruled by the primal sorcerer-queen Lalali-Puy (the Oba). One of the most spiritual city-states.", tags: ["lalali-puy", "oba", "forest", "primal"] },
    { name: "Balic",               location_type: "city",      parent: "The Tablelands",     notes: "The City of Sails — a coastal city on the Sea of Silt ruled by Andropinis. Known for its Senate and fleet of silt skimmers.", tags: ["andropinis", "senate", "silt skimmers", "trade"] },
    { name: "Raam",                location_type: "city",      parent: "The Tablelands",     notes: "The City of Unrest — once ruled by Abalach-Re, now in chaos after her death. Gang wars and slave uprisings tear the city apart.", tags: ["abalach-re", "chaos", "raam", "unrest"] },
    { name: "Draj",                location_type: "city",      parent: "The Tablelands",     notes: "The City of the Moons — ruled by Tectuktitlay, who demands blood sacrifice at his twin pyramids to 'feed' the crimson sun.", tags: ["tectuktitlay", "sacrifice", "pyramids", "moons"] },
    { name: "Sea of Silt",         location_type: "wilderness",parent: "Athas",              notes: "An enormous desert of grey powdery silt stretching for hundreds of miles. Silt storms can bury ships whole; strange creatures lurk beneath.", tags: ["silt", "desert sea", "silt skimmers", "hazard"] },
    { name: "Ringing Mountains",   location_type: "wilderness",parent: "Athas",              notes: "A vast mountain range encircling much of the Tablelands, home to rogue tribes and abandoned dwarven fortresses.", tags: ["mountains", "frontier", "dwarves", "dangerous"] },
    { name: "The Obsidian Wastes", location_type: "wilderness",parent: "Athas",              notes: "A vast plain of black volcanic glass beyond the Ringing Mountains. Almost nothing lives here.", tags: ["obsidian", "desolate", "volcanic", "wasteland"] },
    { name: "The Deadlands",       location_type: "wilderness",parent: "Athas",              notes: "A blasted region of utter devastation, believed to be where the Dragon first tested mass defiling. Utterly lifeless.", tags: ["dragon", "defiled", "lifeless", "history"] },
  ],

  factions: [
    // Resistance
    { name: "The Veiled Alliance",        description: "A secret network of preserver wizards operating cells in every city-state on the Tablelands. They protect each other from templar death squads, share arcane knowledge, and work toward the eventual overthrow of the sorcerer-kings — slowly, carefully, at great cost.", faction_type: "Secret Society", alignment: "Chaotic Good", tags: ["preservers", "secret", "resistance", "wizards"] },
    { name: "The Wanderers",              description: "Loosely organised bands of freed slaves, escaped gladiators, and wilderness survivors who reject all city-state authority. Some wander to survive; others have begun building something in the deep desert that might one day matter.", faction_type: "Other", alignment: "Chaotic Neutral", tags: ["freed slaves", "wilderness", "survival", "resistance"] },
    // Free City
    { name: "Tyrian Republic",            description: "The fragile new government of Tyr following Kalak's assassination — a council of nobles, templars, and free citizens trying to build something that has never existed on Athas: a democratic city. Every faction on the Tablelands is watching it fail, or trying to make it fail.", faction_type: "Government", alignment: "Neutral Good", tags: ["tyr", "freedom", "republic", "unstable", "kalak"] },
    // City-State Templarates
    { name: "Templarate of Urik",         description: "Hamanu's templars — the disciplined divine-powered enforcers of Urik's military sorcerer-king. The most organized templarate on the Tablelands, operating with military precision and absolute loyalty to Hamanu.", faction_type: "Government", alignment: "Lawful Evil", tags: ["urik", "hamanu", "templars", "military", "enforcers"] },
    { name: "Templarate of Nibenay",      description: "The templars of the Shadow King — all female, known as Shadow Brides. They hold administrative and religious power in Nibenay while their reclusive sorcerer-king remains hidden in his palace, appearing only when he must.", faction_type: "Government", alignment: "Lawful Evil", tags: ["nibenay", "shadow king", "templars", "female", "religion"] },
    { name: "Templarate of Gulg",         description: "The Judaga warriors who serve Lalali-Puy, the Oba of Gulg. Part templar, part priest, part judge — in Gulg, the Oba's word is divine law, and her Judaga enforce it through a primal spiritual authority that has no parallel in other city-states.", faction_type: "Government", alignment: "Lawful Neutral", tags: ["gulg", "lalali-puy", "oba", "judaga", "primal"] },
    { name: "Senate of Balic",            description: "Andropinis runs Balic as an elected dictator, but the Senate still functions — debating laws, managing trade, and arguing loudly about the fleet. Senators know the limits of their power and stay carefully within them.", faction_type: "Government", alignment: "Lawful Neutral", tags: ["balic", "andropinis", "senate", "trade", "silt skimmers"] },
    { name: "Templarate of Draj",         description: "Tectuktitlay demands blood sacrifice, and his templars supply it. The Draj templarate is simultaneously a military force, a religious institution, and the primary source of sacrificial victims — drawn from slaves, prisoners, and unlucky citizens.", faction_type: "Government", alignment: "Lawful Evil", tags: ["draj", "tectuktitlay", "sacrifice", "templars", "moons"] },
    { name: "Raam Factions",              description: "After Abalach-Re's death, Raam has no controlling templarate — just rival gangs of ex-templars, warlords, and sorcerer-aspirants tearing the city apart. Multiple factions compete for control, and the city burns slowly.", faction_type: "Criminal", alignment: "Chaotic Evil", tags: ["raam", "abalach-re", "chaos", "gangs", "collapse"] },
    // Merchant Houses
    { name: "House Wavir",                description: "The wealthiest and most politically connected of the great merchant houses, based in Balic. House Wavir runs trade routes the full length of the Tablelands and maintains enough mercenary muscle to defend them.", faction_type: "Merchant", alignment: "Lawful Neutral", tags: ["merchants", "balic", "trade", "wavir", "caravans"] },
    { name: "House Shom",                 description: "An ancient and declining merchant house whose past wealth is more impressive than its current operations. House Shom deals in slaves and luxury goods and has been losing ground to younger houses for decades — a fact that makes them desperate and dangerous.", faction_type: "Merchant", alignment: "Neutral Evil", tags: ["merchants", "slaves", "shom", "declining", "luxury"] },
    { name: "House M'ke",                 description: "A mid-sized house specializing in communications and courier services — runners, message lizards, and the fastest scribes on the Tablelands. They sell information as much as they sell goods, and they're careful never to be the cheapest option.", faction_type: "Merchant", alignment: "True Neutral", tags: ["merchants", "couriers", "information", "mke", "communications"] },
    { name: "House Inika",                description: "A merchant house based in Raam, now deeply entangled in the city's post-collapse chaos. House Inika has positioned itself as a neutral broker between rival factions, which is extremely profitable and extremely dangerous.", faction_type: "Merchant", alignment: "True Neutral", tags: ["merchants", "raam", "inika", "neutral", "broker"] },
    { name: "House Stel",                 description: "The most militaristic of the great merchant houses — House Stel maintains a private army that rivals city-state legions and takes contracts that other houses call 'not worth the trouble.' They are worth the trouble, if you can afford them.", faction_type: "Merchant", alignment: "Lawful Neutral", tags: ["merchants", "military", "stel", "private army", "urik"] },
    // Major threats
    { name: "The Dragon's Levy",          description: "Not a faction but a fact: once per year, each surviving sorcerer-king provides Borys the Dragon with one thousand sentient lives, drawn from their populations however they see fit. This thousand-life tithe is the price of the Dragon's passivity — and everyone on the Tablelands pays it.", faction_type: "Other", alignment: "Neutral Evil", tags: ["dragon", "borys", "levy", "sacrifice", "sorcerer-kings"] },
    { name: "The Urikite Legions",        description: "Hamanu's professional standing army — the most disciplined fighting force on the Tablelands, drilled to militaristic perfection and deployed with strategic precision. They are the reason Urik's neighbours do not test its borders.", faction_type: "Military", alignment: "Lawful Evil", tags: ["urik", "hamanu", "army", "military", "legions"] },
    { name: "The Planar Trade Consortium", description: "A shadowy group of off-world traders who have found their way to Athas and are quietly harvesting its unique psionic resources and rare materials. They avoid contact with sorcerer-kings whenever possible and are more disturbed by Athas than they let on.", faction_type: "Merchant", alignment: "True Neutral", tags: ["off-world", "planar", "trade", "psionic", "mysterious"] },
  ],

  heroes: [
    {
      name: "Rikus",
      race: "Mul (Dwarf-Human Half-Breed)",
      alignment: "Chaotic Good",
      occupation: "Gladiator / Hero of Tyr",
      personality: "Explosive, brave to the point of recklessness, and consumed by righteous fury at a world that made him a slave. Rikus leads with his body and rarely pauses to think. When he does think, he surprises people.",
      backstory: "The greatest gladiator in Tyr's arena, Rikus played a central role in killing the sorcerer-king Kalak and freeing the city. He fights for Tyr's republic with the same savage efficiency he once used to survive the arena — and he is deeply uncertain what freedom is supposed to feel like.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["tyr", "gladiator", "mul", "hero of tyr", "free tyr"],
    },
    {
      name: "Sadira of Tyr",
      race: "Half-Elf",
      alignment: "Neutral Good",
      occupation: "Preserver Wizard / Revolutionary",
      personality: "Principled, intelligent, and carrying the weight of a terrible power she did not ask for. Sadira chose the preserving path when it was dangerous to do so — she refuses to use defiling magic even when it would be easier.",
      backstory: "A preserver wizard from Tyr's underclass who helped bring down Kalak. She later underwent a ritual that granted her the Sun Wizard's power — fuelled by sunlight rather than life, making her the most powerful non-defiling wizard on Athas. The power terrifies her.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["tyr", "preserver", "wizard", "sun wizard", "revolutionary"],
    },
    {
      name: "Agis of Asticles",
      race: "Human",
      alignment: "Lawful Good",
      occupation: "Senator of Tyr / Psionicist",
      personality: "Thoughtful, idealistic, and genuinely committed to building something good from Tyr's ruins. Agis approaches politics with the same disciplined calm he brings to psionics. He is the conscience of the free city.",
      backstory: "A Tyrian noble and senator who was one of the key figures in the conspiracy against Kalak. Agis uses his psychic gifts and political influence to build Tyr's fragile republic. He believes — perhaps naively — that it can work.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["tyr", "senator", "psionicist", "noble", "republic"],
    },
    {
      name: "Neeva",
      race: "Mul (Dwarf-Human Half-Breed)",
      alignment: "Chaotic Good",
      occupation: "Gladiator / Warrior",
      personality: "Fierce, pragmatic, and deeply loyal to Rikus in a way she would never put into words. Neeva approaches everything the way she approaches a fight — directly, efficiently, and without apology. She has strong opinions about almost everything and states them without softening.",
      backstory: "A mul gladiator from Tyr who fought alongside Rikus and participated in the uprising against Kalak. She is one of the finest warriors in the city and has struggled with what to do with her skills in a world that is supposedly at peace.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["tyr", "gladiator", "mul", "warrior", "hero of tyr"],
    },
    {
      name: "Tithian of Mericles",
      race: "Human",
      alignment: "Neutral Evil",
      occupation: "High Templar / King of Tyr",
      personality: "Charming, treacherous, and driven by ambitions that always exceed what the current situation can satisfy. Tithian helped kill Kalak because he wanted the throne — not freedom. He smiles easily and means almost none of it.",
      backstory: "A high templar of Tyr who facilitated the assassination of Sorcerer-King Kalak and then claimed the throne for himself. He is not a liberator — he is an opportunist who correctly identified where the leverage was. He wants power, not justice, and he is very good at looking like he wants the latter.",
      status: "alive",
      relationship: "indifferent",
      portrait_url: null,
      tags: ["tyr", "king", "templar", "traitor", "ambitious"],
    },
    {
      name: "Hamanu",
      race: "Human (Sorcerer-King)",
      alignment: "Lawful Evil",
      occupation: "Sorcerer-King of Urik / Dragon-Metamorph",
      personality: "Cold, calculating, and utterly convinced of his own superiority — because he may well be right. Hamanu views everything and everyone as a resource. He is not capricious like some sorcerer-kings. He is systematic.",
      backstory: "The immortal sorcerer-king of Urik, Hamanu has ruled for thousands of years through discipline and terror. He is secretly a dragon-metamorph in mid-transformation. He watched Kalak fall with contempt — not grief. He does not intend to make the same mistakes.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["urik", "sorcerer-king", "dragon metamorph", "villain", "immortal"],
    },
    {
      name: "Tectuktitlay",
      race: "Human (Sorcerer-King)",
      alignment: "Lawful Evil",
      occupation: "Sorcerer-King of Draj / Divine Emperor",
      personality: "Theatrical, grandiose, and entirely convinced of his own divine status — the blood sacrifice demands are not cruelty but piety, in his theology. He performs godhood with complete conviction. Whether he believes it is the interesting question.",
      backstory: "The sorcerer-king of Draj who rules through the religion he constructed around himself, demanding blood sacrifice at the twin pyramids to 'feed' the crimson sun and keep it rising. His templars are simultaneously priests and soldiers. His city is simultaneously terrified and fanatically devoted.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["draj", "sorcerer-king", "sacrifice", "divine emperor", "villain"],
    },
    {
      name: "Andropinis",
      race: "Human (Sorcerer-King)",
      alignment: "Lawful Evil",
      occupation: "Dictator of Balic / Sorcerer-King",
      personality: "The most politically sophisticated of the sorcerer-kings — Andropinis runs Balic as an elected dictator with a functioning Senate, which is window dressing he maintains because it is useful. He is patient, cultured, and lethal in the specific way of people who have had centuries to perfect lethal.",
      backstory: "The sorcerer-king of Balic, a city of silt-sailors and senatorial tradition. Andropinis has maintained his power through a combination of genuine administrative competence and the same ageless sorcery that sustains all his peers. He is the most diplomatically predictable of the sorcerer-kings — which is not the same as trustworthy.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["balic", "sorcerer-king", "dictator", "senate", "villain"],
    },
    {
      name: "Lalali-Puy the Oba",
      race: "Human (Sorcerer-Queen)",
      alignment: "Lawful Evil",
      occupation: "Sorcerer-Queen of Gulg / The Oba",
      personality: "Primal, intense, and genuinely connected to a spiritual framework that gives her rule a coherent theology. Lalali-Puy is not performing godhood the way Tectuktitlay is — she believes it. This makes her both more sincere and more dangerous.",
      backstory: "The divine ruler of Gulg, the Forest City — the most spiritual of the city-states. Her Judaga templars combine the roles of priest, soldier, and judge. She draws power from primal magic as well as defiling, which gives Gulg a different flavour of brutality than its peers.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["gulg", "sorcerer-queen", "oba", "primal", "villain"],
    },
    {
      name: "Nibenay the Shadow King",
      race: "Human (Sorcerer-King)",
      alignment: "Neutral Evil",
      occupation: "Sorcerer-King of Nibenay / Scholar",
      personality: "Reclusive, intellectual, and genuinely more interested in his arcane research than in governance — which he has delegated entirely to his Shadow Brides. When he does appear, it is always for something important, and it is always unsettling.",
      backstory: "The enigmatic sorcerer-king of Nibenay, named after his own city. He has retreated into his palace-complex and emerges only rarely, leaving his all-female templar corps — the Shadow Brides — to administer the city. What he is studying in his isolation is a question no one has been able to answer.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["nibenay", "shadow king", "sorcerer-king", "reclusive", "villain"],
    },
    {
      name: "Nok",
      race: "Halfling",
      alignment: "Chaotic Neutral",
      occupation: "Halfling Elder / Forest Chief",
      personality: "Ancient, utterly alien in his values, and operating under a halfling philosophy that predates the destruction of Athas's ecology by millennia. Nok is not hostile exactly — but his species remembers when they were the apex predators, and that memory shapes everything.",
      backstory: "The leader of a halfling community in the Forest Ridge, one of the few remaining green places on Athas. Athasian halflings are not the gentle folk of other worlds — they are hunters, ritual cannibals by tradition, and the original inhabitants of a world that was ruined after their time.",
      status: "alive",
      relationship: "indifferent",
      portrait_url: null,
      tags: ["halfling", "forest ridge", "elder", "ancient", "primal"],
    },
    {
      name: "The Dragon of Athas (Borys)",
      race: "Dragon (formerly Human)",
      alignment: "Neutral Evil",
      occupation: "The Dragon / Enforcer of the Sorcerer-Kings",
      personality: "Ancient beyond measure and alien in his thinking. Borys is no longer fully conscious of his humanity. He communicates in demands and demonstrates power in ways that leave craters. He is the reason the Tablelands has stayed relatively stable — and the reason it continues to die.",
      backstory: "Once a great champion who became the first sorcerer-king to complete the dragon metamorphosis. The other kings made a pact: they feed him a thousand lives each year to keep him docile. In exchange he enforces the status quo. The Dragon is the apex predator of Athas — and also its greatest unsolved problem.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["dragon", "borys", "sorcerer-king", "apex predator", "athas"],
    },
  ],
  pantheons: [],
  deities: [],
};
