import type { DndSettingDef } from "./types";
import { DRAGONLANCE_DEITIES, DRAGONLANCE_PANTHEONS } from "@/data/settingDeities";

export const dragonlanceSetting: DndSettingDef = {
  id: "dragonlance",
  label: "Dragonlance",

  defaultAiPrompt:
    "Epic fantasy suffused with loss and hard-won hope. Three moons cast overlapping silver, red, and black light — use them to set the mood of any scene: Solinari's silver for holy moments, Lunitari's red for arcane tension, Nuitari's absence-black for dark sorcery. " +
    "Palette splits between warmth and ruin: Solace's amber vallenwood firelight and padded comfort versus the ash-grey devastation of dragonfire, scorched earth, and draconian ranks. " +
    "Knights of Solamnia wear polished plate with rose-and-sword iconography — proud, rigid, slightly archaic. Draconians should feel genuinely monstrous: scaled, acid-smelling, wrong where dragons are majestic. " +
    "Characters carry the weight of the Cataclysm in worn religious tokens, crumbling temple ruins, and the wariness of people who stopped trusting gods. Clerics who have regained their faith should look quietly luminous. " +
    "Dragonlords and their mounts should dominate compositions — scale matters. A blue dragon over a battlefield is not a detail, it is the sky. " +
    "Use environmental storytelling: trampled crops, refugee columns, destroyed shrines, campfires too small against a very dark night. " +
    "Keep the mood epic but earned — triumph costs something, and sorrow is never far.",

  calendar: {
    name: "Dragonlance (Krynn Common Calendar)",
    epochName: "AC",
    defaultYear: 351,
    weekStyle: "weekly",
    dayLabels: ["Linaras", "Palast", "Bakukal", "Bracha", "Misham", "Kirinor", "Majetag"],
    months: [
      { name: "Newkolt",    alias: "New Cold",        days: 28 },
      { name: "Deepkolt",   alias: "Deep Cold",       days: 28 },
      { name: "Brookgreen", alias: "Green Brook",     days: 28 },
      { name: "Yurthgreen", alias: "Spring Green",    days: 28 },
      { name: "Fleurgreen", alias: "Flower Green",    days: 28 },
      { name: "Holden",     alias: "Midsummer Hold",  days: 28 },
      { name: "Fierswelt",  alias: "Fierce Heat",     days: 28 },
      { name: "Reapember",  alias: "Reaping Time",    days: 28 },
      { name: "Paleswelt",  alias: "Pale Heat",       days: 28 },
      { name: "Havesthold", alias: "Harvest Hold",    days: 28 },
      { name: "Frostkolt",  alias: "Frost Cold",      days: 28 },
      { name: "Darkember",  alias: "Dark Ember",      days: 28 },
    ],
    intercalaryDays: [],
    leapYearRule: "none",
  },

  locations: [
    { name: "Krynn",                          location_type: "world",     notes: "The world of Dragonlance — a planet dominated by the struggle between Paladine, Takhisis, and the balance of Gilean.", tags: ["planet", "world"] },
    { name: "Ansalon",                        location_type: "continent", parent: "Krynn",      notes: "The primary continent of Krynn and the main setting for Dragonlance adventures.", tags: ["krynn", "dragonlance"] },
    { name: "Solamnia",                       location_type: "country",   parent: "Ansalon",   notes: "A great and ancient kingdom in northwestern Ansalon, home of the Knights of Solamnia.", tags: ["knights", "northwest", "knights of solamnia"] },
    { name: "Ergoth",                         location_type: "country",   parent: "Ansalon",   notes: "A former empire on the western coast of Ansalon, fragmented into Northern and Southern Ergoth after the Cataclysm.", tags: ["west", "empire"] },
    { name: "Abanasinia",                     location_type: "region",    parent: "Ansalon",   notes: "A central region of Ansalon, birthplace of many Heroes of the Lance. Home to Solace and the Que-Shu tribe.", tags: ["heroes of the lance", "central", "war of the lance"] },
    { name: "Silvanesti",                     location_type: "region",    parent: "Ansalon",   notes: "The ancient homeland of the Silvanesti elves in southeastern Ansalon, twisted into a nightmare forest by the Silvanesti Shield.", tags: ["elves", "silvanesti", "east"] },
    { name: "Qualinesti",                     location_type: "region",    parent: "Ansalon",   notes: "The homeland of the Qualinesti elves in southwestern Ansalon, long under threat from the Dragon Highlords.", tags: ["elves", "qualinesti", "southwest"] },
    { name: "Khalkist Mountains",             location_type: "wilderness",parent: "Ansalon",   notes: "A brutal mountain range in eastern Ansalon, home to Neraka and countless draconian forces.", tags: ["mountains", "east", "dragon highlords"] },
    { name: "Blood Sea of Istar",             location_type: "wilderness",parent: "Ansalon",   notes: "A sea stained crimson by the Cataclysm, churning above the sunken ruins of the Kingpriest's empire.", tags: ["sea", "cataclysm", "istar", "minotaurs"] },
    { name: "Icewall Glacier",                location_type: "wilderness",parent: "Ansalon",   notes: "A vast and deadly glacier in the southernmost reaches of Ansalon, home to white dragons.", tags: ["ice", "south", "dragons"] },
    { name: "Palanthas",                      location_type: "city",      parent: "Solamnia",  notes: "The crown jewel of Solamnia — seat of the High Clerist's Tower and Raistlin Majere's tower.", tags: ["solamnia", "capital", "high clerist", "raistlin"] },
    { name: "Neraka",                         location_type: "city",      parent: "Khalkist Mountains", notes: "A dark city in the Khalkist Mountains, seat of the Dragon Highlords during the War of the Lance.", tags: ["evil", "takhisis", "dragon highlords"] },
    { name: "Qualinost",                      location_type: "city",      parent: "Qualinesti",notes: "The capital of the Qualinesti elves — a city of golden spires grown from living trees.", tags: ["elves", "qualinesti", "capital"] },
    { name: "Solace",                         location_type: "town",      parent: "Abanasinia",notes: "A beloved town built in the branches of massive Vallenwood trees — home of Tanis Half-Elven and the Majere twins.", tags: ["vallenwood", "heroes of the lance", "tanis"] },
    { name: "Tarsis",                         location_type: "city",      parent: "Ansalon",   notes: "Once a great port city. After the Cataclysm the sea vanished, leaving Tarsis stranded inland and haunted by draconians.", tags: ["south", "ruined", "cataclysm"] },
    { name: "Thorbardin",                     location_type: "dungeon",   parent: "Ansalon",   notes: "The great underground city-fortress of the dwarves of Ansalon, said to be entirely impregnable.", tags: ["dwarves", "underground", "fortress"] },
    { name: "High Clerist's Tower",           location_type: "building",  parent: "Solamnia",  notes: "A great Solamnic fortress protecting the pass to Palanthas. Site where Sturm Brightblade fell in the War of the Lance.", tags: ["solamnia", "knights", "war of the lance", "sturm"] },
    { name: "Tower of High Sorcery at Wayreth", location_type: "building", parent: "Ansalon", notes: "The only surviving Tower of High Sorcery, hidden by a magical forest. Home to the Conclave of Wizards.", tags: ["magic", "conclave", "test", "wayreth"] },
    { name: "Istar",                          location_type: "dungeon",   parent: "Blood Sea of Istar", notes: "The ruins of a once-great theocratic empire, now resting at the bottom of the Blood Sea after the Cataclysm.", tags: ["cataclysm", "ruins", "sunken", "kingpriest"] },
  ],

  factions: [
    // Knights of Solamnia — three orders
    { name: "Order of the Crown",      description: "The entry order of the Knights of Solamnia, devoted to honour and obedience — Est Sularus oth Mithas ('My Honour is My Life'). Crown knights form the bulk of Solamnia's martial force and serve as the backbone of every major defensive action.", faction_type: "Order", alignment: "Lawful Good", tags: ["knights", "solamnia", "honour", "lawful good"] },
    { name: "Order of the Sword",      description: "The middle order of the Knights of Solamnia, devoted to courage and the gods — particularly Kiri-Jolith, god of just war. Sword knights are the great champions and quest-takers, expected to show divine inspiration through heroic deeds.", faction_type: "Order", alignment: "Lawful Good", tags: ["knights", "solamnia", "courage", "divine", "kiri-jolith"] },
    { name: "Order of the Rose",       description: "The highest and rarest order of Solamnic Knights, devoted to wisdom and justice. Rose knights lead the knighthood and are expected to embody the Oath and the Measure in full — few are ever found worthy.", faction_type: "Order", alignment: "Lawful Good", tags: ["knights", "solamnia", "wisdom", "leadership", "lawful good"] },
    // Dragonarmies — five wings
    { name: "Red Dragonarmy",          description: "The premier Dragonarmy, led by the Dragon Highlord Ariakas himself and later contested. Commands red dragons — the most powerful — and serves as the shock force and political centre of Takhisis's invasion.", faction_type: "Military", alignment: "Lawful Evil", tags: ["evil", "takhisis", "red dragons", "highlord", "war of the lance"] },
    { name: "Blue Dragonarmy",         description: "Led by Dragon Highlord Kitiara uth Matar, the Blue Dragonarmy controls the northeastern front. Blue dragons give it unmatched air superiority; Kitiara's tactical genius makes it the most dangerous Dragonarmy in the field.", faction_type: "Military", alignment: "Lawful Evil", tags: ["evil", "takhisis", "blue dragons", "kitiara", "war of the lance"] },
    { name: "Green Dragonarmy",        description: "The most covert of the five wings, using green dragons and guerrilla tactics in forests and coastal regions. The Green Dragonarmy specialises in infiltration, supply-line disruption, and terror operations.", faction_type: "Military", alignment: "Neutral Evil", tags: ["evil", "takhisis", "green dragons", "guerrilla", "war of the lance"] },
    { name: "Black Dragonarmy",        description: "Assigned the wetlands and southern coasts, the Black Dragonarmy uses its dragons' acid breath and swamp-fighting adaptations to seize territory impassable to other forces.", faction_type: "Military", alignment: "Chaotic Evil", tags: ["evil", "takhisis", "black dragons", "swamps", "war of the lance"] },
    { name: "White Dragonarmy",        description: "The weakest of the five wings, operating in the frozen south and the Icewall Glacier. White dragons are the least intelligent of the chromatics; the White Dragonarmy makes up for this with sheer brutality.", faction_type: "Military", alignment: "Chaotic Evil", tags: ["evil", "takhisis", "white dragons", "icewall", "war of the lance"] },
    // Arcane orders
    { name: "White Robe Wizards",      description: "The magic-users of the Conclave who draw power from Solinari, moon of good magic. White Robes are devoted to good and healing but are forbidden from taking sides in conflicts that compromise the Conclave's neutrality.", faction_type: "Order", alignment: "Neutral Good", tags: ["wizards", "solinari", "good", "conclave", "white robes"] },
    { name: "Red Robe Wizards",        description: "The largest order of the Conclave, drawing power from Lunitari, moon of neutral magic. Red Robes walk the balance between good and evil; they are pragmatic, politically adept, and the glue that keeps the Conclave together.", faction_type: "Order", alignment: "True Neutral", tags: ["wizards", "lunitari", "neutral", "conclave", "red robes"] },
    { name: "Black Robe Wizards",      description: "The magic-users who draw power from Nuitari, moon of dark magic. Black Robes are sworn to their own advancement and serve evil willingly — but they still follow the Conclave's laws, because the laws protect all wizards equally.", faction_type: "Order", alignment: "Neutral Evil", tags: ["wizards", "nuitari", "evil", "conclave", "black robes"] },
    // Alliance forces
    { name: "Whitestone Forces",       description: "The grand alliance assembled at Whitestone Council to resist the Dragon Highlords — Solamnic Knights, Qualinesti and Silvanesti elves, Thorbardin dwarves, hill dwarves, gnomes, and the free peoples of Abanasinia, united by the Dragonlances.", faction_type: "Military", alignment: "Lawful Good", tags: ["good", "alliance", "whitestone", "anti-dragonarmy", "war of the lance"] },
    { name: "Companions of the Lance", description: "The Heroes of the Lance — Tanis Half-Elven, Raistlin, Caramon, Sturm, Flint, Tasslehoff, Goldmoon, and Riverwind — the small group of friends whose journey rediscovered the true gods and turned the tide of the War.", faction_type: "Other", alignment: "Neutral Good", tags: ["heroes of the lance", "companions", "good", "war of the lance"] },
    // Religious and political groups
    { name: "Seekers of the New Gods", description: "A false religious movement that filled the spiritual vacuum after the Cataclysm. Seeker priests have no divine power but enormous political leverage — which collapses spectacularly when true clerics of the old gods return to the world.", faction_type: "Religion", alignment: "True Neutral", tags: ["religion", "false gods", "political", "cataclysm", "abanasinia"] },
    { name: "Silvanesti Court",        description: "The ancient and deeply conservative elven monarchy of Silvanesti, led by Speaker Lorac. Isolationist to the point of self-destruction, the Silvanesti withdrew behind magical wards rather than ally with humans — a decision that cost their homeland dearly.", faction_type: "Government", alignment: "Lawful Neutral", tags: ["elves", "silvanesti", "monarchy", "isolationist", "lorac"] },
    { name: "Qualinesti Council",      description: "The more pragmatic elven government of Qualinesti, led by the Speaker of the Sun. Qualinesti elves are willing to trade and ally with humans and half-elves, which makes them fractionally more likely to survive the Dragonarmy invasion.", faction_type: "Government", alignment: "Neutral Good", tags: ["elves", "qualinesti", "council", "pragmatic", "speaker of the sun"] },
    { name: "Minotaur Empire of Mithas", description: "The proud and martial minotaur nation based on the Blood Sea island of Mithas, governed by an Emperor who rules through combat supremacy. Minotaurs view honour in battle as the highest virtue and participate on both sides of the War as they see fit.", faction_type: "Government", alignment: "Lawful Neutral", tags: ["minotaurs", "empire", "mithas", "blood sea", "martial"] },
    { name: "Kender Communities",      description: "The loose, cheerfully anarchic society of kender across Ansalon — tiny and fearless, incapable of understanding danger, and deeply inconvenient to anyone with something in their pocket. Their homeland of Kenderhome draws them back, but they range everywhere.", faction_type: "Tribe", alignment: "Chaotic Neutral", tags: ["kender", "fearless", "chaos", "kenderhome", "thieves"] },
  ],

  heroes: [
    {
      name: "Tanis Half-Elven",
      race: "Half-Elf",
      alignment: "Neutral Good",
      occupation: "Fighter / Leader",
      personality: "Reluctant leader, torn between his elven and human natures. Tanis is compassionate and perceptive, but plagued by self-doubt. He is most effective when protecting those he loves, and most vulnerable when asked to choose between them.",
      backstory: "Born of an elven mother and a human father who was killed before his birth, Tanis Half-Elven grew up on the margins of Qualinesti elven society. He formed the Companions of the Lance with his childhood friends and now finds himself at the centre of the war against the Dragon Highlords.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["heroes of the lance", "companions", "half-elf", "war of the lance"],
    },
    {
      name: "Raistlin Majere",
      race: "Human",
      alignment: "Neutral Evil",
      occupation: "Wizard (Black Robes)",
      personality: "Brilliant, cold, and consumed by ambition. Raistlin has golden skin and hourglass eyes — the price of his Test at the Tower of Wayreth. He views nearly everyone as a fool or a tool, but occasionally shows a complicated tenderness toward his twin brother Caramon.",
      backstory: "The most powerful mage of his age, Raistlin survived the Test at the Tower of High Sorcery by agreeing to serve the gods of magic — at a terrible price. He chose the Black Robes and walks a razor's edge between serving the Companions and serving his own ends.",
      status: "alive",
      relationship: "indifferent",
      portrait_url: null,
      tags: ["heroes of the lance", "black robes", "tower of wayreth", "ambitious"],
    },
    {
      name: "Caramon Majere",
      race: "Human",
      alignment: "Neutral Good",
      occupation: "Warrior / Fighter",
      personality: "Big-hearted, uncomplicated, and endlessly patient with his brilliant and cruel twin brother. Caramon is the brawn to Raistlin's brain and knows it — but he has more wisdom than he's given credit for, and his loyalty is absolute.",
      backstory: "Raistlin's twin brother and lifelong protector. Caramon has spent his whole life carrying Raistlin's physical weakness while Raistlin devoured the world's attention. He is a formidable fighter who has had to survive adventures while watching his brother edge toward genuine darkness.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["heroes of the lance", "companions", "warrior", "caramon"],
    },
    {
      name: "Sturm Brightblade",
      race: "Human",
      alignment: "Lawful Good",
      occupation: "Knight of Solamnia",
      personality: "Honourable to a fault, courtly, and possessed of a dignity that shames those around him. Sturm follows the Measure even when it costs him everything. He carries his father's armour and a debt of honour he can never repay.",
      backstory: "A Knight of Solamnia in all but title — he has yet to be formally knighted due to his irregular birth and the Order's disarray. Sturm fights with an ancient two-handed sword and the full weight of the Solamnic code. He will not survive the War of the Lance.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["heroes of the lance", "knights of solamnia", "honour", "sacrifice"],
    },
    {
      name: "Flint Fireforge",
      race: "Dwarf",
      alignment: "Lawful Good",
      occupation: "Blacksmith / Warrior",
      personality: "Cantankerous, warm-hearted, and constitutionally unable to tolerate nonsense — especially from Tasslehoff Burrfoot. Flint grumbles about everything and would die for any of his companions. He often does.",
      backstory: "A dwarven craftsman from Hillhome who adventured with the Companions for decades before the War of the Lance. He is one of the oldest of the group and the most reluctant to admit it. His friendship with Tanis is the deepest relationship either of them has.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["heroes of the lance", "companions", "dwarf", "craftsman"],
    },
    {
      name: "Tasslehoff Burrfoot",
      race: "Kender",
      alignment: "Chaotic Good",
      occupation: "Thief / Adventurer",
      personality: "Irrepressibly curious, absolutely fearless, and constitutionally incapable of understanding why borrowing things without asking is a social problem. Tasslehoff is not malicious — he is a force of nature that happens to interact with pockets.",
      backstory: "The most famous kender in Ansalon and a member of the original Companions. He has wandered everywhere, borrowed from everyone, and been present at more historic moments than anyone has a right to be. He carries a magical device that has allowed him to travel through time, which has caused a variety of problems.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["heroes of the lance", "companions", "kender", "fearless"],
    },
    {
      name: "Goldmoon",
      race: "Human",
      alignment: "Neutral Good",
      occupation: "Cleric of Mishakal / Chieftain's Daughter",
      personality: "Deeply principled and quietly fierce. Goldmoon was a princess who gave up everything — title, people, safety — to follow a blue crystal staff she didn't understand. She embodies genuine faith in a world that had forgotten the gods existed.",
      backstory: "Daughter of the Que-Shu tribal chieftain, Goldmoon carried the blue crystal staff of Mishakal that proved the true gods had returned to Krynn. Her arrival among the Companions marked the beginning of the end for the Dragon Highlords. She became the first cleric of the returned gods.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["heroes of the lance", "companions", "cleric", "mishakal", "que-shu"],
    },
    {
      name: "Riverwind",
      race: "Human",
      alignment: "Lawful Good",
      occupation: "Warrior / Que-Shu Plainsman",
      personality: "Stoic, proud, and deeply suspicious of magic after his quest for the blue crystal staff left him traumatized. Riverwind's love for Goldmoon is the steadying force of his life. He is a warrior of real quality who struggles with a world that is stranger than he was raised for.",
      backstory: "A Que-Shu warrior of low birth who loved the chieftain's daughter. His quest to prove himself worthy took him to Xak Tsaroth, where he found the blue crystal staff and was driven nearly mad. He survived to become one of the Companions and Goldmoon's partner in every sense.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["heroes of the lance", "companions", "warrior", "que-shu", "plainsman"],
    },
    {
      name: "Kitiara uth Matar",
      race: "Human",
      alignment: "Lawful Evil",
      occupation: "Dragon Highlord (Blue Wing) / General",
      personality: "Brilliant, magnetic, and utterly ruthless — Kitiara is everything a Dragon Highlord should be and more. She is also Tanis Half-Elven's former lover, which makes her one of the most dangerous people in the world.",
      backstory: "The half-sister of Raistlin and Caramon Majere, Kitiara chose power over family. She rose through the Dragon Highlord ranks by defeating rivals and has been granted dominion over the Blue Dragonarmies. She rides the blue dragon Skie.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["dragon highlord", "blue dragonarmy", "villain", "skie"],
    },
    {
      name: "Takhisis",
      race: "Deity",
      alignment: "Lawful Evil",
      occupation: "Dark Queen / Goddess of Evil",
      personality: "Magnificent and terrible — Takhisis commands through majesty and the promise of destruction for those who fail. She is not merely evil; she is the principle of dominion. She speaks to her servants in visions and demands nothing less than everything.",
      backstory: "The Dark Queen of Krynn, who brought her war to the world through the Dragon Highlords and their armies. She seeks to complete a dominance over Krynn that has been denied her since the Age of Dreams. The War of the Lance is her most direct attempt to reclaim the world she considers hers.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["dark queen", "deity", "dragonarmies", "villain", "takhisis"],
    },
    {
      name: "Dragon Highlord Ariakas",
      race: "Human",
      alignment: "Lawful Evil",
      occupation: "Supreme Dragon Highlord",
      personality: "Brutal, strategically gifted, and personally terrifying. Ariakas commands through fear and demonstrated consequence. He has no patience for the complicated internal politics of the Dragonlords — he prefers to solve disputes by removing one of the disputants.",
      backstory: "The supreme commander of all five Dragonarmies, answerable only to Takhisis herself. Ariakas is a fearsome warrior who killed his own father to prove his worth to the Dark Queen. He wears the Crown of Power and commands the Red Dragonarmy, the most powerful of the five wings.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["dragon highlord", "red dragonarmy", "villain", "supreme commander"],
    },
    {
      name: "Laurana Kanan",
      race: "Elf",
      alignment: "Neutral Good",
      occupation: "General / The Golden General",
      personality: "Initially sheltered and naive, Laurana has been hardened by war into something extraordinary. She is brave without being reckless, brilliant without being cold, and she carries the grief of people who have died following her orders.",
      backstory: "Princess of the Qualinesti elves, childhood friend and eventual partner to Tanis Half-Elven. She began the war as a young noblewoman who followed the Companions out of heartbreak and grew into the Golden General — the greatest military commander of the Whitestone Forces.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["qualinesti", "golden general", "whitestone forces", "elf", "general"],
    },
    {
      name: "Fizban the Fabulous",
      race: "Human (disguised)",
      alignment: "Neutral Good",
      occupation: "Wandering Wizard / Ancient",
      personality: "Absent-minded, cheerful, and prone to spectacular magical mishaps — or so he seems. Fizban has a way of appearing exactly when he is needed and vanishing before anyone can ask too many questions. He is very fond of hats.",
      backstory: "A bumbling old wizard who traveled with the Companions for a time, Fizban is secretly far more than he appears. Those who meet him rarely forget him — even if they can't quite explain why.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["wizard", "mysterious", "divine", "companion"],
    },
    {
      name: "Lord Soth",
      race: "Undead (Death Knight)",
      alignment: "Lawful Evil",
      occupation: "Death Knight / Knight of the Rose",
      personality: "Magnificent in his ruin. Soth was once the noblest of the Rose Knights, and the tragedy of what he chose has calcified into cold contempt for everything he failed to be. He serves Kitiara not out of loyalty but because it suits him — and because she found a use for a horror like him.",
      backstory: "Once the greatest Knight of the Rose in Solamnia's history, Lord Soth was cursed to undeath after he failed to stop the Cataclysm — a task the gods gave him that he abandoned for petty personal reasons. He is now a death knight of terrible power who commands the undead and serves Kitiara uth Matar.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["death knight", "villain", "undead", "kitiara", "solamnia"],
    },
    {
      name: "Berem Everman",
      race: "Human",
      alignment: "Neutral Good",
      occupation: "The Everman / Key to Takhisis",
      personality: "Haunted, wandering, and consumed by guilt over his sister's death. Berem is not quite sane and not quite present. He has been running for decades and does not know how to stop.",
      backstory: "An ordinary man who pulled a green gemstone from a ruined altar, accidentally killing his sister. The gem fused with his chest and made him immortal — and unknowingly became the key Takhisis needs to fully enter the world of Krynn. The Dragon Highlords have been hunting him for years.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["everman", "immortal", "key", "takhisis", "tragic"],
    },
  ],
  pantheons: DRAGONLANCE_PANTHEONS,
  deities: DRAGONLANCE_DEITIES,
};
