import type { DndSettingDef } from "./types";

export const eberronSetting: DndSettingDef = {
  id: "eberron",
  label: "Eberron",

  defaultAiPrompt:
    "Magitech noir fantasy with a post-war, rain-slicked mood. Favour amber gaslight, dark polished wood, tarnished brass, wet cobblestone, and industrial grey stone. " +
    "Magic is infrastructure — House seals on crates, lightning rail sparks, the blue-white glow of eberite lanterns, Cannith maker's marks stamped on everything. " +
    "Warforged should look functional and scarred: plated with different metals from field repairs, carvings or sigils added by their own hands, not decorative but personal. " +
    "Characters wear urban practical — long coats, dragonmark tattoos visible at collar or wrist, House insignia, military surplus from the Last War. Show war wounds and exhaustion. " +
    "Architecture mixes grand Galifar-era facades with makeshift post-war additions — scaffolding, boarding, mismatched stone. Sharn layers keep and skytower above fog-choked lower wards. " +
    "The Mournland should feel wrong: grey-white mist, warped terrain, silence, the absence of decay where everything should be rotting. " +
    "Keep the mood tense, morally grey, and urban — glamour exists but it's always covering something.",

  calendar: {
    name: "Eberron (Galifar Calendar)",
    epochName: "YK",
    defaultYear: 998,
    weekStyle: "weekly",
    dayLabels: ["Sul", "Mol", "Zol", "Wir", "Zor", "Far", "Sar"],
    months: [
      { name: "Zarantyr",  alias: "Storm Month",    days: 28 },
      { name: "Olarune",   alias: "Sentinel Month", days: 28 },
      { name: "Therendor", alias: "Healer's Month", days: 28 },
      { name: "Eyre",      alias: "Anvil Month",    days: 28 },
      { name: "Dravago",   alias: "Herder's Month", days: 28 },
      { name: "Nymm",      alias: "Crowns Month",   days: 28 },
      { name: "Lharvion",  alias: "Eye Month",      days: 28 },
      { name: "Barrakas",  alias: "Lantern Month",  days: 28 },
      { name: "Rhaan",     alias: "Book Month",     days: 28 },
      { name: "Sypheros",  alias: "Shadow Month",   days: 28 },
      { name: "Aryth",     alias: "Gateway Month",  days: 28 },
      { name: "Vult",      alias: "Warding Month",  days: 28 },
    ],
    intercalaryDays: [],
    leapYearRule: "none",
  },

  locations: [
    { name: "Eberron",     location_type: "world",     notes: "The world itself, formed from the body of the great dragon Eberron, where magic is woven into its very physics.", tags: ["planet", "world"] },
    { name: "Khorvaire",   location_type: "continent", parent: "Eberron",    notes: "The primary continent of Eberron, home to the Five Nations, the Mournland, and dozens of diverse peoples.", tags: ["eberron"] },
    { name: "Xen'drik",    location_type: "continent", parent: "Eberron",    notes: "A mysterious southern continent of ancient giant ruins and impenetrable jungles.", tags: ["giants", "ruins", "mysterious", "south"] },
    { name: "Sarlona",     location_type: "continent", parent: "Eberron",    notes: "A distant eastern continent dominated by the Inspired, humanoid thralls of the nightmare Quori spirits.", tags: ["inspired", "quori", "distant", "east"] },
    { name: "Argonnessen", location_type: "continent", parent: "Eberron",    notes: "The dragon continent to the southeast. Home to the Chamber, the Conclave, and thousands of true dragons.", tags: ["dragons", "chamber", "conclave"] },
    { name: "Khyber",      location_type: "region",    parent: "Eberron",    notes: "The underworld of Eberron, said to be the body of the Dragon Below. A vast subterranean realm of aberrations and bound fiends.", tags: ["underground", "aberrations", "fiends", "dragon below"] },
    { name: "Breland",     location_type: "country",   parent: "Khorvaire",  notes: "The largest of the Five Nations, known for industry, relative democracy, and the teeming city of Sharn.", tags: ["five nations"] },
    { name: "Aundair",     location_type: "country",   parent: "Khorvaire",  notes: "A nation renowned for its arcane traditions, fertile fields, and the floating Arcanix towers.", tags: ["five nations", "magic", "arcanix"] },
    { name: "Karrnath",    location_type: "country",   parent: "Khorvaire",  notes: "A harsh, militaristic nation with a grim history of deploying undead soldiers in the Last War.", tags: ["five nations", "undead", "military"] },
    { name: "Thrane",      location_type: "country",   parent: "Khorvaire",  notes: "A theocracy governed by the Church of the Silver Flame, known for its paladins and inquisitors.", tags: ["five nations", "silver flame", "theocracy"] },
    { name: "Darguun",     location_type: "country",   parent: "Khorvaire",  notes: "A nation carved out by goblinoid peoples who seized former Cyre territory during the Last War.", tags: ["goblinoids", "hobgoblins", "last war"] },
    { name: "Droaam",      location_type: "country",   parent: "Khorvaire",  notes: "A nation of monsters — medusas, gnolls, harpies, and worse — ruled by the three Daughters of Sora Kell.", tags: ["monsters", "daughters of sora kell"] },
    { name: "Sharn",       location_type: "city",      parent: "Breland",    notes: "The City of Towers — a massive vertical metropolis built on a manifest zone to Syrania that allows magic to lift buildings miles into the sky.", tags: ["city of towers", "towers", "syrania"] },
    { name: "Wroat",       location_type: "city",      parent: "Breland",    notes: "The capital of Breland, seat of King Boranel ir'Wynarn and the Breland Parliament.", tags: ["breland", "capital", "parliament"] },
    { name: "Fairhaven",   location_type: "city",      parent: "Aundair",    notes: "The capital of Aundair — a city of wizards built around the floating Arcanix towers. Known for fine wine and arcane academies.", tags: ["aundair", "capital", "wizards", "arcanix"] },
    { name: "Korth",       location_type: "city",      parent: "Karrnath",   notes: "The capital of Karrnath — a grim fortress-city on the Karrn River, home to the Order of the Emerald Claw.", tags: ["karrnath", "capital", "undead", "emerald claw"] },
    { name: "Flamekeep",   location_type: "city",      parent: "Thrane",     notes: "The capital of Thrane and seat of the Church of the Silver Flame, built around the pillar of divine fire.", tags: ["thrane", "capital", "silver flame"] },
    { name: "The Mournland", location_type: "wilderness", parent: "Khorvaire", notes: "The shattered wasteland where Cyre once stood. Destroyed in the Day of Mourning in 994 YK. Surrounded by a wall of dead grey mist.", tags: ["cyre", "day of mourning", "ruins", "dead-grey mist"] },
  ],

  factions: [
    // Dragonmarked Houses
    { name: "House Cannith",          description: "The dragonmarked house of Making — artificers, engineers, and creators of the warforged. Fractured into three rival heirs (North, South, and the exiled) after the Last War, each competing to control the future of arcane manufacturing.", faction_type: "Guild", alignment: "Lawful Neutral", tags: ["dragonmark", "artificers", "warforged", "making"] },
    { name: "House Deneith",          description: "The dragonmarked house of Sentinel — mercenary soldiers, bodyguards, and military contractors headquartered in Karrnath. Their Blademark guild deploys trained soldiers to any buyer; the Defender's Guild supplies elite personal guards.", faction_type: "Guild", alignment: "Lawful Neutral", tags: ["dragonmark", "mercenary", "sentinel", "soldiers"] },
    { name: "House Ghallanda",        description: "The dragonmarked house of Hospitality — halfling innkeepers, brewers, and food suppliers whose Hospitality guild operates the Hosteler's Guild network of inns across Khorvaire. They sell safety in a dangerous world.", faction_type: "Guild", alignment: "Lawful Neutral", tags: ["dragonmark", "halflings", "hospitality", "innkeepers"] },
    { name: "House Jorasco",          description: "The dragonmarked house of Healing — halfling healers and alchemists who provide magical medical services for a price. They are expensive, non-judgmental, and will treat anyone who can pay.", faction_type: "Guild", alignment: "Lawful Neutral", tags: ["dragonmark", "halflings", "healing", "alchemy"] },
    { name: "House Kundarak",         description: "The dragonmarked house of Warding — dwarven bankers and vault-keepers whose Mark of Warding underpins the entire financial system of Khorvaire. Their banks are considered absolutely unbreakable.", faction_type: "Merchant", alignment: "Lawful Neutral", tags: ["dragonmark", "dwarves", "banking", "warding"] },
    { name: "House Lyrandar",         description: "The dragonmarked house of Storm — half-elf captains of the elemental galleons and airships that connect the Five Nations. They control most air and sea trade routes and are growing increasingly powerful.", faction_type: "Merchant", alignment: "Lawful Neutral", tags: ["dragonmark", "half-elves", "airships", "ships", "storm"] },
    { name: "House Medani",           description: "The dragonmarked house of Detection — half-elves who sell warning, surveillance, and investigation services. Their Warning Guild supplies some of the finest inquisitives in Khorvaire.", faction_type: "Guild", alignment: "Lawful Neutral", tags: ["dragonmark", "half-elves", "detection", "inquisitives"] },
    { name: "House Orien",            description: "The dragonmarked house of Passage — humans who operate the lightning rail, overland caravans, and teleportation services. The lightning rail is their crown jewel: fast, expensive, and essential.", faction_type: "Merchant", alignment: "Lawful Neutral", tags: ["dragonmark", "humans", "lightning rail", "transport"] },
    { name: "House Phiarlan",         description: "The dragonmarked house of Shadow (entertainment half) — elves who operate a vast guild of entertainers, bards, and artists. They also run one of the most sophisticated intelligence networks in Khorvaire, discreetly.", faction_type: "Guild", alignment: "Lawful Neutral", tags: ["dragonmark", "elves", "entertainment", "espionage", "shadow"] },
    { name: "House Sivis",            description: "The dragonmarked house of Scribing — gnome notaries, translators, and message brokers. The Speakers Guild operates Sivis message stations that allow near-instantaneous written communication across continents.", faction_type: "Guild", alignment: "Lawful Neutral", tags: ["dragonmark", "gnomes", "scribing", "communication"] },
    { name: "House Tharashk",         description: "The dragonmarked house of Finding — a half-orc and human house based in the Shadow Marches. They find things: ore, people, and information. Their Finders Guild dominates Eberron dragonshards mining.", faction_type: "Merchant", alignment: "Lawful Neutral", tags: ["dragonmark", "half-orcs", "finding", "mining", "shadow marches"] },
    { name: "House Thuranni",         description: "The dragonmarked house of Shadow (assassination half) — a splinter house of elves that separated from Phiarlan after the Shadow Schism. They are assassins and entertainers both, and the line blurs deliberately.", faction_type: "Criminal", alignment: "Lawful Evil", tags: ["dragonmark", "elves", "assassination", "shadow", "shadow schism"] },
    { name: "House Vadalis",          description: "The dragonmarked house of Handling — humans who breed and sell magebred animals. From war horses to message-carrying birds to exotic mounts, if it is an animal worth owning, Vadalis probably bred it.", faction_type: "Merchant", alignment: "Lawful Neutral", tags: ["dragonmark", "humans", "animals", "magebred", "breeders"] },
    // Political and intelligence organizations
    { name: "The Twelve",             description: "A joint arcane institute funded by all thirteen Dragonmarked Houses to research and standardize the use of dragonmarks. Officially neutral; in practice it is a political arena where Houses negotiate influence over magical standards.", faction_type: "Guild", alignment: "True Neutral", tags: ["dragonmarks", "arcane", "research", "politics", "neutral"] },
    { name: "The Citadel",            description: "Breland's combined military intelligence and law-enforcement agency — King Boranel's most effective tool. The Citadel conducts surveillance, counter-espionage, and captures criminals too dangerous for local watch.", faction_type: "Military", alignment: "Lawful Neutral", tags: ["breland", "intelligence", "law enforcement", "military"] },
    { name: "The Dark Lanterns",      description: "The covert operations branch of the Citadel — Breland's true spy service. Dark Lanterns operate deep cover identities, run foreign agents, and deal in the shadowy operations the Citadel cannot officially acknowledge.", faction_type: "Secret Society", alignment: "Lawful Neutral", tags: ["breland", "spies", "covert", "intelligence"] },
    { name: "Royal Eyes of Aundair",  description: "Aundair's arcane intelligence service, combining conventional espionage with divination magic. They monitor enemy nations and gather political intelligence for Queen Aurala, who has never given up on reunifying Galifar under Aundairian rule.", faction_type: "Secret Society", alignment: "Lawful Neutral", tags: ["aundair", "intelligence", "divination", "spies", "aurala"] },
    { name: "Boranel's Court",        description: "The royal court of Breland, centred on the beloved and aging King Boranel ir'Wynarn. An unusually democratic monarchy with a functioning parliament, it is the most progressive of the Five Nations — and its future after Boranel is deeply uncertain.", faction_type: "Government", alignment: "Neutral Good", tags: ["breland", "royalty", "parliament", "politics", "king boranel"] },
    // Secret and conspiracy groups
    { name: "The Aurum",              description: "A secret society of Khorvaire's wealthiest individuals — merchants, nobles, and dragonmarked heirs — who believe wealth entitles them to steer the world. Organized into four lodges by wealth tier, the Aurum pursues power through financial manipulation and political placement.", faction_type: "Secret Society", alignment: "Lawful Evil", tags: ["conspiracy", "wealth", "secret", "nobles", "merchants"] },
    { name: "The Chamber",            description: "An ancient organization of dragons who have embedded agents across Khorvaire to monitor and manipulate world events in accordance with the Draconic Prophecy. They are not a government or an army — they are a long game, measured in centuries.", faction_type: "Secret Society", alignment: "True Neutral", tags: ["dragons", "prophecy", "argonnessen", "secret", "ancient"] },
    { name: "The Lords of Dust",      description: "A vast conspiracy of Rakshasas and other fiends working to free the ancient demon lords (Overlords) bound beneath Khyber. Patient beyond mortal comprehension, they have agents in every court and cult across Eberron.", faction_type: "Secret Society", alignment: "Neutral Evil", tags: ["rakshasas", "fiends", "khyber", "demon lords", "conspiracy"] },
    { name: "The Dreaming Dark",      description: "The ruling council of the Inspired — the quori spirits that dominate the continent of Sarlona through their human hosts. Their long-term plan involves bringing the nightmare quori age to Khorvaire by corrupting the dream-landscape.", faction_type: "Government", alignment: "Lawful Evil", tags: ["quori", "sarlona", "inspired", "nightmare", "psionic"] },
    // Religious and extremist
    { name: "Church of the Silver Flame", description: "The dominant religion of Thrane, devoted to a divine force that trapped demons long ago. Governed by the child Keeper Jaela Daran and a council of cardinals who wield as much political power as spiritual authority. Includes devout paladins and fanatical inquisitors.", faction_type: "Religion", alignment: "Lawful Good", tags: ["religion", "thrane", "paladins", "inquisitors", "silver flame"] },
    { name: "Order of the Emerald Claw", description: "A Karrnathi nationalist extremist group wielding forbidden necromancy in service of an unknown master. Officially outlawed by Karrnath, they recruit fanatics, deploy undead shock troops, and pursue ancient artefacts for goals that go beyond simple nationalism.", faction_type: "Military", alignment: "Lawful Evil", tags: ["karrnath", "undead", "nationalist", "extremist", "necromancy"] },
    { name: "Cults of the Dragon Below", description: "A constellation of unrelated cults united only by their worship of the imprisoned demon lords of Khyber. Each cult is different in theology and practice, but all serve the Lords of Dust's agenda — unknowingly or otherwise.", faction_type: "Cult", alignment: "Chaotic Evil", tags: ["cults", "khyber", "demon lords", "dragon below", "aberrations"] },
    // Other major factions
    { name: "Daughters of Sora Kell", description: "Three hag sisters — a hag, a green hag, and a night hag — who rule the monster nation of Droaam. They formed the first monster government west of Breland and are building something that may outlast them both.", faction_type: "Government", alignment: "Neutral Evil", tags: ["droaam", "hags", "monsters", "rulers", "sorceresses"] },
    { name: "The Valenar Elves",      description: "A mercenary nation of elves who seized Karrnath's southern territories during the Last War and refused to leave, declaring themselves the new homeland of the Tairnadal. They revere and ritually re-enact the deeds of ancient elf heroes through combat.", faction_type: "Military", alignment: "Chaotic Neutral", tags: ["elves", "valenar", "mercenary", "tairnadal", "cavalry"] },
    { name: "The Boromar Clan",       description: "The most powerful criminal organization in Sharn — a halfling crime family with roots in House Ghallanda that controls much of the city's smuggling, gambling dens, and protection rackets across all six ward levels.", faction_type: "Criminal", alignment: "Neutral Evil", tags: ["criminal", "halflings", "sharn", "smuggling", "organized crime"] },
  ],

  heroes: [
    {
      name: "Jaela Daran",
      race: "Human",
      alignment: "Lawful Good",
      occupation: "Keeper of the Flame",
      personality: "Serene and wise far beyond her apparent age — Jaela was chosen as the spiritual leader of the Church of the Silver Flame at age six and has served as Keeper ever since. She is compassionate but resolute when the Flame demands difficult decisions.",
      backstory: "The spiritual leader of the Church of the Silver Flame and de facto ruler of Thrane. Though she appears as a young girl, she is centuries older in accumulated spiritual experience. The Silver Flame speaks through her directly.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["thrane", "silver flame", "keeper", "theocracy"],
    },
    {
      name: "King Boranel ir'Wynarn",
      race: "Human",
      alignment: "Neutral Good",
      occupation: "King of Breland",
      personality: "Warm, beloved, and aware that his death will be a catastrophe. Boranel is an old man who has ruled with unusual wisdom and genuine care for his people. He knows his heirs are not ready. He worries about this constantly while never letting it show.",
      backstory: "The aging king of Breland — the largest and most prosperous of the Five Nations. Boranel has kept Breland together through the Last War and the peace after it. His health is failing, his succession is uncertain, and every political faction in Khorvaire is making contingency plans.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["breland", "king", "wroat", "court", "royalty"],
    },
    {
      name: "Merrix d'Cannith",
      race: "Human",
      alignment: "Lawful Neutral",
      occupation: "House Cannith Patriarch (South) / Artificer",
      personality: "Cold, brilliant, and utterly pragmatic. Merrix views the world as a problem to be engineered. He created the modern warforged and has plans few others can anticipate. Not evil — but not warm either.",
      backstory: "Head of House Cannith South and grandson of the man who first built the warforged. He secretly continued warforged production after the Treaty of Thronehold banned it, and his interests in the Day of Mourning go deeper than anyone knows.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["house cannith", "artificer", "warforged", "dragonmark"],
    },
    {
      name: "Lady Elaydren d'Vown",
      race: "Half-Elf",
      alignment: "Neutral Good",
      occupation: "House Cannith Agent",
      personality: "Charming and genuinely warm, but carrying deep secrets about House Cannith's hidden agenda. She cares about doing the right thing even when her House obligations make that complicated.",
      backstory: "A Cannith agent tasked with recovering schema fragments tied to the Creation Pattern — an ancient Cannith design of unknown but terrifying power. She recruits adventurers when her House's own agents cannot be trusted.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["house cannith", "eberron", "creation pattern", "schema"],
    },
    {
      name: "The Lord of Blades",
      race: "Warforged",
      alignment: "Lawful Evil",
      occupation: "Warlord / Warforged Separatist",
      personality: "Charismatic, hateful of 'fleshlings', and utterly convinced that warforged are the next stage of civilization. He speaks with cold precision and has never lost a debate with an enemy he later allowed to live.",
      backstory: "An enigmatic warforged warlord who leads a nation of warforged in the Mournland. He rejects the Treaty of Thronehold and seeks to build a warforged homeland — by conquest if necessary. His true name and origins are unknown.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["warforged", "mournland", "separatist", "villain"],
    },
    {
      name: "Sora Kell",
      race: "Hag (Green Hag)",
      alignment: "Neutral Evil",
      occupation: "Ruler of Droaam / Daughter of Sora Kell",
      personality: "Darkly maternal, politically shrewd, and patient in the way that creatures who have lived centuries learn to be. Sora Kell is the most capable politician of the three sisters — she talks where Sora Maenya breaks and Sora Teraza sees.",
      backstory: "One of the three hag sisters who created the monster nation of Droaam. The Daughters of Sora Kell united the monster clans that no one else could control and established a functioning government west of Breland. Whether this represents progress or a subtler threat is a question the Five Nations have not yet answered.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["droaam", "hag", "daughters of sora kell", "monster nation", "ruler"],
    },
    {
      name: "Sora Maenya",
      race: "Hag (Annis Hag)",
      alignment: "Chaotic Evil",
      occupation: "Warlord of Droaam / Daughter of Sora Kell",
      personality: "Enormous, brutal, and genuinely delighted by physical violence. Sora Maenya is Droaam's enforcer — the sister you send when you want something destroyed. She is not stupid but she would rather act than negotiate.",
      backstory: "The muscle of the three Daughters. She commands Droaam's military forces with a warlord's instinct and a hag's cruelty. Her opponents tend not to survive to discuss her strategic limitations.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["droaam", "hag", "daughters of sora kell", "warlord", "brute"],
    },
    {
      name: "Sora Teraza",
      race: "Hag (Dusk Hag)",
      alignment: "True Neutral",
      occupation: "Oracle of Droaam / Daughter of Sora Kell",
      personality: "Ancient and alien even by hag standards. Sora Teraza sees fragments of the future and speaks in riddles that only become clear in retrospect. She is not unkind — she simply operates on a timeline that makes her hard to read.",
      backstory: "The eldest and most mysterious of the three Daughters. She sees the future with unsettling clarity and guided her sisters to build Droaam in accordance with what she has seen. She is the most dangerous of the three — not because of power but because she already knows what you are going to do.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["droaam", "hag", "daughters of sora kell", "oracle", "seer"],
    },
    {
      name: "Daine",
      race: "Human",
      alignment: "Chaotic Good",
      occupation: "Veteran Soldier / Mercenary",
      personality: "Gruff, haunted by the Last War, and deeply protective of those he calls his own. Daine distrusts authority but will go to any length for his comrades. He drinks too much and sleeps too little.",
      backstory: "A veteran of the Last War who survived the Day of Mourning by being away from Cyre on a mission. The loss of his nation, his family, and most of his regiment has left him without roots — he wanders, takes mercenary work, and tries not to think about what he lost.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["cyre", "veteran", "last war", "mercenary"],
    },
    {
      name: "Viorr Maelak",
      race: "Human",
      alignment: "Lawful Neutral",
      occupation: "Captain of the Dark Lanterns",
      personality: "Quiet, methodical, and deeply uncomfortable in conversation with anyone who doesn't share his clearance level. Maelak is Breland's spymaster in all but name and he treats information the way other men treat gold — you spend it carefully and you never give it away.",
      backstory: "The current head of the Dark Lanterns, Breland's covert intelligence service. He has kept Breland ahead of its rivals through a combination of careful tradecraft and the willingness to make decisions that cannot be discussed afterward.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["breland", "dark lanterns", "spymaster", "intelligence", "citadel"],
    },
    {
      name: "Mordain the Fleshweaver",
      race: "Human (Transmuted)",
      alignment: "Neutral Evil",
      occupation: "Renegade Wizard / Flesh Sculptor",
      personality: "Utterly detached from normal human feeling, Mordain regards living bodies as raw material for artistic expression. He is not cruel in the way that people who enjoy pain are cruel — he is worse. He is indifferent.",
      backstory: "A Jorasco-born wizard who was excoriated from House Phiarlan for experiments that horrified even his peers. He retreated to a tower in the Shadow Marches where he has been sculpting living creatures into new forms for decades. Dragonmarked Houses occasionally hire him when no one else will take the contract.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["shadow marches", "flesh sculptor", "renegade", "transmutation", "horror"],
    },
    {
      name: "Demise",
      race: "Elf (Lich)",
      alignment: "Lawful Evil",
      occupation: "Order of the Emerald Claw Lich / Undead Agent",
      personality: "Coldly fanatical. Demise serves the Order of the Emerald Claw and its masters with a lich's perfect patience and an ideologue's conviction. She does not bargain. She delivers ultimatums and consequences.",
      backstory: "A former Blood of Vol priest who achieved lichdom in pursuit of the Divinity Within — the Vol doctrine that mortals can transcend death through their own power. She now serves as one of the Emerald Claw's most powerful agents, pursuing ancient artefacts and eliminating threats to the Order's agenda.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["emerald claw", "lich", "blood of vol", "undead", "karrnath"],
    },
    {
      name: "Tirashana",
      race: "Human (Inspired)",
      alignment: "Lawful Evil",
      occupation: "Dreaming Dark Agent / Inspired",
      personality: "Elegant, composed, and absolutely not the person she appears to be. Tirashana's human host was chosen for her social access and her willingness. The quori spirit within is the true occupant — calculating, psionic, and pursuing an agenda that operates on a continental scale.",
      backstory: "An agent of the Dreaming Dark operating deep cover in Khorvaire. The quori spirit possessing her has been infiltrating the dream-landscape of the Five Nations for years, seeding nightmares, corrupting dreams, and building toward the conditions that will allow the quori's nightmare age to spread westward from Sarlona.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["dreaming dark", "inspired", "quori", "psionic", "sarlona"],
    },
  ],
};
