import type { DndSettingDef } from "./types";

export const faerunSetting: DndSettingDef = {
  id: "faerun",
  label: "Forgotten Realms",

  defaultAiPrompt:
    "High fantasy setting with a broad, lived-in palette — warm torchlit stone, deep forest greens, coastal greys, merchant blues, and the gold of old kingdoms. " +
    "Magic is common: arcane sigils on doors, glowing potions on shelves, the faint shimmer of enchantments on weapons. Let it be present but unremarkable to the locals. " +
    "Architecture ranges from rough frontier timber to grand city stonework — show weathering, repairs, guild crests, and the layering of centuries. " +
    "Characters dress practically with cultural flair — Sword Coast merchants in padded doublets, northern rangers in furs and travel-stained cloaks, Waterdhavian nobles in jewelled excess. " +
    "Dungeons should feel ancient and dangerous: crumbling ceilings, torchlight swallowed by darkness, moss on carved stone, the drip of water. " +
    "Creatures should feel like they belong to their environment — a troll reeks of the swamp, a drow moves like shadow, a dragon commands the whole composition. " +
    "Keep the mood bold, adventurous, and world-consistent — heroic without being clean, dangerous without being bleak.",

  calendar: {
    name: "Faerûn (Calendar of Harptos)",
    epochName: "DR",
    defaultYear: 1495,
    weekStyle: "tenday",
    weekRowNames: ["Tenday 1", "Tenday 2", "Tenday 3"],
    months: [
      { name: "Hammer",    alias: "Deepwinter",             days: 30 },
      { name: "Alturiak",  alias: "The Claw of Winter",     days: 30 },
      { name: "Ches",      alias: "The Claw of the Sunsets",days: 30 },
      { name: "Tarsakh",   alias: "The Claw of the Storms", days: 30 },
      { name: "Mirtul",    alias: "The Melting",            days: 30 },
      { name: "Kythorn",   alias: "The Time of Flowers",    days: 30 },
      { name: "Flamerule", alias: "Summertide",             days: 30 },
      { name: "Eleasias",  alias: "Highsun",                days: 30 },
      { name: "Eleint",    alias: "The Fading",             days: 30 },
      { name: "Marpenoth", alias: "Leaffall",               days: 30 },
      { name: "Uktar",     alias: "The Rotting",            days: 30 },
      { name: "Nightal",   alias: "The Drawing Down",       days: 30 },
    ],
    intercalaryDays: [
      { name: "Midwinter",        afterMonth: 1,  description: "A mid-winter festival of introspection and planning for the year ahead." },
      { name: "Greengrass",       afterMonth: 4,  description: "A spring celebration welcoming warmer weather and new beginnings." },
      { name: "Midsummer",        afterMonth: 7,  description: "A summer festival of revelry, romance, and celebration." },
      { name: "Shieldmeet",       afterMonth: 7,  description: "A leap day occurring every four years, immediately after Midsummer. A time for solemn oaths and great deeds.", isLeapOnly: true },
      { name: "Highharvestide",   afterMonth: 9,  description: "An autumn harvest festival of feasting and thanks." },
      { name: "Feast of the Moon",afterMonth: 11, description: "A solemn festival to honour the dead and remember those who have passed." },
    ],
    leapYearRule: "every4",
  },

  locations: [
    { name: "Toril",              location_type: "world",     notes: "The planet on which Faerûn, Kara-Tur, Maztica, and Zakhara sit.", tags: ["world", "planet", "prime material"] },
    { name: "Maztica",            location_type: "continent", parent: "Toril",    notes: "A continent far to the west of Faerûn, home to the Maztican civilizations.", tags: ["west", "new world"] },
    { name: "Kara-Tur",           location_type: "continent", parent: "Toril",    notes: "The eastern continent of Toril, home to ancient human civilizations inspired by the cultures of the Far East.", tags: ["east", "orient"] },
    { name: "Faerûn",             location_type: "continent", parent: "Toril",    notes: "The main continent of Toril and home to the Forgotten Realms setting.", tags: ["forgotten realms", "toril"] },
    { name: "The Underdark",      location_type: "region",    parent: "Toril",    notes: "A vast subterranean realm beneath the surface of Toril, home to drow, mind flayers, beholders, and other horrors.", tags: ["underdark", "underground"] },
    { name: "Sword Coast",        location_type: "region",    parent: "Faerûn",   notes: "A long stretch of coastline on the western edge of Faerûn, one of the most heavily traveled trade routes in the world.", tags: ["sword coast", "northwest faerûn"] },
    { name: "The North",          location_type: "region",    parent: "Faerûn",   notes: "A cold and dangerous frontier stretching north of the Sword Coast, land of frontier towns, orcs, and ancient ruins.", tags: ["north", "frontier"] },
    { name: "Western Heartlands", location_type: "region",    parent: "Faerûn",   notes: "A broad expanse of open land stretching east from the Sword Coast, dotted with trade towns and ruins.", tags: ["heartlands"] },
    { name: "The Dalelands",      location_type: "region",    parent: "Faerûn",   notes: "A collection of loosely allied pastoral communities east of the Cormanthor forest, known for fierce independence.", tags: ["dales", "east", "dalelands"] },
    { name: "Moonsea",            location_type: "region",    parent: "Faerûn",   notes: "A volatile region around the cold inland sea of the same name, dominated by tyrant city-states and the Zhentarim.", tags: ["north", "moonsea", "zhentarim"] },
    { name: "The Silver Marches", location_type: "region",    parent: "The North", notes: "A confederation of northern city-states led by Silverymoon, acting as a bulwark against orc hordes.", tags: ["north", "luruar", "confederation"] },
    { name: "Chult",              location_type: "region",    parent: "Faerûn",   notes: "A steaming jungle peninsula in southern Faerûn, home to dinosaurs, yuan-ti, undead, and the ruins of Omu.", tags: ["jungle", "south", "dinosaurs"] },
    { name: "Cormyr",             location_type: "country",   parent: "Faerûn",   notes: "The Forest Kingdom — a prosperous and lawful realm ruled by the Obarskyr dynasty, defended by the Purple Dragon knights.", tags: ["heartlands", "purple dragons", "war wizards"] },
    { name: "Sembia",             location_type: "country",   parent: "Faerûn",   notes: "A wealthy mercantile nation east of Cormyr, ruled by merchant lords.", tags: ["heartlands", "merchant", "east"] },
    { name: "Amn",                location_type: "country",   parent: "Faerûn",   notes: "A powerful merchant nation south of the Sword Coast, secretly governed by the Council of Six.", tags: ["south", "merchant", "council of six"] },
    { name: "Thay",               location_type: "country",   parent: "Faerûn",   notes: "A theocratic nation ruled by the Zulkir council of Red Wizards. Necromancy is a state art and an export.", tags: ["east", "red wizards", "necromancy", "zulkirs"] },
    { name: "Rashemen",           location_type: "country",   parent: "Faerûn",   notes: "A fierce northern nation ruled by the secretive Wychlaran witches, protected by legendary Berserkers.", tags: ["east", "witches", "wychlaran"] },
    { name: "Calimshan",          location_type: "country",   parent: "Faerûn",   notes: "The southernmost great nation of Faerûn — ancient, hot, steeped in genie-pact magic and guild-lord intrigue.", tags: ["south", "desert", "genies"] },
    { name: "Waterdeep",          location_type: "city",      parent: "Sword Coast", notes: "The City of Splendors. The largest and most cosmopolitan city on the Sword Coast, governed by the masked Lords.", tags: ["city of splendors", "sword coast", "lords of waterdeep"] },
    { name: "Baldur's Gate",      location_type: "city",      parent: "Sword Coast", notes: "A powerful merchant city-state on the River Chionthar, known for the Flaming Fist mercenaries and deep corruption.", tags: ["sword coast", "merchant", "flaming fist"] },
    { name: "Neverwinter",        location_type: "city",      parent: "Sword Coast", notes: "The Jewel of the North. A prosperous city rebuilt after the catastrophic eruption of Mount Hotenow.", tags: ["north", "sword coast", "jewel of the north"] },
    { name: "Luskan",             location_type: "city",      parent: "Sword Coast", notes: "The City of Sails — a lawless port city nominally controlled by five pirate captains.", tags: ["north", "pirates", "arcane brotherhood"] },
    { name: "Silverymoon",        location_type: "city",      parent: "The Silver Marches", notes: "The Gem of the North. A centre of learning, art, and high magic.", tags: ["north", "magic", "gem of the north"] },
    { name: "Menzoberranzan",     location_type: "city",      parent: "The Underdark", notes: "The City of Spiders — a vast drow metropolis deep in the Underdark, ruled by noble Houses devoted to Lolth.", tags: ["underdark", "drow", "lolth", "drizzt"] },
    { name: "Suzail",             location_type: "city",      parent: "Cormyr",    notes: "The capital of Cormyr, seat of the Obarskyr dynasty and mustering ground for the Purple Dragon knights.", tags: ["cormyr", "heartlands", "capital"] },
    { name: "Port Nyanzaru",      location_type: "city",      parent: "Chult",     notes: "The only major settlement in Chult — a vibrant port city ruled by seven merchant princes.", tags: ["chult", "port", "merchant princes"] },
    { name: "Phandalin",          location_type: "town",      parent: "The North",  notes: "A small frontier town near the Sword Mountains, rebuilt after being burned by the Redbrands.", tags: ["north", "frontier"] },
    { name: "Triboar",            location_type: "town",      parent: "The North",  notes: "A prosperous town at the crossroads of the Long Road and the Evermoor Way.", tags: ["north", "trade route"] },
    { name: "Shadowdale",         location_type: "town",      parent: "The Dalelands", notes: "A quiet farming community, made famous as the home of Elminster Aumar, the Sage of Shadowdale.", tags: ["dalelands", "elminster"] },
    { name: "Candlekeep",         location_type: "building",  parent: "Sword Coast", notes: "A great fortress-library — one of the greatest repositories of knowledge in all Faerûn.", tags: ["library", "sword coast", "knowledge"] },
    { name: "Undermountain",      location_type: "dungeon",   parent: "Waterdeep", notes: "A legendary megadungeon carved beneath Waterdeep by the mad wizard Halaster Blackcloak.", tags: ["waterdeep", "megadungeon", "halaster"] },
    { name: "Mithral Hall",       location_type: "dungeon",   parent: "The North",  notes: "A great dwarven fortress, stronghold of Clan Battlehammer, reclaimed from the shadow dragon Shimmergloom.", tags: ["dwarves", "north", "battlehammer"] },
    { name: "Wave Echo Cave",     location_type: "dungeon",   parent: "Phandalin", notes: "An ancient mine famed for its magical resonance, site of the legendary Forge of Spells.", tags: ["phandalin", "mine", "forge of spells"] },
    { name: "Icewind Dale",       location_type: "wilderness",parent: "The North",  notes: "A frozen tundra in the far North, home to the Ten-Towns and the Reghed barbarians.", tags: ["north", "frozen", "ten-towns", "reghed"] },
    { name: "Anauroch",           location_type: "wilderness",parent: "Faerûn",    notes: "A vast magical desert in central Faerûn built over the ruins of the ancient Netheril empire.", tags: ["desert", "netheril", "north", "ancient"] },
  ],

  heroes: [
    {
      name: "Drizzt Do'Urden",
      race: "Drow Elf",
      alignment: "Chaotic Good",
      occupation: "Ranger",
      personality: "Introspective and principled — Drizzt carries the weight of his dark heritage while striving to prove that one's nature is not one's destiny. Speaks rarely, but with conviction. Loyal to his companions above all.",
      backstory: "Born in Menzoberranzan to the noble House Do'Urden, Drizzt rejected the cruel ways of drow society and fled to the surface. After years of surviving alone in the Underdark and then in the Forgotten Realms, he found a second family among the Companions of the Hall.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["companion of the hall", "menzoberranzan", "north", "ranger", "scimitars"],
    },
    {
      name: "Elminster Aumar",
      race: "Human",
      alignment: "Chaotic Good",
      occupation: "Archmage / Chosen of Mystra",
      personality: "Ancient, eccentric, and often infuriatingly cryptic. Elminster has lived for over a millennium and treats most crises as mildly interesting puzzles. Fond of pipe-weed, good wine, and testing people's mettle.",
      backstory: "A simple shepherd's son who became the most powerful wizard in Faerûn through centuries of study and favour from Mystra herself. He has personally shaped the history of the Realms — and carries the burden of knowing it.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["shadowdale", "mystra", "chosen", "sage", "archmage"],
    },
    {
      name: "Jarlaxle Baenre",
      race: "Drow Elf",
      alignment: "Chaotic Neutral",
      occupation: "Mercenary Leader / Schemer",
      personality: "Flamboyant, charming, and utterly self-interested — but possessed of a strange honour toward those who earn his respect. Jarlaxle wears an enormous feathered hat and collects magic items obsessively. He always has a plan within a plan.",
      backstory: "Leader of Bregan D'aerthe, a drow mercenary band that operates above and below the surface. Jarlaxle is the illegitimate son of Matron Baenre and has survived longer than any male drow in Menzoberranzan through sheer cunning.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["bregan d'aerthe", "menzoberranzan", "mercenary", "schemer"],
    },
    {
      name: "Bruenor Battlehammer",
      race: "Dwarf",
      alignment: "Lawful Good",
      occupation: "King of Mithral Hall",
      personality: "Gruff, stubborn, and fiercely loyal — Bruenor shows his love through insults and actions, rarely words. He has a dwarf's pride in craftsmanship and a king's hatred of injustice.",
      backstory: "Orphaned survivor of the sacking of Mithral Hall, Bruenor was raised in Icewind Dale where he adopted the human girl Catti-brie and befriended Drizzt Do'Urden. He eventually reclaimed Mithral Hall and restored his clan.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["mithral hall", "companion of the hall", "battlehammer clan", "dwarf king"],
    },
    {
      name: "Laeral Silverhand",
      race: "Human",
      alignment: "Neutral Good",
      occupation: "Open Lord of Waterdeep / Chosen of Mystra",
      personality: "Measured, intelligent, and politically astute. Laeral carries the weight of centuries and the painful memory of being corrupted by the Crown of Horns. She balances the needs of Waterdeep's common folk against the schemes of the nobility.",
      backstory: "One of the Seven Sisters, the Chosen of Mystra. She was the Lady Mage of Waterdeep and Blackstaff for many years before becoming Open Lord after the death of Dagult Neverember's fall from grace.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["waterdeep", "open lord", "seven sisters", "mystra", "chosen"],
    },
  ],
};
