import type { DndSettingDef } from "./types";
import { FAERUN_DEITIES, FAERUN_PANTHEONS } from "@/data/settingDeities";

export const faerunSetting: DndSettingDef = {
  id: "faerun",
  label: "Forgotten Realms",

  defaultAiPrompt:
    "High fantasy setting with a broad, lived-in palette — warm torchlit stone, deep forest greens, coastal greys, merchant blues, and the gold of old kingdoms. " +
    "Magic is common: arcane sigils on doors, glowing potions on shelves, the faint shimmer of enchantments on weapons. Let it be present but unremarkable to the locals. " +
    "Architecture ranges from rough frontier timber to grand city stonework — show weathering, repairs, guild crests, and the layering of centuries. " +
    "Characters dress practically with cultural flair — Sword Coast merchants in padded doublets, northern rangers in furs and travel-stained cloaks, Waterdhavian nobles in jewelled excess. " +
    "Dungeons should feel ancient and dangerous: crumbling ceilings, torchlight swallowed by darkness, moss on carved stone, the drip of water. " +
    "Creatures should feel like they belong to their environment — a troll reeks of the swamp, a drow moves like shadow, a dragon commands the whole composition. " +
    "Keep the mood bold, adventurous, and world-consistent — heroic without being clean, dangerous without being bleak.",

  calendar: {
    name: "Faerûn (Calendar of Harptos)",
    epochName: "DR",
    defaultYear: 1495,
    weekStyle: "tenday",
    weekRowNames: ["Tenday 1", "Tenday 2", "Tenday 3"],
    months: [
      { name: "Hammer",    alias: "Deepwinter",             days: 30 },
      { name: "Alturiak",  alias: "The Claw of Winter",     days: 30 },
      { name: "Ches",      alias: "The Claw of the Sunsets",days: 30 },
      { name: "Tarsakh",   alias: "The Claw of the Storms", days: 30 },
      { name: "Mirtul",    alias: "The Melting",            days: 30 },
      { name: "Kythorn",   alias: "The Time of Flowers",    days: 30 },
      { name: "Flamerule", alias: "Summertide",             days: 30 },
      { name: "Eleasias",  alias: "Highsun",                days: 30 },
      { name: "Eleint",    alias: "The Fading",             days: 30 },
      { name: "Marpenoth", alias: "Leaffall",               days: 30 },
      { name: "Uktar",     alias: "The Rotting",            days: 30 },
      { name: "Nightal",   alias: "The Drawing Down",       days: 30 },
    ],
    intercalaryDays: [
      { name: "Midwinter",        afterMonth: 1,  description: "A mid-winter festival of introspection and planning for the year ahead." },
      { name: "Greengrass",       afterMonth: 4,  description: "A spring celebration welcoming warmer weather and new beginnings." },
      { name: "Midsummer",        afterMonth: 7,  description: "A summer festival of revelry, romance, and celebration." },
      { name: "Shieldmeet",       afterMonth: 7,  description: "A leap day occurring every four years, immediately after Midsummer. A time for solemn oaths and great deeds.", isLeapOnly: true },
      { name: "Highharvestide",   afterMonth: 9,  description: "An autumn harvest festival of feasting and thanks." },
      { name: "Feast of the Moon",afterMonth: 11, description: "A solemn festival to honour the dead and remember those who have passed." },
    ],
    leapYearRule: "every4",
  },

  locations: [
    { name: "Toril",              location_type: "world",     notes: "The planet on which Faerûn, Kara-Tur, Maztica, and Zakhara sit.", tags: ["world", "planet", "prime material"] },
    { name: "Maztica",            location_type: "continent", parent: "Toril",    notes: "A continent far to the west of Faerûn, home to the Maztican civilizations.", tags: ["west", "new world"] },
    { name: "Kara-Tur",           location_type: "continent", parent: "Toril",    notes: "The eastern continent of Toril, home to ancient human civilizations inspired by the cultures of the Far East.", tags: ["east", "orient"] },
    { name: "Faerûn",             location_type: "continent", parent: "Toril",    notes: "The main continent of Toril and home to the Forgotten Realms setting.", tags: ["forgotten realms", "toril"] },
    { name: "The Underdark",      location_type: "region",    parent: "Toril",    notes: "A vast subterranean realm beneath the surface of Toril, home to drow, mind flayers, beholders, and other horrors.", tags: ["underdark", "underground"] },
    { name: "Sword Coast",        location_type: "region",    parent: "Faerûn",   notes: "A long stretch of coastline on the western edge of Faerûn, one of the most heavily traveled trade routes in the world.", tags: ["sword coast", "northwest faerûn"] },
    { name: "The North",          location_type: "region",    parent: "Faerûn",   notes: "A cold and dangerous frontier stretching north of the Sword Coast, land of frontier towns, orcs, and ancient ruins.", tags: ["north", "frontier"] },
    { name: "Western Heartlands", location_type: "region",    parent: "Faerûn",   notes: "A broad expanse of open land stretching east from the Sword Coast, dotted with trade towns and ruins.", tags: ["heartlands"] },
    { name: "The Dalelands",      location_type: "region",    parent: "Faerûn",   notes: "A collection of loosely allied pastoral communities east of the Cormanthor forest, known for fierce independence.", tags: ["dales", "east", "dalelands"] },
    { name: "Moonsea",            location_type: "region",    parent: "Faerûn",   notes: "A volatile region around the cold inland sea of the same name, dominated by tyrant city-states and the Zhentarim.", tags: ["north", "moonsea", "zhentarim"] },
    { name: "The Silver Marches", location_type: "region",    parent: "The North", notes: "A confederation of northern city-states led by Silverymoon, acting as a bulwark against orc hordes.", tags: ["north", "luruar", "confederation"] },
    { name: "Chult",              location_type: "region",    parent: "Faerûn",   notes: "A steaming jungle peninsula in southern Faerûn, home to dinosaurs, yuan-ti, undead, and the ruins of Omu.", tags: ["jungle", "south", "dinosaurs"] },
    { name: "Cormyr",             location_type: "country",   parent: "Faerûn",   notes: "The Forest Kingdom — a prosperous and lawful realm ruled by the Obarskyr dynasty, defended by the Purple Dragon knights.", tags: ["heartlands", "purple dragons", "war wizards"] },
    { name: "Sembia",             location_type: "country",   parent: "Faerûn",   notes: "A wealthy mercantile nation east of Cormyr, ruled by merchant lords.", tags: ["heartlands", "merchant", "east"] },
    { name: "Amn",                location_type: "country",   parent: "Faerûn",   notes: "A powerful merchant nation south of the Sword Coast, secretly governed by the Council of Six.", tags: ["south", "merchant", "council of six"] },
    { name: "Thay",               location_type: "country",   parent: "Faerûn",   notes: "A theocratic nation ruled by the Zulkir council of Red Wizards. Necromancy is a state art and an export.", tags: ["east", "red wizards", "necromancy", "zulkirs"] },
    { name: "Rashemen",           location_type: "country",   parent: "Faerûn",   notes: "A fierce northern nation ruled by the secretive Wychlaran witches, protected by legendary Berserkers.", tags: ["east", "witches", "wychlaran"] },
    { name: "Calimshan",          location_type: "country",   parent: "Faerûn",   notes: "The southernmost great nation of Faerûn — ancient, hot, steeped in genie-pact magic and guild-lord intrigue.", tags: ["south", "desert", "genies"] },
    { name: "Waterdeep",          location_type: "city",      parent: "Sword Coast", notes: "The City of Splendors. The largest and most cosmopolitan city on the Sword Coast, governed by the masked Lords.", tags: ["city of splendors", "sword coast", "lords of waterdeep"] },
    { name: "Baldur's Gate",      location_type: "city",      parent: "Sword Coast", notes: "A powerful merchant city-state on the River Chionthar, known for the Flaming Fist mercenaries and deep corruption.", tags: ["sword coast", "merchant", "flaming fist"] },
    { name: "Neverwinter",        location_type: "city",      parent: "Sword Coast", notes: "The Jewel of the North. A prosperous city rebuilt after the catastrophic eruption of Mount Hotenow.", tags: ["north", "sword coast", "jewel of the north"] },
    { name: "Luskan",             location_type: "city",      parent: "Sword Coast", notes: "The City of Sails — a lawless port city nominally controlled by five pirate captains.", tags: ["north", "pirates", "arcane brotherhood"] },
    { name: "Silverymoon",        location_type: "city",      parent: "The Silver Marches", notes: "The Gem of the North. A centre of learning, art, and high magic.", tags: ["north", "magic", "gem of the north"] },
    { name: "Menzoberranzan",     location_type: "city",      parent: "The Underdark", notes: "The City of Spiders — a vast drow metropolis deep in the Underdark, ruled by noble Houses devoted to Lolth.", tags: ["underdark", "drow", "lolth", "drizzt"] },
    { name: "Suzail",             location_type: "city",      parent: "Cormyr",    notes: "The capital of Cormyr, seat of the Obarskyr dynasty and mustering ground for the Purple Dragon knights.", tags: ["cormyr", "heartlands", "capital"] },
    { name: "Port Nyanzaru",      location_type: "city",      parent: "Chult",     notes: "The only major settlement in Chult — a vibrant port city ruled by seven merchant princes.", tags: ["chult", "port", "merchant princes"] },
    { name: "Phandalin",          location_type: "town",      parent: "The North",  notes: "A small frontier town near the Sword Mountains, rebuilt after being burned by the Redbrands.", tags: ["north", "frontier"] },
    { name: "Triboar",            location_type: "town",      parent: "The North",  notes: "A prosperous town at the crossroads of the Long Road and the Evermoor Way.", tags: ["north", "trade route"] },
    { name: "Shadowdale",         location_type: "town",      parent: "The Dalelands", notes: "A quiet farming community, made famous as the home of Elminster Aumar, the Sage of Shadowdale.", tags: ["dalelands", "elminster"] },
    { name: "Candlekeep",         location_type: "building",  parent: "Sword Coast", notes: "A great fortress-library — one of the greatest repositories of knowledge in all Faerûn.", tags: ["library", "sword coast", "knowledge"] },
    { name: "Undermountain",      location_type: "dungeon",   parent: "Waterdeep", notes: "A legendary megadungeon carved beneath Waterdeep by the mad wizard Halaster Blackcloak.", tags: ["waterdeep", "megadungeon", "halaster"] },
    { name: "Mithral Hall",       location_type: "dungeon",   parent: "The North",  notes: "A great dwarven fortress, stronghold of Clan Battlehammer, reclaimed from the shadow dragon Shimmergloom.", tags: ["dwarves", "north", "battlehammer"] },
    { name: "Wave Echo Cave",     location_type: "dungeon",   parent: "Phandalin", notes: "An ancient mine famed for its magical resonance, site of the legendary Forge of Spells.", tags: ["phandalin", "mine", "forge of spells"] },
    { name: "Icewind Dale",       location_type: "wilderness",parent: "The North",  notes: "A frozen tundra in the far North, home to the Ten-Towns and the Reghed barbarians.", tags: ["north", "frozen", "ten-towns", "reghed"] },
    { name: "Anauroch",           location_type: "wilderness",parent: "Faerûn",    notes: "A vast magical desert in central Faerûn built over the ruins of the ancient Netheril empire.", tags: ["desert", "netheril", "north", "ancient"] },
  ],

  factions: [
    { name: "Harpers",                description: "A covert network of bards, rangers, and spellcasters who protect the balance of power and the rights of common folk. They oppose tyranny wherever they find it.", faction_type: "Secret Society", alignment: "Neutral Good", tags: ["covert", "good", "balance"] },
    { name: "Zhentarim",              description: "A mercenary network seeking wealth and influence through any means necessary. They offer the best deal — and always collect. Also called the Black Network.", faction_type: "Criminal", alignment: "Neutral Evil", tags: ["mercenary", "evil", "wealth", "black network"] },
    { name: "Lords' Alliance",        description: "A coalition of northern city-states and rulers united by mutual self-interest. They fund adventurers willing to protect their trade routes and political stability.", faction_type: "Government", alignment: "Lawful Neutral", tags: ["political", "lawful", "north"] },
    { name: "Emerald Enclave",        description: "A druidic and ranger organization devoted to preserving the natural world against civilization's encroachment and unnatural threats.", faction_type: "Order", alignment: "True Neutral", tags: ["nature", "druids", "rangers"] },
    { name: "Order of the Gauntlet",  description: "A vigilant order of paladins and clerics dedicated to hunting evil, protecting the innocent, and smiting the undead. They act swiftly where the law cannot reach.", faction_type: "Order", alignment: "Lawful Good", tags: ["paladins", "good", "anti-undead"] },
    { name: "Red Wizards of Thay",    description: "The ruling arcane order of Thay — tattooed mages who deal in magic items, slaves, and political leverage across Faerûn. Their enclaves appear in every major city. Their true agenda is always worse than it looks.", faction_type: "Order", alignment: "Lawful Evil", tags: ["thay", "evil", "necromancy", "zulkirs", "magic"] },
    { name: "Arcane Brotherhood",     description: "A mercantile fellowship of wizards based in Luskan's Host Tower. They trade in arcane knowledge and monopolise the magical markets of the Savage North, backing their commercial interests with considerable force.", faction_type: "Guild", alignment: "Neutral Evil", tags: ["luskan", "wizards", "north", "mercantile"] },
    { name: "Flaming Fist",           description: "Baldur's Gate's pre-eminent mercenary company and de facto city guard. They hire out across Faerûn and answer to the Grand Duke — but the Fist's loyalty follows the coin.", faction_type: "Military", alignment: "Lawful Neutral", tags: ["baldur's gate", "mercenary", "military", "lawful"] },
    { name: "Bregan D'aerthe",        description: "A drow mercenary company founded by Jarlaxle Baenre — ruthless, pragmatic, and surprisingly willing to deal with surface-dwellers. They operate from the shadows in cities across the Sword Coast.", faction_type: "Criminal", alignment: "Chaotic Neutral", tags: ["drow", "mercenary", "jarlaxle", "underdark", "covert"] },
    { name: "Xanathar Guild",         description: "The criminal empire of Xanathar, a paranoid beholder lord who rules Waterdeep's underworld from a lair beneath the city. The guild controls much of the city's illegal trade and takes a cut of every criminal enterprise.", faction_type: "Criminal", alignment: "Neutral Evil", tags: ["waterdeep", "criminal", "beholder", "underworld"] },
    { name: "Cult of the Dragon",     description: "Devoted to the belief that undead dragons are the ultimate form of power, the Cult hoards wealth, forges alliances with dracoliches, and pursues schemes to raise a Dracolich Queen. A centuries-old threat that has grown more dangerous with every passing decade.", faction_type: "Cult", alignment: "Neutral Evil", tags: ["dragons", "undead", "evil", "cult", "dracolich"] },
    { name: "Shadow Thieves",         description: "Faerûn's most extensive thieves' guild, headquartered in Amn and operating across the continent. They lost Waterdeep to the Xanathar Guild — a wound they have not forgiven and intend to repay.", faction_type: "Criminal", alignment: "Neutral Evil", tags: ["amn", "thieves", "criminal", "guild"] },
    { name: "Force Grey",             description: "Waterdeep's elite response team — a small, hand-picked band of adventurers authorised by the Masked Lords to handle threats too sensitive or powerful for the City Watch. Membership is an honour and a liability.", faction_type: "Military", alignment: "Neutral Good", tags: ["waterdeep", "elite", "lords", "adventurers"] },
    { name: "Purple Dragon Knights",  description: "Cormyr's knightly order — the armoured backbone of the Forest Kingdom's military. They enforce the King's law, patrol the roads, and swear personal oaths to the Obarskyr crown.", faction_type: "Order", alignment: "Lawful Good", tags: ["cormyr", "knights", "military", "lawful"] },
    { name: "Moonstar",               description: "A secret society within Waterdeep's nobility dedicated to opposing the Xanathar Guild and other threats to the city — funded by old money, staffed by idealists, and quietly mentored by the Harpers.", faction_type: "Secret Society", alignment: "Neutral Good", tags: ["waterdeep", "noble", "secret", "covert"] },
  ],

  heroes: [
    {
      name: "Drizzt Do'Urden",
      race: "Drow Elf",
      alignment: "Chaotic Good",
      occupation: "Ranger",
      personality: "Introspective and principled — Drizzt carries the weight of his dark heritage while striving to prove that one's nature is not one's destiny. Speaks rarely, but with conviction. Loyal to his companions above all.",
      backstory: "Born in Menzoberranzan to the noble House Do'Urden, Drizzt rejected the cruel ways of drow society and fled to the surface. After years of surviving alone in the Underdark and then in the Forgotten Realms, he found a second family among the Companions of the Hall.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["companion of the hall", "menzoberranzan", "north", "ranger", "scimitars"],
    },
    {
      name: "Elminster Aumar",
      race: "Human",
      alignment: "Chaotic Good",
      occupation: "Archmage / Chosen of Mystra",
      personality: "Ancient, eccentric, and often infuriatingly cryptic. Elminster has lived for over a millennium and treats most crises as mildly interesting puzzles. Fond of pipe-weed, good wine, and testing people's mettle.",
      backstory: "A simple shepherd's son who became the most powerful wizard in Faerûn through centuries of study and favour from Mystra herself. He has personally shaped the history of the Realms — and carries the burden of knowing it.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["shadowdale", "mystra", "chosen", "sage", "archmage"],
    },
    {
      name: "Jarlaxle Baenre",
      race: "Drow Elf",
      alignment: "Chaotic Neutral",
      occupation: "Mercenary Leader / Schemer",
      personality: "Flamboyant, charming, and utterly self-interested — but possessed of a strange honour toward those who earn his respect. Jarlaxle wears an enormous feathered hat and collects magic items obsessively. He always has a plan within a plan.",
      backstory: "Leader of Bregan D'aerthe, a drow mercenary band that operates above and below the surface. Jarlaxle is the illegitimate son of Matron Baenre and has survived longer than any male drow in Menzoberranzan through sheer cunning.",
      status: "alive",
      relationship: "indifferent",
      portrait_url: null,
      tags: ["bregan d'aerthe", "menzoberranzan", "mercenary", "schemer"],
    },
    {
      name: "Artemis Entreri",
      race: "Human",
      alignment: "Lawful Evil",
      occupation: "Assassin",
      personality: "Cold, exacting, and completely without illusion about himself or anyone else. Entreri is the finest assassin in the Realms and he knows it. He does not enjoy killing — he simply excels at it, which is somehow worse.",
      backstory: "Born in the slums of Calimport, Entreri clawed his way to the top of the assassin's guild through pure ruthless competence. He became Drizzt Do'Urden's greatest rival — not out of hatred but because Drizzt is the only person who can match him, and that is something Entreri cannot accept.",
      status: "alive",
      relationship: "indifferent",
      portrait_url: null,
      tags: ["calimport", "assassin", "companion of the hall", "entreri", "zhengyi"],
    },
    {
      name: "Bruenor Battlehammer",
      race: "Dwarf",
      alignment: "Lawful Good",
      occupation: "King of Mithral Hall",
      personality: "Gruff, stubborn, and fiercely loyal — Bruenor shows his love through insults and actions, rarely words. He has a dwarf's pride in craftsmanship and a king's hatred of injustice.",
      backstory: "Orphaned survivor of the sacking of Mithral Hall, Bruenor was raised in Icewind Dale where he adopted the human girl Catti-brie and befriended Drizzt Do'Urden. He eventually reclaimed Mithral Hall and restored his clan.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["mithral hall", "companion of the hall", "battlehammer clan", "dwarf king"],
    },
    {
      name: "Catti-brie",
      race: "Human",
      alignment: "Chaotic Good",
      occupation: "Archer / Mage",
      personality: "Spirited, warm, and far more perceptive than people expect from someone that charming. Catti-brie has her adoptive father's stubbornness but a human's adaptability. She is capable of extraordinary compassion and equally extraordinary accuracy with a bow.",
      backstory: "Adopted by Bruenor Battlehammer after her family was killed by gnolls, Catti-brie grew up among dwarves and adventurers. She is one of the Companions of the Hall and wields the magical bow Taulmaril. In her later life she became a formidable wizard as well.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["companion of the hall", "archer", "mithral hall", "taulmaril"],
    },
    {
      name: "Wulfgar",
      race: "Human",
      alignment: "Chaotic Good",
      occupation: "Warrior / Chieftain",
      personality: "Huge, honourable, and carrying deep scars from years imprisoned in the Abyss. Wulfgar is working to rebuild himself after trauma — he is brave and kind but struggles with rage he has not yet mastered.",
      backstory: "A barbarian of the Icewind Dale who was captured by Bruenor and raised as a son. He wields the warhammer Aegis-fang, crafted for him by Bruenor. After years of imprisonment by the demon Errtu, Wulfgar has rejoined the Companions changed but unbroken.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["companion of the hall", "icewind dale", "barbarian", "aegis-fang"],
    },
    {
      name: "Regis",
      race: "Halfling",
      alignment: "Neutral Good",
      occupation: "Rogue / Diplomat",
      personality: "Lazy, charming, and far more clever than his comfortable demeanour suggests. Regis would rather talk his way out of trouble than fight his way through it, which has led to some surprisingly elegant solutions. He is genuinely kind beneath the scheming.",
      backstory: "A halfling thief from Calimport who fled his criminal past to Ten-Towns in Icewind Dale. He carries a ruby pendant of hypnosis that he stole from the thieves' guild master Pasha Pook — which is why a guild assassin keeps being sent to find him.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["companion of the hall", "halfling", "icewind dale", "rogue", "ten-towns"],
    },
    {
      name: "Laeral Silverhand",
      race: "Human",
      alignment: "Neutral Good",
      occupation: "Open Lord of Waterdeep / Chosen of Mystra",
      personality: "Measured, intelligent, and politically astute. Laeral carries the weight of centuries and the painful memory of being corrupted by the Crown of Horns. She balances the needs of Waterdeep's common folk against the schemes of the nobility.",
      backstory: "One of the Seven Sisters, the Chosen of Mystra. She was the Lady Mage of Waterdeep and Blackstaff for many years before becoming Open Lord after the death of Dagult Neverember's fall from grace.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["waterdeep", "open lord", "seven sisters", "mystra", "chosen"],
    },
    {
      name: "Vajra Safahr",
      race: "Human",
      alignment: "Neutral Good",
      occupation: "Blackstaff of Waterdeep",
      personality: "Direct, serious, and somewhat overwhelmed by an office that carries seven centuries of accumulated magical obligation. Vajra wields the Blackstaff — a sentient artifact — and must navigate its advice, which is not always welcome.",
      backstory: "The current Blackstaff of Waterdeep, keeper of the city's most powerful magical defences. She was chosen by the previous Blackstaff Khelben Arunsun and is still growing into the role's full weight. The staff itself is semi-sentient and does not always agree with her decisions.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["waterdeep", "blackstaff", "archmage", "wizard tower", "defender"],
    },
    {
      name: "Dagult Neverember",
      race: "Human",
      alignment: "Lawful Neutral",
      occupation: "Lord Protector of Neverwinter / Former Open Lord",
      personality: "Charismatic, ruthlessly ambitious, and genuinely talented at governance — which makes him all the more dangerous. Neverember never does anything without a self-serving angle, but his angles often align with what his subjects actually need.",
      backstory: "Once the Open Lord of Waterdeep, Neverember was removed from power when the city's hidden Lords concluded his ambitions had outgrown his usefulness. He relocated to Neverwinter, which he is rebuilding as Lord Protector. He nurses grievances and long-term plans in equal measure.",
      status: "alive",
      relationship: "indifferent",
      portrait_url: null,
      tags: ["neverwinter", "waterdeep", "lord protector", "politician", "ambitious"],
    },
    {
      name: "Grand Duke Ulder Ravengard",
      race: "Human",
      alignment: "Lawful Good",
      occupation: "Grand Duke of Baldur's Gate / Marshal of the Flaming Fist",
      personality: "Hard, principled, and uncomfortable with politics. Ravengard built his career through military competence and still prefers a direct order to a diplomatic manoeuvre. He is honest to a fault and deeply suspicious of anyone who isn't.",
      backstory: "Rose from common soldier to Marshal of the Flaming Fist through sheer ability and force of will. He was then elevated to Grand Duke of Baldur's Gate — a political office he finds genuinely baffling. He is one of the few Grand Dukes who is not visibly corrupt, which makes him either admirable or naive depending on who you ask.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["baldur's gate", "flaming fist", "grand duke", "military", "lawful"],
    },
    {
      name: "Halaster Blackcloak",
      race: "Human",
      alignment: "Chaotic Evil",
      occupation: "Mad Wizard / Master of Undermountain",
      personality: "Brilliantly, comprehensively insane. Halaster has spent so many centuries warping the laws of magic inside Undermountain that he has lost his grip on consensus reality. He is delighted by adventurers — as test subjects, entertainment, and occasional dinner guests.",
      backstory: "The legendary archmage who carved Undermountain beneath Waterdeep over a thousand years ago. He lured seven wizards as apprentices, trapped them in the dungeon when they tried to leave, and has been sealing and stocking his megadungeon ever since. He is functionally immortal and thoroughly mad.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["undermountain", "waterdeep", "mad wizard", "megadungeon", "archmage"],
    },
    {
      name: "Lolth",
      race: "Deity",
      alignment: "Chaotic Evil",
      occupation: "Demon Queen of Spiders / Goddess of the Drow",
      personality: "Mercurial, sadistic, and addicted to chaos as an aesthetic principle. Lolth demands absolute devotion and rewards it with tests of loyalty that amount to elaborate cruelty. She genuinely enjoys watching her followers destroy each other.",
      backstory: "The Spider Queen who rules from the Demonweb Pits in the Abyss. Lolth remade drow society in her image — matriarchal, violent, and perpetually at war with itself — because an ordered society wouldn't need her. Every house war, every assassination, every betrayal in Menzoberranzan feeds her power.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["drow", "menzoberranzan", "spider queen", "abyss", "deity"],
    },
    {
      name: "Szass Tam",
      race: "Lich",
      alignment: "Neutral Evil",
      occupation: "Regent of Thay / Zulkir of Necromancy",
      personality: "Patient, brilliant, and operating on timelines that make other powerful mages look like they are running to stand still. Szass Tam is the most dangerous undead spellcaster in Faerûn — not because of raw power but because he has been outmanoeuvring enemies for centuries and has never stopped improving.",
      backstory: "The ancient lich who rules Thay after a bloody internal coup against the other Zulkirs. He sacrificed his mortality for perfect undeath long ago and has used his unnatural patience to convert Thay into a necrocracy — a nation run by and for the undead. He exports Red Wizard enclaves as intelligence networks across the continent.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["thay", "lich", "red wizards", "necromancy", "zulkir"],
    },
    {
      name: "Manshoon",
      race: "Human (Clone)",
      alignment: "Lawful Evil",
      occupation: "Zhentarim Leader / Clone-Mage",
      personality: "Cold, controlling, and obsessed with hierarchy. Manshoon believes the world would function better if he were in charge of it — not out of ego but out of a genuine conviction that lesser minds create the chaos he despises. He is charming when he needs to be and lethal when he doesn't.",
      backstory: "The original founder of the Zhentarim, Manshoon died many times — the result of a Clone spell catastrophe — and multiple copies of him roam the Realms with conflicting memories and agendas. The one based in Waterdeep has rebuilt his power carefully and quietly from the city's criminal underground.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["zhentarim", "wizard", "clone", "waterdeep", "villain"],
    },
    {
      name: "Mordenkainen",
      race: "Human",
      alignment: "True Neutral",
      occupation: "Archmage / Multiplanar Traveller",
      personality: "Brilliant, calculating, and utterly convinced that balance is the only philosophy worth holding. Mordenkainen visits the Realms as he visits every other world — to observe, influence, and leave. He is not cold exactly, but he is always performing a calculation you cannot see.",
      backstory: "Greyhawk's greatest archmage who travels the planes and visits multiple worlds including Faerûn. He authored many famous spells that bear his name. On Faerûn he maintains a loose network of allies and information, convinced that no power should be allowed to dominate the world — including the ones he likes.",
      status: "alive",
      relationship: "indifferent",
      portrait_url: null,
      tags: ["archmage", "planar traveller", "balance", "spells", "greyhawk"],
    },
    {
      name: "Volo (Volothamp Geddarm)",
      race: "Human",
      alignment: "Chaotic Good",
      occupation: "Author / Explorer / Guidebook Writer",
      personality: "Enthusiastic, boastful, and often wrong in memorable ways. Volo has a gift for finding himself at the centre of events he is completely unprepared for. He is genuinely brave in the way that people who don't quite grasp danger can be.",
      backstory: "Faerûn's most famous travel writer and author of numerous guides to the Realms. He has survived encounters that should have killed him through luck, charm, and the sheer narrative force of being exactly the kind of person who should not survive. He is also frequently banned from specific cities for specific reasons.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["author", "explorer", "waterdeep", "traveller", "guidebooks"],
    },
    {
      name: "Tasha (Iggwilv)",
      race: "Human",
      alignment: "Chaotic Evil",
      occupation: "Archmage / Demonologist / Witch Queen",
      personality: "Brilliant, terrifying, and completely amoral. Iggwilv views everyone as a tool or an obstacle. She has enslaved demon lords, toppled kingdoms, and outlived most of her enemies — and she finds this delightful. Her current demeanour as 'Tasha' is a somewhat more playful performance of the same fundamental ruthlessness.",
      backstory: "Known by many names: Natasha, Tasha, Iggwilv. An apprentice of Zagig Yragerne who surpassed her master and conquered Perrenland. She authored the Demonomicon of Iggwilv, imprisoned the demon lord Graz'zt, and took him as a consort before eventually moving to Faerûn's broader stage.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["witch queen", "demonologist", "demonomicon", "archmage", "graz'zt"],
    },
    {
      name: "Larloch",
      race: "Lich",
      alignment: "Neutral Evil",
      occupation: "The Shadow King / Ancient Lich",
      personality: "Ancient beyond measure and alien in his patience. Larloch has existed so long that most of what he once cared about is dust, and what remains is a cold obsession with power for its own sake. He does not hate; he simply categorises.",
      backstory: "One of the oldest liches in Faerûn, Larloch rules from Warlock's Crypt in the Anauroch desert. He is older than Thay, older than most nations, and his sheer accumulated magical power is rivalled by very few living beings. He endures because accumulation is its own purpose.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["lich", "anauroch", "ancient", "warlock's crypt", "necromancy"],
    },
  ],
  pantheons: FAERUN_PANTHEONS,
  deities: FAERUN_DEITIES,
};
