import type { DndSettingDef } from "./types";

export const greyhawkSetting: DndSettingDef = {
  id: "greyhawk",
  label: "Greyhawk",

  defaultAiPrompt:
    "Gritty sword-and-sorcery fantasy with an earthy, weathered palette — rough-spun wool, worn leather, iron, tallow candles, smoke-stained timber, and river mud. " +
    "Magic is rare and consequential. A wizard should stand out in a crowd — robes mark them as exceptional, their equipment strange and purposeful. Avoid casual magic flourishes. " +
    "Dungeons feel genuinely ancient and lethal: cracked flagstones, thick darkness, rust, bones, the smell of something wrong. Traps look like they were built to last centuries. " +
    "Characters are mercenaries, scholars, priests, and outlaws — dress them in mismatched, repaired gear with regional details. A Velunian knight looks different from a Nyrond footsoldier. " +
    "Cities should feel medieval and layered — guild halls, market chaos, temple banners, the occasional lord's guard moving through a crowd that quietly parts. " +
    "Evil should feel tangible: Iuz's forces are twisted, cruel, and orcish-dark; the Great Kingdom's corruption shows in its finery hiding rot beneath. " +
    "Keep the mood grounded, dangerous, and classically adventurous — this is the world where the genre was forged.",

  calendar: {
    name: "Greyhawk (Oerth Common Year)",
    epochName: "CY",
    defaultYear: 591,
    weekStyle: "weekly",
    dayLabels: ["Starday", "Sunday", "Moonday", "Godsday", "Waterday", "Earthday", "Freeday"],
    months: [
      { name: "Fireseek",   alias: "Deep Winter",   days: 28 },
      { name: "Readying",   alias: "Late Winter",   days: 28 },
      { name: "Coldeven",   alias: "Early Spring",  days: 28 },
      { name: "Planting",   alias: "Mid Spring",    days: 28 },
      { name: "Flocktime",  alias: "Late Spring",   days: 28 },
      { name: "Wealsun",    alias: "Early Summer",  days: 28 },
      { name: "Reaping",    alias: "High Summer",   days: 28 },
      { name: "Goodmonth",  alias: "Late Summer",   days: 28 },
      { name: "Harvester",  alias: "Early Autumn",  days: 28 },
      { name: "Patchwall",  alias: "Mid Autumn",    days: 28 },
      { name: "Ready'reat", alias: "Late Autumn",   days: 28 },
      { name: "Sunsebb",    alias: "Early Winter",  days: 28 },
    ],
    intercalaryDays: [
      { name: "Needfest",  afterMonth: 12, description: "A mid-winter festival of gift-giving and merriment, lasting a full week." },
      { name: "Growfest",  afterMonth: 3,  description: "A spring festival celebrating the return of warmth and the planting season." },
      { name: "Richfest",  afterMonth: 6,  description: "A midsummer celebration of prosperity, games, and revelry." },
      { name: "Brewfest",  afterMonth: 9,  description: "An autumn harvest festival of feasting, drinking, and thanksgiving." },
    ],
    leapYearRule: "none",
  },

  locations: [
    { name: "Oerth",                            location_type: "world",     notes: "The world of Greyhawk — an Earth-like planet orbiting a yellow sun.", tags: ["greyhawk", "world of greyhawk", "planet"] },
    { name: "Oerik",                            location_type: "continent", parent: "Oerth",     notes: "The primary continent of Oerth. Most Greyhawk adventures take place in its eastern region, the Flanaess.", tags: ["greyhawk"] },
    { name: "Flanaess",                         location_type: "region",    parent: "Oerik",     notes: "The eastern portion of Oerik and the primary setting for Greyhawk adventures.", tags: ["greyhawk"] },
    { name: "City of Greyhawk",                 location_type: "city",      parent: "Flanaess",  notes: "The Free City of Greyhawk — a major hub of trade, magic, and political intrigue, named for the ancient castle ruins above it.", tags: ["free city", "greyhawk"] },
    { name: "Dyvers",                           location_type: "city",      parent: "Flanaess",  notes: "A prosperous port city on the Nyr Dyv lake, a commercial rival to the Free City.", tags: ["port", "trade", "nyr dyv"] },
    { name: "Verbobonc",                        location_type: "city",      parent: "Flanaess",  notes: "A fortified city near the Temple of Elemental Evil, gateway to many classic adventures.", tags: ["temple of elemental evil", "classic"] },
    { name: "Furyondy",                         location_type: "country",   parent: "Flanaess",  notes: "A powerful and chivalric kingdom in the central Flanaess, long a bulwark against the spreading evil of Iuz.", tags: ["good", "kingdom"] },
    { name: "Veluna",                           location_type: "country",   parent: "Flanaess",  notes: "A theocratic nation devoted to Rao, god of peace and reason — closely allied with Furyondy.", tags: ["theocracy", "good", "rao"] },
    { name: "Nyrond",                           location_type: "country",   parent: "Flanaess",  notes: "A large and once-proud kingdom in the eastern Flanaess, frequently beset by wars and internal strife.", tags: ["kingdom", "east"] },
    { name: "Iuz",                              location_type: "country",   parent: "Flanaess",  notes: "The evil empire of the cambion demigod Iuz the Old, spanning the north-central Flanaess.", tags: ["evil", "demigod", "empire"] },
    { name: "The Great Kingdom",                location_type: "country",   parent: "Flanaess",  notes: "A vast and crumbling empire in the east, once dominant, now corrupt and fractured into tyrant states.", tags: ["empire", "east", "corrupt"] },
    { name: "Keoland",                          location_type: "country",   parent: "Flanaess",  notes: "A once-great southern kingdom, now content to dominate regional trade.", tags: ["south", "kingdom", "trade"] },
    { name: "Castle Greyhawk",                  location_type: "dungeon",   parent: "City of Greyhawk", notes: "The legendary ruins of the wizard Zagig Yragerne's castle — a classic megadungeon with dozens of levels.", tags: ["megadungeon", "zagig", "ruins", "classic"] },
    { name: "Temple of Elemental Evil",         location_type: "dungeon",   parent: "Verbobonc", notes: "A notorious dungeon built atop a node of pure elemental chaos, once used to summon Zuggtmoy the Demon Queen.", tags: ["classic", "zuggtmoy", "elemental"] },
    { name: "Tomb of Horrors",                  location_type: "dungeon",   parent: "Flanaess",  notes: "The near-inescapable death trap dungeon of Acererak the archlich — the original killer dungeon.", tags: ["acererak", "lich", "classic", "deathtrap"] },
    { name: "Barrier Peaks",                    location_type: "wilderness",parent: "Flanaess",  notes: "A mountain range on the western edge of the Flanaess, rumoured to hold the wreck of a star-vessel.", tags: ["mountains", "west"] },
    { name: "Crystalmist Mountains",            location_type: "wilderness",parent: "Flanaess",  notes: "The highest mountain range on the Flanaess, home to cloud giants, fire giants, and the Vault of the Drow.", tags: ["mountains", "giants", "drow"] },
    { name: "Nyr Dyv",                          location_type: "wilderness",parent: "Flanaess",  notes: "The Lake of Unknown Depths — a vast inland lake at the heart of the Flanaess.", tags: ["lake", "central", "mysterious"] },
  ],

  factions: [
    // Arcane and scholarly
    { name: "Circle of Eight",         description: "A cabal of eight archmages led by Mordenkainen, working behind the scenes to maintain the balance of power across the Flanaess. They do not align with good or evil — only equilibrium — and will undermine either side if one grows too dominant.", faction_type: "Secret Society", alignment: "True Neutral", tags: ["archmages", "balance", "secret", "mordenkainen"] },
    { name: "Guild of Wizardry",       description: "The arcane guild of the Free City of Greyhawk, controlling magical research, licensing, and commerce in the city. Politically cautious and commercially motivated; they oppose any faction that would destabilize the Free City's profitable neutrality.", faction_type: "Guild", alignment: "True Neutral", tags: ["wizards", "greyhawk city", "guild", "arcane"] },
    { name: "Rel Mord Academy",        description: "Nyrond's premier arcane institution, training wizards loyal to the crown. Less prestigious than Greyhawk's Guild but deeply embedded in Nyrondese politics and military planning.", faction_type: "Guild", alignment: "Lawful Neutral", tags: ["nyrond", "wizards", "academy", "military"] },
    // Knightly and military orders
    { name: "Knights of the Hart",     description: "A tripartite alliance of knightly orders — the Knights of Furyondy, the Knights of Veluna, and the Highfolk Warders — united in opposing Iuz and defending the good peoples of the central Flanaess.", faction_type: "Order", alignment: "Lawful Good", tags: ["good", "knights", "furyondy", "anti-iuz"] },
    { name: "Knights of Holy Shielding", description: "Defenders of the Shield Lands — an order of knights sworn to reclaim the lands overrun by Iuz. Most of their territory is lost; most of their membership is in exile, and their determination only deepens.", faction_type: "Order", alignment: "Lawful Good", tags: ["knights", "shield lands", "anti-iuz", "exiles"] },
    { name: "Order of the Hart",       description: "The senior knightly order of Furyondy, sworn to the Furyondian crown. They form the military backbone of the kingdom's resistance against Iuz's constant incursions from the north.", faction_type: "Order", alignment: "Lawful Good", tags: ["furyondy", "knights", "military", "good"] },
    // Evil empires and organizations
    { name: "Iuz the Old's Empire",    description: "The chaotic evil empire of the cambion demigod Iuz, spanning the north-central Flanaess. His armies of humanoids, demons, and undead have overrun the Shield Lands and press against Furyondy. He rules through terror, cruelty, and the Old Ones — his demonic generals.", faction_type: "Government", alignment: "Chaotic Evil", tags: ["evil", "demigod", "empire", "iuz", "cambion"] },
    { name: "The Scarlet Brotherhood", description: "A secretive monastic order of Suel humans who believe their race superior to all others. Operating through assassins, poison, and puppet rulers, they work toward Suel racial supremacy and have already subverted several southern kingdoms.", faction_type: "Secret Society", alignment: "Lawful Evil", tags: ["evil", "secret", "suel", "assassins", "monks"] },
    { name: "The Horned Society",      description: "An evil theocracy of devil-worshippers and humanoid warlords that once ruled its own territory before being consumed by Iuz. Remnants operate as a secretive cult beneath Iuz's occupation, waiting for a chance to reclaim power.", faction_type: "Cult", alignment: "Lawful Evil", tags: ["evil", "devils", "cult", "occupied", "humanoids"] },
    { name: "The Great Kingdom",       description: "The crumbling imperial rump-state of the old Aerdi empire in the east, now ruled by the Overking — a title descended into true madness and diabolism. Its court is corrupt, its nobility treacherous, and its undead-rich army the only thing holding it together.", faction_type: "Government", alignment: "Lawful Evil", tags: ["empire", "evil", "east", "undead", "corrupt"] },
    // Criminal and thieves
    { name: "Greyhawk Thieves' Guild", description: "The most powerful criminal organization in the Free City, controlling theft, smuggling, fencing, and protection. The guild is pragmatic rather than ideological and has agreements with the city watch that keep everything just orderly enough.", faction_type: "Criminal", alignment: "Chaotic Neutral", tags: ["thieves", "criminal", "greyhawk city", "smuggling"] },
    { name: "The Slavers",             description: "A loose criminal network of slavers who operated out of the Pomarj and the Drachensgrab Hills — the antagonists of the A-series adventures. They dealt in mass kidnapping for profit and had unexpected noble backing.", faction_type: "Criminal", alignment: "Neutral Evil", tags: ["slavers", "pomarj", "criminal", "evil", "humanoids"] },
    // Religious cults
    { name: "Temple of Elemental Evil", description: "A notorious dungeon complex near Verbobonc built to serve Zuggtmoy, Demon Queen of Fungi. Repeatedly cleansed and repeatedly reactivated, it serves as a node of pure elemental chaos that attracts evil like a wound draws flies.", faction_type: "Cult", alignment: "Chaotic Evil", tags: ["zuggtmoy", "elemental", "demon", "cult", "dungeon"] },
    { name: "Cult of Tharizdun",       description: "The most feared cult in the Flanaess — worshippers of the Elder Elemental God, the Chained God who predates even the gods themselves. They seek to free him from his imprisonment, which would end existence as it is currently arranged.", faction_type: "Cult", alignment: "Chaotic Evil", tags: ["tharizdun", "elder god", "forbidden", "apocalyptic", "cult"] },
    // Humanoid factions
    { name: "Pomarj Humanoids",        description: "The orcish and gnollish humanoid confederation that controls the Pomarj peninsula after slaughtering or driving out its human population. They serve as a constant threat to the Wild Coast and launch regular raids northward.", faction_type: "Tribe", alignment: "Chaotic Evil", tags: ["orcs", "gnolls", "humanoids", "pomarj", "raiders"] },
    { name: "Furyondian Resistance",   description: "The military and civilian resistance movement within Furyondy and the occupied Shield Lands — knights, farmers, and priests working to slow Iuz's advance and maintain hope in the occupied north.", faction_type: "Military", alignment: "Neutral Good", tags: ["furyondy", "resistance", "good", "occupied", "anti-iuz"] },
  ],

  heroes: [
    {
      name: "Mordenkainen",
      race: "Human",
      alignment: "True Neutral",
      occupation: "Archmage",
      personality: "Aloof, calculating, and utterly devoted to maintaining the balance of power between good and evil — not because he favours goodness, but because he believes imbalance leads to ruin. He is brilliant, condescending, and occasionally more dangerous than the problems he claims to solve.",
      backstory: "The most powerful wizard in the Flanaess and leader of the Circle of Eight — a group of archmages who work behind the scenes to prevent any single power from dominating the world. Mordenkainen's famous spells bear his name across every world.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["circle of eight", "archmage", "balance", "city of greyhawk"],
    },
    {
      name: "Bigby",
      race: "Human",
      alignment: "Neutral Good",
      occupation: "Archmage / Circle of Eight",
      personality: "More warmly human than his master Mordenkainen — Bigby genuinely cares about the people affected by the Circle's abstract power games. He is thoughtful and reluctant to use his terrible power, but formidable when pushed.",
      backstory: "Once a thief's apprentice and then a servant of the evil wizard Leomund, Bigby was freed and mentored by Mordenkainen. He created his famous series of hand spells. Now a member of the Circle of Eight, he quietly advocates for more direct action against evil.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["circle of eight", "archmage", "city of greyhawk", "bigby's hand"],
    },
    {
      name: "Tenser",
      race: "Human",
      alignment: "Neutral Good",
      occupation: "Archmage / Circle of Eight",
      personality: "The most idealistic member of the Circle — Tenser genuinely wants to use his power to do good, which puts him in constant philosophical conflict with Mordenkainen's cold calculus. He has been known to act unilaterally when he believes the balance argument is being used to excuse inaction.",
      backstory: "A powerful archmage and member of the Circle of Eight, Tenser has his own tower and his own agents. He created Tenser's Transformation, the spell that makes a wizard fight like a fighter. He was once killed and recreated from a clone — an experience that changed his perspective on mortality considerably.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["circle of eight", "archmage", "city of greyhawk", "tenser's transformation"],
    },
    {
      name: "Rary the Traitor",
      race: "Human",
      alignment: "Neutral Evil",
      occupation: "Renegade Archmage / Desert Ruler",
      personality: "Brilliant and bitter. Rary spent decades working for a balance he no longer believes in, then chose self-interest at the worst possible moment. He does not apologize. He has built something for himself in the Bright Desert and intends to keep it.",
      backstory: "Once a respected member of the Circle of Eight, Rary betrayed the Circle during the signing of the Greyhawk Peace Treaty — killing Tenser and Otiluke and fleeing with Lord Robilar to the Bright Desert, where he now rules as a desert power. His motives remain partially unclear.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["circle of eight", "traitor", "bright desert", "archmage", "renegade"],
    },
    {
      name: "Tasha (Iggwilv)",
      race: "Human",
      alignment: "Chaotic Evil",
      occupation: "Archmage / Demonologist / Witch Queen",
      personality: "Brilliant, terrifying, and completely amoral. Iggwilv views everyone as a tool or an obstacle. She has enslaved demon lords, toppled kingdoms, and outlived most of her enemies — and she finds this delightful.",
      backstory: "Known by many names, including Natasha and Tasha. An apprentice of Zagig Yragerne who eventually surpassed her master. Iggwilv conquered Perrenland, authored the Demonomicon, and imprisoned the demon lord Graz'zt — whom she later took as a consort.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["witch queen", "demonologist", "demonomicon", "perrenland", "graz'zt"],
    },
    {
      name: "Jallarzi Sallavarian",
      race: "Human",
      alignment: "Neutral Good",
      occupation: "Archmage / Circle of Eight",
      personality: "Warm, principled, and the moral compass of the Circle of Eight. Jallarzi is less interested in abstract balance than in the actual wellbeing of people. She is well-loved and deeply trusted — which makes her a target.",
      backstory: "The newest and most idealistic member of the Circle of Eight, Jallarzi represents a more humane approach to arcane power politics. She works to ensure the Circle's decisions consider the cost to ordinary people.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["circle of eight", "archmage", "city of greyhawk"],
    },
    {
      name: "Iuz the Old",
      race: "Cambion",
      alignment: "Chaotic Evil",
      occupation: "Demigod / Tyrant",
      personality: "Ancient, sadistic, and possessed of a demigod's patience. Iuz delights in cruelty and instability. He is not merely evil — he is invested in suffering as an art form.",
      backstory: "The half-fiend son of the demon lord Graz'zt and the witch Iggwilv, Iuz built a kingdom through conquest and atrocity. He was once imprisoned by Zagig Yragerne but broke free, and his empire now threatens the peace of the entire Flanaess.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["demigod", "tyrant", "cambion", "graz'zt", "iggwilv"],
    },
    {
      name: "Zagyg Yragerne",
      race: "Human (Demigod)",
      alignment: "Chaotic Neutral",
      occupation: "Mad Archmage / Demigod",
      personality: "Incomprehensible. Zagyg's madness is not a defect — it is a philosophy. He built Castle Greyhawk as a monument to chaos and trapped several deities in its depths. His humour is real. His cruelty is real. These are not in conflict for him.",
      backstory: "The Mad Archmage of Greyhawk, builder of the legendary Castle Greyhawk megadungeon. He achieved apotheosis — becoming a demigod — through a ritual that may have involved trapping the demigod Iuz in his dungeon. Zagyg vanished long ago but his works are everywhere.",
      status: "missing",
      relationship: "neutral",
      portrait_url: null,
      tags: ["castle greyhawk", "mad archmage", "demigod", "greyhawk city", "chaotic"],
    },
    {
      name: "Acererak",
      race: "Lich (Demilich)",
      alignment: "Neutral Evil",
      occupation: "Demilich / Tomb Builder",
      personality: "There is very little personality left. Acererak has transcended lichdom and most of what he was is now devoted to power, souls, and architecture. The Tomb of Horrors is the clearest expression of his remaining will: a lethal statement that adventurers are prey.",
      backstory: "Once a cambion wizard who became a lich and then transcended even that — Acererak shed his body and became a demilich, his soul gem floating in the most lethal dungeon in the world. He builds death-trap dungeons across the multiverse for reasons that have become opaque even to those who study him.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["demilich", "tomb of horrors", "lich", "death trap", "undead"],
    },
    {
      name: "Keraptis",
      race: "Human (Lich-like)",
      alignment: "Chaotic Evil",
      occupation: "Mad Wizard / White Plume Mountain Ruler",
      personality: "Erratic, megalomaniacal, and obsessed with proving his superiority. Keraptis has stolen legendary weapons from their owners not because he needs them but because he can, and because it amuses him to watch people try to get them back.",
      backstory: "An ancient evil wizard who once terrorized a kingdom, disappeared, and recently resurfaced in White Plume Mountain. He has stolen the legendary weapons Blackrazor, Wave, and Whelm from their owners and installed elaborate death-trap chambers around them. He may be immortal. He is definitely not sane.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["white plume mountain", "mad wizard", "villain", "evil", "weapons"],
    },
    {
      name: "Robilar",
      race: "Human",
      alignment: "Chaotic Neutral",
      occupation: "Fighter / Warlord",
      personality: "Decisive, ambitious, and not especially troubled by the moral weight of his decisions. Robilar adventured with the heroes who first explored Castle Greyhawk and then allied himself with Rary's betrayal. He is very good at fighting and very bad at allegiances.",
      backstory: "One of the original adventurers to explore Castle Greyhawk alongside Mordenkainen and others. He participated in Rary's betrayal at the end of the Greyhawk Wars and now holds the Bright Desert as Rary's military arm. He has few regrets.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["fighter", "rary", "bright desert", "traitor", "warlord"],
    },
    {
      name: "Nerof Gasgal",
      race: "Human",
      alignment: "True Neutral",
      occupation: "Lord Mayor of the Free City of Greyhawk",
      personality: "Pragmatic, politically dexterous, and deeply invested in the Free City's neutrality — not out of principle but because neutrality is the most profitable position. He will deal with anyone who can pay or who provides leverage. He is never quite where you expect him.",
      backstory: "The current Lord Mayor of the Free City of Greyhawk, leader of the Directing Oligarchy. He rose through the Thieves' Guild before transitioning to legitimate politics, and he remembers exactly what he was. The city runs because he keeps every faction just satisfied enough to not burn anything down.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["greyhawk city", "lord mayor", "oligarchy", "politics", "neutral"],
    },
  ],
};
