import type { DndSettingDef } from "./types";

export const mystaraSetting: DndSettingDef = {
  id: "mystara",
  label: "Mystara",

  defaultAiPrompt:
    "Classic adventure fantasy with a bright, culturally varied palette — Thyatian marble white and imperial crimson, Karameikan frontier timber and muddy roads, Glantrian arcane purples and brass, dwarven Rockhome grey granite and forge-orange, elven Alfheim silver-green. " +
    "Each kingdom has a distinct visual identity — lean into historical analogues. Thyatian soldiers wear segmented armour and carry pilums; Karameikan adventurers look like frontier explorers in mismatched practical gear; Glantrian wizards dress for ceremony and status. " +
    "Magic is present but not ubiquitous — a wizard's tower stands out in a village, magical items are notable, and in Glantri specifically, magic is clearly the highest social currency. In Karameikos, the wilderness is more immediate than any spell. " +
    "Dungeons and ruins predate the current kingdoms — show older civilisation in the stonework, Traladan pictographs beneath Thyatian plaster, dwarven mason marks on what is now an elven road. History is physical here. " +
    "Characters should feel like people from specific places — a Thyatian soldier carries Imperial swagger, a Traladan elder carries quiet resentment, a Glantrian noble carries entitlement and a scroll case. " +
    "The overall mood is optimistic and adventurous with real stakes — a good world to explore, full of secrets but not fundamentally broken.",

  calendar: {
    name: "Mystara (Thyatian Calendar)",
    epochName: "AC",
    defaultYear: 1000,
    weekStyle: "weekly",
    dayLabels: ["Lunadain", "Gromdain", "Tserdain", "Moldain", "Nytdain", "Lorelain", "Soladain"],
    months: [
      { name: "Nuwmont",   alias: "New Month",    days: 28 },
      { name: "Vatermont", alias: "Deep Winter",  days: 28 },
      { name: "Thaumont",  alias: "Early Spring", days: 28 },
      { name: "Flaurmont", alias: "Spring Bloom", days: 28 },
      { name: "Yarthmont", alias: "Late Spring",  days: 28 },
      { name: "Klarmont",  alias: "Early Summer", days: 28 },
      { name: "Felmont",   alias: "High Summer",  days: 28 },
      { name: "Fyrmont",   alias: "Late Summer",  days: 28 },
      { name: "Ambyrmont", alias: "Early Autumn", days: 28 },
      { name: "Sviftmont", alias: "Mid Autumn",   days: 28 },
      { name: "Eirmont",   alias: "Late Autumn",  days: 28 },
      { name: "Kaldmont",  alias: "Deep Winter",  days: 28 },
    ],
    intercalaryDays: [
      { name: "Festival of Thaumont", afterMonth: 2,  description: "A spring festival welcoming the new growing season, celebrated with fairs and the blessing of fields by Thyatian priests." },
      { name: "Midsummer Festival",   afterMonth: 6,  description: "The great summer celebration — jousting, bardic competitions, and the renewal of noble oaths across the Known World." },
      { name: "Harvest Festival",     afterMonth: 9,  description: "A four-day harvest celebration observed throughout the Known World. Trade caravans converge on market cities." },
      { name: "Kaldmont Festival",    afterMonth: 12, description: "The midwinter feast and gift-giving tradition that closes the Thyatian year. Nobles open their halls to the poor; temples offer free meals." },
    ],
    leapYearRule: "none",
  },

  locations: [
    { name: "Mystara",                    location_type: "world",    notes: "A hollow world with an inner sun. The outer surface hosts the Known World; the Hollow World inside preserves lost civilisations.", tags: ["hollow world", "inner sun", "known world"] },
    { name: "Known World",                location_type: "continent",parent: "Mystara",            notes: "The primary continent of Mystara's outer surface — a densely packed collection of rival kingdoms drawing on broad historical cultures.", tags: ["outer surface", "known world", "kingdoms"] },
    { name: "Thyatis Empire",             location_type: "country",  parent: "Known World",        notes: "The dominant empire of the Known World, modelled on ancient Rome. Controls much of the eastern sea.", tags: ["empire", "roman", "military", "senate"] },
    { name: "Thyatis City",               location_type: "city",     parent: "Thyatis Empire",     notes: "The capital of the Thyatian Empire — a grand metropolis of coliseums, forums, and marble temples.", tags: ["capital", "coliseum", "politics", "roman"] },
    { name: "Grand Duchy of Karameikos",  location_type: "country",  parent: "Known World",        notes: "A frontier duchy ruled by Duke Stefan Karameikos. Adventurers find opportunity here; the wilderness is full of dungeons and ruins.", tags: ["frontier", "karameikos", "stefan", "traldar"] },
    { name: "Specularum",                 location_type: "city",     parent: "Grand Duchy of Karameikos", notes: "The capital of Karameikos (later renamed Mirros). A busy port where Thyatian colonists and native Traladarans coexist in uneasy proximity.", tags: ["capital", "port", "traldar", "thyatian"] },
    { name: "Glantri",                    location_type: "country",  parent: "Known World",        notes: "A principality ruled by a Council of Princes — all of whom are wizards. Clerics are outlawed here.", tags: ["wizards", "no clerics", "magic", "princes"] },
    { name: "Glantri City",               location_type: "city",     parent: "Glantri",            notes: "The capital of Glantri — built over magical canals, with a grand Wizard's Tower at its heart.", tags: ["wizards", "canals", "great school", "magic"] },
    { name: "Rockhome",                   location_type: "country",  parent: "Known World",        notes: "The dwarven nation — a heavily fortified mountain kingdom of clan halls, forge-temples, and ancient grudges.", tags: ["dwarves", "mountains", "clans", "smithing"] },
    { name: "Alfheim",                    location_type: "country",  parent: "Known World",        notes: "The elven nation — a forested land of ancient trees and elven clans, protected by the Tree of Life.", tags: ["elves", "forest", "tree of life", "clans"] },
    { name: "Ierendi",                    location_type: "country",  parent: "Known World",        notes: "An island nation south of Karameikos — nominally a monarchy where the rulers are chosen by tournament.", tags: ["islands", "tournament", "trade", "adventurers"] },
    { name: "Darokin",                    location_type: "country",  parent: "Known World",        notes: "A merchant republic with no hereditary nobility — wealth is rank. The Darokin Diplomatic Corps maintains relations with every nation.", tags: ["merchants", "republic", "diplomacy", "wealth"] },
    { name: "The Hollow World",           location_type: "plane",    parent: "Mystara",            notes: "The inner surface of Mystara — a vast continent lit by an inner sun, where the Immortals preserve civilisations erased from the outer world.", tags: ["hollow world", "immortals", "preserved civilizations", "inner sun"] },
  ],

  factions: [
    // Empires and major powers
    { name: "Thyatian Empire",             description: "The dominant power of the Known World, modelled on ancient Rome. The Empire controls sea trade routes, maintains legionary garrisons in client states, and views its former territory of Traladara (now Karameikos) as a noble experiment it may yet need to reclaim.", faction_type: "Government", alignment: "Lawful Neutral", tags: ["empire", "roman", "military", "dominant", "thyatis"] },
    { name: "Alphatian Empire",            description: "The rival empire to Thyatis — a vast, magic-obsessed nation whose ruling class are all wizards. Alphatia considers itself culturally superior to every other nation on Mystara and has the magical firepower to back this claim, which it occasionally demonstrates.", faction_type: "Government", alignment: "Lawful Neutral", tags: ["empire", "wizards", "alphatia", "magic", "rival"] },
    { name: "Glantrian Princes",           description: "The Council of Princes — the ruling body of Glantri, comprising seven archmage nobles each controlling a principality. They agree on almost nothing except that clerics are illegal and magic is supreme, and they argue brilliantly and dangerously about everything else.", faction_type: "Government", alignment: "Chaotic Neutral", tags: ["glantri", "wizards", "princes", "council", "arcane"] },
    // Karameikos factions
    { name: "Order of the Griffon",        description: "The knightly order loyal to Duke Stefan Karameikos — Thyatian veterans and native knights sworn to defend the duchy from monsters, bandits, and political threats. Their loyalty to Stefan is personal, not institutional, which will matter when he is gone.", faction_type: "Order", alignment: "Lawful Good", tags: ["karameikos", "knights", "loyal", "defenders", "stefan"] },
    { name: "Iron Ring",                   description: "A Traladaran criminal organization running a slave trade across the Known World, operating through legitimate merchant fronts and allies in noble houses. They are one of the persistent nightmares of the Karameikos frontier.", faction_type: "Criminal", alignment: "Neutral Evil", tags: ["slavers", "criminal", "traldar", "underworld", "merchant fronts"] },
    { name: "The Veiled Society",          description: "A secret brotherhood of Thyatian nobles in Karameikos who believe the duchy should be returned to direct Thyatian Imperial control. They work through political manipulation, assassination, and economic pressure — and they are patient.", faction_type: "Secret Society", alignment: "Lawful Evil", tags: ["secret", "thyatian", "conspiracy", "nobles", "karameikos"] },
    { name: "The Traladan Clans",          description: "The native people of Traladara, organized into kin-groups with long memories of Thyatian colonization. Some seek accommodation with Duke Stefan; others quietly resist. All remember the three heroes Halav, Petra, and Zirchev, and all wait.", faction_type: "Tribe", alignment: "Chaotic Neutral", tags: ["traldar", "native", "culture", "resistance", "karameikos"] },
    // Diplomatic and merchant powers
    { name: "Darokin Diplomatic Corps",    description: "The professional diplomatic and merchant service of Darokin — a republic of merchants that has no army worth mentioning but extraordinary financial leverage. Darokin maintains embassies everywhere and considers war an inefficiency that better trade deals could have prevented.", faction_type: "Merchant", alignment: "Lawful Neutral", tags: ["darokin", "diplomacy", "merchants", "republic", "trade"] },
    // Racial factions
    { name: "Clan Tordaroch of Rockhome",  description: "The most politically powerful of Rockhome's dwarven clans, controlling the capital Dengar and much of the nation's foreign trade. Clan Tordaroch has dominated dwarven politics for centuries and intends to continue doing so, with or without the other clans' enthusiasm.", faction_type: "Tribe", alignment: "Lawful Neutral", tags: ["dwarves", "rockhome", "clans", "tordaroch", "politics"] },
    { name: "Alfheim Tree Wardens",        description: "The guardian order of Alfheim's elves, sworn to protect the Tree of Life at the heart of the forest — the magical source that sustains all elven clan trees across the nation. They are peaceable until the Tree is threatened, at which point they become extraordinarily dangerous.", faction_type: "Order", alignment: "Neutral Good", tags: ["elves", "alfheim", "tree of life", "guardians", "forest"] },
    { name: "Shadow Elves",               description: "A subterranean elven civilization living in vast cavern cities beneath the Known World — expelled from the surface long ago and changed by their centuries underground. They worship a mysterious entity called the Immortal of Night and have plans for the surface world that surface elves find deeply concerning.", faction_type: "Government", alignment: "Lawful Neutral", tags: ["shadow elves", "underground", "secret", "night immortal", "exile"] },
    // Tournament and island states
    { name: "Ierendi Tournament Court",    description: "The unique ruling institution of the island nation of Ierendi, where the king and queen are selected by annual tournament open to all adventurers. This produces rulers who are competent fighters but not always competent rulers, which keeps the islands lively.", faction_type: "Government", alignment: "Chaotic Neutral", tags: ["ierendi", "tournament", "islands", "adventurers", "monarchy"] },
    // Secret societies
    { name: "Brotherhood of the Radiance", description: "A secret society of Glantrian nobles who have discovered and study the Source of Radiance — a hidden arcane force beneath Glantri that may be connected to the disappearance of clerical magic from the nation. They guard this secret with lethal seriousness.", faction_type: "Secret Society", alignment: "Lawful Neutral", tags: ["glantri", "secret", "radiance", "arcane", "conspiracy"] },
    { name: "Agents of Hule",             description: "The operatives of the Master of Hule — a distant theocratic empire beyond the Known World's western edge. Hulean agents work through mercenary companies, religious cults, and political subversion to destabilize the Known World for eventual conquest.", faction_type: "Secret Society", alignment: "Lawful Evil", tags: ["hule", "master", "agents", "theocracy", "infiltration"] },
  ],

  heroes: [
    {
      name: "Duke Stefan Karameikos",
      race: "Human",
      alignment: "Lawful Good",
      occupation: "Duke / Ruler of Karameikos",
      personality: "Idealistic, honourable, and occasionally naive about the entrenched resentments his colonisation of Traladaran lands has created. Stefan genuinely wants to build a just and prosperous duchy — he is simply doing it on top of someone else's home.",
      backstory: "A Thyatian noble who traded his family lands in Thyatis for the territory of Traladara, which he renamed Karameikos. He imported Thyatian colonists and has been trying ever since to build a unified duchy that respects both Thyatian and Traladan cultures — with mixed results.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["karameikos", "duke", "thyatian", "ruler", "frontier"],
    },
    {
      name: "Aleena",
      race: "Human",
      alignment: "Lawful Good",
      occupation: "Cleric of Halav",
      personality: "Warm, brave, and utterly committed to the wellbeing of those around her. Aleena is the kind of person who runs toward trouble rather than away from it. She has excellent healing spells and a quick laugh.",
      backstory: "A young cleric who adventured alongside a beginning adventurer in the ruins near Threshold. She is patient with newcomers to the adventuring life and has a gift for explaining the basics of dungeon survival without making people feel foolish for not knowing.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["cleric", "halav", "karameikos", "classic", "threshold"],
    },
    {
      name: "Bargle the Infamous",
      race: "Human",
      alignment: "Chaotic Evil",
      occupation: "Wizard / Outlaw",
      personality: "Clever, vain, and utterly convinced that his intellect entitles him to whatever he wants. Bargle is not stupid — he is dangerous. He is also deeply petty and will pursue a grudge long past the point of reason.",
      backstory: "A renegade wizard who operates out of the Caves of Chaos near Threshold. He is responsible for the death of at least one beloved NPC and has evaded justice for years through a combination of cunning and teleportation. He serves a Thyatian noble faction that finds his chaos useful.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["wizard", "outlaw", "karameikos", "villain", "classic"],
    },
    {
      name: "Princess Adriana Karameikos",
      race: "Human",
      alignment: "Neutral Good",
      occupation: "Princess / Adventurer",
      personality: "Sharp, politically aware, and frustrated by the constraints placed on her as a royal woman. Adriana has more military ability than most of her father's knights and is quietly determined to prove it.",
      backstory: "The daughter of Duke Stefan Karameikos, raised between two cultures (Thyatian nobility and Traladan tradition). She secretly admires adventurers and has been known to disguise herself to go on expeditions — a fact that gives the palace guard grey hair.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["karameikos", "princess", "royal", "adventurer"],
    },
    {
      name: "Retameron Antonic",
      race: "Human",
      alignment: "Lawful Good",
      occupation: "Knight / Caravan Guard Captain",
      personality: "Steady, professional, and deeply loyal to those who have earned his trust. Retameron is not exciting. He is dependable in the way that a good sword or a well-built bridge is dependable. In Karameikos, that is worth more than excitement.",
      backstory: "A veteran Thyatian knight who came to Karameikos in Duke Stefan's first wave of colonists. He has since become a respected caravan guard captain and maintains a fighting school in Specularum. He knows every safe road and every dangerous one.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["karameikos", "knight", "thyatian", "veteran", "guard captain"],
    },
    {
      name: "Empress Eriadna",
      race: "Human",
      alignment: "Lawful Neutral",
      occupation: "Empress of Alphatia",
      personality: "Regal, deliberate, and accustomed to being the most powerful person in any room — which in the Alphatian court means the most powerful wizard in any room. She rules an empire of arcane supremacists with the careful authority of someone who must balance genuine power against genuine arrogance.",
      backstory: "The ruler of the Alphatian Empire — the great rival power to Thyatis. Alphatia is a society where wizards are the ruling class, and Eriadna sits at its apex. She has maintained Alphatian superiority through a combination of diplomatic acuity and the implicit threat of the Empire's magical firepower.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["alphatia", "empress", "wizard", "empire", "rival"],
    },
    {
      name: "Emperor Thincol Torion",
      race: "Human",
      alignment: "Lawful Neutral",
      occupation: "Emperor of Thyatis",
      personality: "Blunt, pragmatic, and carrying the specific ego of a man who won the throne in the arena and has never forgotten what that required. Thincol leads with action and tolerates abstraction only when it pays.",
      backstory: "A gladiator who rose through Thyatian politics by winning the right of imperial acclamation in the arena. He now rules the Thyatian Empire with the strategic instincts of a fighter who has survived everything the empire could throw at him — including its nobles.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["thyatis", "emperor", "gladiator", "empire", "ruler"],
    },
    {
      name: "Prince Morphail Gorevitch-Woszlany",
      race: "Vampire",
      alignment: "Lawful Evil",
      occupation: "Vampire Prince of Boldavia / Glantrian Noble",
      personality: "Old-world courtly manner over something very cold and very patient. Morphail has survived Glantrian politics for centuries by being exactly as treacherous as everyone expects and slightly more capable than anyone accounts for.",
      backstory: "The vampire Prince of Boldavia and one of Glantri's most powerful nobles. He is an open secret — everyone knows what he is; no one can prove it to the legal standards of the Glantrian courts, which is exactly as he has arranged it. He rules his principality through fear and political manoeuvre in equal measure.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["glantri", "vampire", "boldavia", "noble", "villain"],
    },
    {
      name: "Rad (Etienne d'Ambreville)",
      race: "Human (Immortal)",
      alignment: "Lawful Neutral",
      occupation: "Immortal / Patron of Glantri",
      personality: "Distant, benevolent in a hands-off way, and operating on a timeline that makes most conversations feel slightly pointless. Rad watches over Glantri without intervening directly — which is precisely what his Immortal status requires and precisely what his former subjects find frustrating.",
      backstory: "Once the archmage Etienne d'Ambreville, head of Glantri's most powerful noble family, who achieved Immortality and now serves as Rad — the Immortal patron of magic in the Glantrian calendar. His relationship with Glantri's current rulers is complicated by the fact that he cannot interfere directly.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["glantri", "immortal", "archmage", "d'ambreville", "patron"],
    },
    {
      name: "Jaggar von Drachenfels",
      race: "Human",
      alignment: "Lawful Neutral",
      occupation: "Prince of Aalban / War-Wizard",
      personality: "Militaristic, technically brilliant, and possessing the specific competence of a wizard who has also studied military engineering. Von Drachenfels is not a schemer — he is a strategist, which is different. He solves problems with force and precision rather than politics.",
      backstory: "One of Glantri's most powerful princes and its foremost military wizard. He rules Aalban with an iron hand and is responsible for much of Glantri's conventional military capability. His expertise in siege magic and battlefield enchantment makes him invaluable — and politically dangerous because he cannot be easily outmanoeuvred.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["glantri", "prince", "war wizard", "military", "aalban"],
    },
    {
      name: "Brannart McGregor",
      race: "Human (Lich)",
      alignment: "Neutral Evil",
      occupation: "Lich-Prince of Klantyre / Glantrian Noble",
      personality: "Caustic, intellectually proud, and genuinely not concerned with the social discomfort his undead status creates for others. Brannart achieved lichdom as a scholarly experiment and considers the political complications a minor inconvenience.",
      backstory: "The undead prince of Klantyre in Glantri — a lich who holds noble rank and a seat on the Council of Princes. His lichdom is technically illegal under Glantrian law but he has the power to make enforcement unpleasant, and the other princes have pragmatically chosen to look elsewhere.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["glantri", "lich", "klantyre", "noble", "undead"],
    },
    {
      name: "The Master of Hule",
      race: "Human",
      alignment: "Lawful Evil",
      occupation: "Theocratic Dictator of Hule",
      personality: "Patient, dogmatic, and operating a long-horizon infiltration of the Known World that most of its targets haven't noticed yet. The Master presents a face of religious reasonableness while deploying agents, mercenaries, and religious subversion in every neighbouring nation.",
      backstory: "The ruler of Hule, a theocratic empire beyond the Known World's western edge. He pursues the conquest and religious conversion of the Known World through proxy wars, cultural infiltration, and occasional direct military pressure when the opportunity arises. He has been doing this longer than most of his opponents have been alive.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["hule", "master", "theocracy", "villain", "distant"],
    },
    {
      name: "Thar",
      race: "Orc",
      alignment: "Chaotic Evil",
      occupation: "Orc King",
      personality: "Brutal, ambitious, and possessed of enough strategic intelligence to make him genuinely dangerous. Thar is not merely a raider — he wants to build something. Exactly what is unclear, but the process involves a lot of destruction of everything that currently exists.",
      backstory: "The self-styled king of the various orc and goblinoid tribes in the region north of Karameikos. He has united more humanoid tribes than anyone expected and leads periodic massive raids against the Known World's northern borders. The difference between Thar and previous orc warlords is that Thar thinks ahead.",
      status: "alive",
      relationship: "enemy",
      portrait_url: null,
      tags: ["orc", "warlord", "king", "humanoid", "villain"],
    },
  ],
};
