import type { DndSettingDef } from "./types";

export const planescapeSetting: DndSettingDef = {
  id: "planescape",
  label: "Planescape",

  defaultAiPrompt:
    "Strange, layered, cosmopolitan fantasy where nothing is normal and everything has a philosophy behind it. Sigil's palette is smoked stone, faction colours, portal-shimmer, and the glow of a thousand exotic light sources — no two blocks look the same. " +
    "Characters are radically diverse: tieflings with every horn shape imaginable, githzerai in wrapped linen and discipline, bariaur, modrons on errands, a dabus floating silently past trailing rebuses. Faction insignia should be visible and meaningful. " +
    "Architecture is impossible gothic — buttresses that support nothing, stairs that change direction mid-flight, buildings that share a wall with a portal to Mechanus. Everything has been repaired, modified, and graffitied by a thousand tenants. " +
    "The planes bleed through: the floor near an Abyss portal smells of sulphur and feels slightly wrong underfoot; a Celestia-aligned district has cleaner air and uncomfortably earnest locals. Use these details. " +
    "Portals should be visually distinct — not generic glowing circles but unique: a particular door at a particular angle, a specific window at noon, a crack in a certain wall. " +
    "Creatures from lower planes should feel genuinely malevolent and alien; upper-plane beings should feel uncomfortably perfect. Yugoloths look like they're calculating the cost of your soul. " +
    "Keep the mood weird, street-level, and philosophically loaded — even a simple alley has an argument happening in it.",

  calendar: {
    name: "Planescape (Planar Common Reckoning)",
    epochName: "PCR",
    defaultYear: 570,
    weekStyle: "weekly",
    dayLabels: ["Prime", "Bleaker", "Guvner", "Cipher", "Signer", "Sensate", "Deadday"],
    months: [
      { name: "Primum",     alias: "The Opening",     days: 30 },
      { name: "Internum",   alias: "The Seeking",     days: 30 },
      { name: "Tertium",    alias: "The Debating",    days: 30 },
      { name: "Quartum",    alias: "The Arguing",     days: 30 },
      { name: "Quintum",    alias: "The Reckoning",   days: 30 },
      { name: "Sextum",     alias: "The Convergence", days: 30 },
      { name: "Septimum",   alias: "The Midtide",     days: 30 },
      { name: "Octavum",    alias: "The Wandering",   days: 30 },
      { name: "Nonum",      alias: "The Returning",   days: 30 },
      { name: "Decimum",    alias: "The Closing",     days: 30 },
      { name: "Undecimum",  alias: "The Silence",     days: 30 },
      { name: "Duodecimum", alias: "The Reckoning",   days: 30 },
    ],
    intercalaryDays: [
      { name: "Day of Factions",   afterMonth: 3,  description: "A day when the great factions of Sigil hold open debates in the Hall of Speakers. Recruitment is aggressive; newcomers are wise to choose a side." },
      { name: "Great Bazaar Day",  afterMonth: 6,  description: "A planar market day when portals to every known trading plane cycle open in the Great Bazaar. The most exotic goods in the multiverse change hands." },
      { name: "Day of the Lady",   afterMonth: 9,  description: "A day of enforced quiet in Sigil. No faction meetings. No public violence. The Lady of Pain's dabus scrub the streets. No one asks why." },
      { name: "Convergence",       afterMonth: 12, description: "The year's end festival, when planar travellers across the multiverse gather debts, settle old scores, and begin new ventures." },
    ],
    leapYearRule: "none",
  },

  locations: [
    { name: "The Outlands",      location_type: "plane",    notes: "The Great Wheel's hub — a ring-shaped outer plane of perfect neutral balance, with the Spire rising from its centre.", tags: ["outer planes", "true neutral", "the spire"] },
    { name: "Sigil",             location_type: "city",     parent: "The Outlands",   notes: "The City of Doors — a torus-shaped city atop the Spire, accessible from any plane via portals. Governed by the Lady of Pain.", tags: ["city of doors", "lady of pain", "portals", "factions"] },
    { name: "The Great Bazaar",  location_type: "district", parent: "Sigil",          notes: "Sigil's largest market, where merchants from across the multiverse buy and sell everything from spell components to bottled demons.", tags: ["market", "trade", "merchants"] },
    { name: "The Cage",          location_type: "district", parent: "Sigil",          notes: "Street slang for Sigil itself — the city that traps even gods. No deity can enter; the Lady keeps them out.", tags: ["sigil", "slang", "no gods"] },
    { name: "The Spire",         location_type: "wilderness",parent: "The Outlands",  notes: "An impossibly tall pillar rising from the centre of the Outlands, atop which sits Sigil. Magic weakens the closer one climbs.", tags: ["spire", "antimagic", "outlands"] },
    { name: "Tradegate",         location_type: "city",     parent: "The Outlands",   notes: "A gate-town to Mechanus, known for its honest merchants and the Great Wheel trading guilds headquartered here.", tags: ["gate-town", "mechanus", "trade"] },
    { name: "Plague-Mort",       location_type: "town",     parent: "The Outlands",   notes: "The gate-town to the Abyss — a chaotic, violent settlement constantly on the verge of being pulled into the lower planes.", tags: ["gate-town", "abyss", "chaotic evil"] },
    { name: "Ribcage",           location_type: "city",     parent: "The Outlands",   notes: "The gate-town to Baator (Nine Hells) — a heavily fortified city-state ruled by iron-fisted lawful-evil overlords.", tags: ["gate-town", "nine hells", "lawful evil"] },
    // Transitive planes
    { name: "The Astral Plane",   location_type: "plane",   notes: "A silvery void connecting all planes. Home to githyanki silver cities and the drifting god-isles of long-dead deities.", tags: ["transitive", "astral", "githyanki"] },
    { name: "The Ethereal Plane", location_type: "plane",   notes: "A misty borderland coexisting with the Material Plane, used by ghosts and travelers passing between inner and outer planes.", tags: ["transitive", "ethereal", "ghosts"] },
    { name: "The Feywild",        location_type: "plane",   notes: "The Plane of Faerie — a mirror of the Material Plane suffused with wild magic, beauty, and danger. Home to the Seelie and Unseelie Courts.", tags: ["feywild", "fey", "archfey", "seelie", "unseelie"] },
    { name: "The Shadowfell",     location_type: "plane",   notes: "The Plane of Shadow — a dark reflection of the Material Plane where all colour drains to grey.", tags: ["shadowfell", "shadow", "raven queen", "shadar-kai"] },
    // Inner planes
    { name: "Elemental Plane of Fire",  location_type: "plane", notes: "A plane of endless conflagration, home to the City of Brass and the efreeti sultans.", tags: ["inner planes", "fire", "efreeti", "city of brass"] },
    { name: "Elemental Plane of Water", location_type: "plane", notes: "A boundless ocean with no surface, home to marids and the coral cities of the Elemental Court of Water.", tags: ["inner planes", "water", "marids"] },
    { name: "Elemental Plane of Earth", location_type: "plane", notes: "An infinite mass of rock and crystal tunnels. Home to dao, xorn, and vast underground kingdoms.", tags: ["inner planes", "earth", "dao"] },
    { name: "Elemental Plane of Air",   location_type: "plane", notes: "A limitless sky with no ground, home to djinn, aarakocra, and the floating cities of the djinn sultans.", tags: ["inner planes", "air", "djinn", "aarakocra"] },
    // Outer planes — upper
    { name: "Mount Celestia",  location_type: "plane", notes: "The Seven Heavens — a shining plane of absolute law and good, home to archons and the souls of the most virtuous.", tags: ["upper planes", "lawful good", "archons"] },
    { name: "Arborea",         location_type: "plane", notes: "The Olympian Glades — a chaotic good plane of wild beauty and passion. Home to elven gods and their divine servants.", tags: ["upper planes", "chaotic good", "elves"] },
    { name: "Elysium",         location_type: "plane", notes: "A neutral good plane of perfect peace and rest. Home of departed good souls and the birthplace of guardinals.", tags: ["upper planes", "neutral good", "guardinals"] },
    { name: "Ysgard",          location_type: "plane", notes: "The Heroic Domains — a plane of eternal battle and glory, home to Norse-inspired gods, giants, and the honored slain.", tags: ["upper planes", "chaotic good", "giants", "norse"] },
    // Outer planes — lower
    { name: "The Nine Hells",  location_type: "plane", notes: "Baator — nine layers of lawful evil dominated by archdevils. Avernus down through Nessus (Asmodeus).", tags: ["lower planes", "lawful evil", "devils", "asmodeus"] },
    { name: "Avernus",         location_type: "plane", parent: "The Nine Hells", notes: "The first layer of the Nine Hells, ruled by Zariel. A blasted hellscape of endless war between demons and devils.", tags: ["nine hells", "zariel", "devils", "war"] },
    { name: "The Abyss",       location_type: "plane", notes: "An infinite layered plane of pure chaos and evil, home to the tanar'ri demons. Each layer is a different demon lord's domain.", tags: ["lower planes", "chaotic evil", "demons", "tanar'ri"] },
    { name: "Gehenna",         location_type: "plane", notes: "The Bleak Eternity — a plane of volcanic mountainsides, where yugoloths sell their services to both sides of the Blood War.", tags: ["lower planes", "neutral evil", "yugoloths"] },
    { name: "Hades",           location_type: "plane", notes: "The Gray Waste — three bleak grey layers where all emotion drains away. Home to larvae.", tags: ["lower planes", "neutral evil", "gray waste"] },
    { name: "Mechanus",        location_type: "plane", notes: "Infinite interlocking clockwork gears — a plane of absolute law and order, ruled by modrons and the god Primus.", tags: ["outer planes", "lawful neutral", "modrons", "clockwork"] },
    { name: "Limbo",           location_type: "plane", notes: "The Ever-Changing Chaos — a roiling soup of unformed matter that slaadi and githzerai monks shape by willpower alone.", tags: ["outer planes", "chaotic neutral", "slaadi", "githzerai"] },
  ],

  factions: [
    // The Fifteen Factions of Sigil
    { name: "Athar",                  description: "The Lost — they have discovered that the gods are merely powerful beings, not true divinities, and worship of them is a con. They gather in a ruined temple and proselytize loudly, which has made them unpopular with every faith in Sigil.", faction_type: "Other", alignment: "Chaotic Neutral", tags: ["atheism", "anti-gods", "philosophy", "sigil"] },
    { name: "Believers of the Source", description: "The Godsmen — they believe every creature has the potential to become a god through sufficient trial and growth. Mortality is a testing ground; failure means another life, another chance. They run Sigil's foundries and forges.", faction_type: "Religion", alignment: "True Neutral", tags: ["self-improvement", "godhood", "reincarnation", "sigil", "foundries"] },
    { name: "Bleak Cabal",            description: "The Bleakers — they have looked into the void and concluded there is no cosmic meaning. Rather than despair, they run Sigil's hospitals and madhouses. Someone has to care for those the multiverse has broken.", faction_type: "Other", alignment: "Chaotic Neutral", tags: ["nihilism", "charity", "asylums", "sigil"] },
    { name: "Doomguard",              description: "The Sinkers — they believe entropy is the natural and correct end of all things. They maintain Sigil's weapon shops and argue constantly about whether to accelerate the multiverse's collapse or simply let it happen on schedule.", faction_type: "Other", alignment: "Chaotic Neutral", tags: ["entropy", "decay", "weapons", "sigil", "nihilism"] },
    { name: "Dustmen",                description: "The Dead — they believe true existence ended long ago and all living beings are merely undead who haven't accepted it yet. They run Sigil's mortuary and are surprisingly pleasant, if you can get past the theology.", faction_type: "Other", alignment: "True Neutral", tags: ["undead", "death", "philosophy", "mortuary", "sigil"] },
    { name: "Fated",                  description: "The Takers — they believe the multiverse owes nothing to anyone and everything belongs to whoever can take and hold it. They run Sigil's Hall of Records and tax collection, which suits them philosophically.", faction_type: "Other", alignment: "Chaotic Neutral", tags: ["power", "self-reliance", "wealth", "records", "sigil"] },
    { name: "Fraternity of Order",    description: "The Guvners — they believe the multiverse runs on laws, and if you know enough laws precisely enough, you can bend any of them. They run Sigil's courts and produce more loopholes than any other faction.", faction_type: "Other", alignment: "Lawful Neutral", tags: ["law", "knowledge", "courts", "lawyers", "sigil"] },
    { name: "Free League",            description: "The Indeps — the faction that refuses factions. They believe in individual freedom and distrust all organizations, which makes being an organized faction philosophically complicated. They dominate the Great Bazaar.", faction_type: "Merchant", alignment: "Chaotic Neutral", tags: ["freedom", "independence", "merchants", "great bazaar", "sigil"] },
    { name: "Harmonium",              description: "The Hardheads — Sigil's primary law enforcement and the faction that believes true peace comes when everyone agrees on one right way to live. They are very good at making people agree, by persuasion first and baton second.", faction_type: "Government", alignment: "Lawful Neutral", tags: ["law", "enforcement", "peace", "lawful", "sigil"] },
    { name: "Mercykillers",           description: "The Red Death — they believe in perfect justice: every crime has a punishment, every punishment must be carried out completely. They operate Sigil's prison and pursue fugitives across the planes with cold dedication.", faction_type: "Other", alignment: "Lawful Neutral", tags: ["justice", "punishment", "prison", "lawful", "sigil"] },
    { name: "Revolutionary League",   description: "The Anarchists — they want to tear down every power structure in the multiverse, starting with the other fourteen factions. They have no known headquarters, no public members, and are theoretically impossible to identify — which is the point.", faction_type: "Secret Society", alignment: "Chaotic Neutral", tags: ["anarchy", "revolution", "secret", "chaotic", "sigil"] },
    { name: "Sign of One",            description: "The Signers — they believe the individual mind is the centre of the multiverse, possibly literally; if one of them imagines something hard enough, it might become real. They run Sigil's Hall of Speakers and debate endlessly.", faction_type: "Other", alignment: "Chaotic Neutral", tags: ["individualism", "solipsism", "creativity", "hall of speakers", "sigil"] },
    { name: "Society of Sensation",   description: "The Sensates — they believe knowledge can only come through direct experience. They seek every sensation, every experience, every pleasure and pain, and record it in a vast memory-palace that can be shared. They run the best taverns in Sigil.", faction_type: "Guild", alignment: "Chaotic Neutral", tags: ["sensation", "experience", "hedonism", "taverns", "sigil"] },
    { name: "Transcendent Order",     description: "The Ciphers — they believe thought and action should be one. The time you spend deciding is time you spend not doing. They train until the body acts without the mind's interference, achieving a form of pure instinct that looks like enlightenment.", faction_type: "Order", alignment: "True Neutral", tags: ["action", "martial", "enlightenment", "instinct", "sigil"] },
    { name: "Xaositects",             description: "The Chaosmen — true believers in absolute chaos as the natural state of the multiverse. Their meetings are cacophonous, their decisions random, their arguments conducted in scrambled sentence order. They are genuinely dangerous to be near.", faction_type: "Other", alignment: "Chaotic Neutral", tags: ["chaos", "random", "chaotic neutral", "dangerous", "sigil"] },
    // Major planar factions beyond Sigil
    { name: "The Rilmani",            description: "The native inhabitants of the Outlands — humanoid creatures of absolute true neutrality who intervene across the planes to prevent any alignment from gaining too much power. They are not friends of anyone; they are the multiverse's immune system.", faction_type: "Other", alignment: "True Neutral", tags: ["neutral", "outlands", "balance", "planar", "ancient"] },
    { name: "The Modrons",            description: "The inhabitants of Mechanus — perfect geometric constructs arranged in an absolute hierarchy from Monodrone to the singular Primus. They conduct a Great March across the planes every 17 years for reasons they are incapable of explaining to non-modrons.", faction_type: "Other", alignment: "Lawful Neutral", tags: ["modrons", "mechanus", "law", "clockwork", "hierarchy"] },
    { name: "The Githyanki",          description: "Psionic warriors who live in silver citadels on the Astral Plane, serving their lich-queen Vlaakith. They were once slaves of the mind flayers; they are now one of the most dangerous military forces between planes, and they hate illithids beyond all reason.", faction_type: "Military", alignment: "Lawful Evil", tags: ["githyanki", "astral plane", "psionic", "military", "silver swords"] },
    { name: "The Githzerai",          description: "The other half of the gith people — monastic psionic warriors who chose Limbo's chaos over the Astral Plane's rigidity. Their monks shape Limbo by willpower alone, maintaining islands of calm in infinite chaos. They hate githyanki as much as they hate illithids.", faction_type: "Order", alignment: "Chaotic Neutral", tags: ["githzerai", "limbo", "psionic", "monks", "chaos"] },
  ],

  heroes: [
    {
      name: "The Lady of Pain",
      race: "Unknown",
      alignment: "True Neutral",
      occupation: "Ruler of Sigil",
      personality: "The Lady does not speak. She floats silently through Sigil's streets on her dabus. Those who displease her are mazed — imprisoned in a pocket dimension — or flayed alive where they stand. Her motivations are completely unknowable. Do not pray to her. Do not make eye contact.",
      backstory: "The absolute ruler of Sigil and the most powerful entity in the city. She keeps all gods out of Sigil and maintains the city's neutrality through sheer terror. Her origins are unknown. Her purpose is unknown. She has existed for as long as Sigil itself.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["sigil", "ruler", "mysterious", "unknowable", "dabus"],
    },
    {
      name: "Fall-from-Grace",
      race: "Tiefling (Succubus)",
      alignment: "Neutral Good",
      occupation: "Proprietor of the Brothel for Slaking Intellectual Lusts",
      personality: "Serene, philosophical, and possessing a rare quality in Sigil — genuine kindness. Grace has renounced her fiendish nature and found that wisdom and compassion are more interesting than temptation. She is soft-spoken and absolutely deadly in combat.",
      backstory: "A succubus who rejected the Abyss and took paladin vows — or something close to them. She runs an establishment in Sigil dedicated to satisfying the mind rather than the body. She is a member of the Society of Sensation and a genuine moral force in the city.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["sigil", "succubus", "paladin", "sensates", "tiefling"],
    },
    {
      name: "Shemeshka the Marauder",
      race: "Arcanaloth",
      alignment: "Neutral Evil",
      occupation: "Information Broker / Crime Lord",
      personality: "Theatrical, vain, and extraordinarily dangerous. Shemeshka presents herself as a gracious and sophisticated merchant of secrets — which she is — while concealing a predator's patience and a yugoloth's utter lack of conscience. She knows everyone's price.",
      backstory: "The most powerful information broker in Sigil, Shemeshka has her fingers in every pie and her claws around every throat. She is old, rich, and paranoid in equal measure. Dealing with her is profitable and extremely risky.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["sigil", "arcanaloth", "information broker", "yugoloth", "villain"],
    },
    {
      name: "Factol Rhys of the Transcendent Order",
      race: "Human (Tiefling heritage)",
      alignment: "True Neutral",
      occupation: "Factol of the Transcendent Order (Ciphers)",
      personality: "Swift, decisive, and utterly present — Rhys embodies the Cipher philosophy that thought and action are one. She rarely explains her decisions because her body has already made them. She is not unkind; she simply doesn't have time for hesitation.",
      backstory: "The leader of the Transcendent Order — Ciphers — who believe that acting without thought is the highest form of consciousness. Rhys reached this enlightenment through decades of rigorous training. She remains one of the deadliest fighters in Sigil.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["sigil", "ciphers", "transcendent order", "factol", "martial"],
    },
    {
      name: "Morte",
      race: "Undead (Floating Skull)",
      alignment: "Chaotic Neutral",
      occupation: "Companion / Insult Artist",
      personality: "Wisecracking, cowardly, fiercely loyal, and possessed of an extraordinary vocabulary of barbs. Morte pretends everything is a joke because admitting anything matters is more frightening than the Abyss.",
      backstory: "A floating talking skull of unknown origin who has served as a companion to countless amnesiac travellers through the planes. His true history is darker than his patter suggests. He knows more than he lets on — about everything.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["sigil", "skull", "companion", "undead", "nameless one"],
    },
    {
      name: "The Nameless One",
      race: "Human (Immortal)",
      alignment: "Unknown",
      occupation: "Amnesiac Immortal / Seeker",
      personality: "Every incarnation is different — the Nameless One's personality shifts with each death and resurrection. The current version is curious, haunted by scars he cannot explain, and driven by a question he cannot quite remember formulating: what can change the nature of a man?",
      backstory: "An immortal being who has died and been reborn so many times that his identity has fractured across his incarnations. Each rebirth costs him his memories. He wanders Sigil and the planes trying to piece together who he was, who he is, and what it would mean to finally die. His story is the central tragedy of the Planescape setting.",
      status: "alive",
      relationship: "ally",
      portrait_url: null,
      tags: ["sigil", "immortal", "amnesiac", "nameless one", "torment"],
    },
    {
      name: "Factol Sarin",
      race: "Human",
      alignment: "Lawful Neutral",
      occupation: "Factol of the Harmonium",
      personality: "Earnest, idealistic, and convinced that peace is achievable if everyone would simply agree on the correct approach. Sarin is not stupid — he is genuinely persuasive, and the fact that his philosophy curdles into authoritarianism at scale is a thing he is working very hard not to notice.",
      backstory: "The current leader of the Harmonium — Sigil's primary law enforcement faction, who believe universal peace is achievable when everyone agrees with them. Sarin is a true believer rather than a cynical power-seeker, which in some ways makes him more dangerous.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["sigil", "harmonium", "hardheads", "factol", "lawful"],
    },
    {
      name: "Factol Skall",
      race: "Undead (Wight)",
      alignment: "True Neutral",
      occupation: "Factol of the Dustmen",
      personality: "Quiet, measured, and possessed of the infinite patience of the already-dead. Skall does not argue — he waits. He has found something most find disturbing: genuine contentment. The Dead philosophy says life as we know it is the aberration, and Skall has stopped finding this sad.",
      backstory: "The undead leader of the Dustmen — the faction that believes all living beings are undead who haven't accepted it yet. Skall runs Sigil's Mortuary with quiet efficiency and advocates for the Dead philosophy with the serene certainty of someone who has personally crossed the threshold and found it agreeable.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["sigil", "dustmen", "undead", "factol", "mortuary"],
    },
    {
      name: "Duke Rowan Darkwood",
      race: "Human",
      alignment: "Chaotic Neutral",
      occupation: "Factol of the Fated",
      personality: "Supremely self-assured, ambitious, and operating under the sincere conviction that the multiverse's resources belong to whoever can claim them. Darkwood is charming when that serves him and ruthless when charm runs out. He considers this intellectual consistency.",
      backstory: "The factol of the Fated — the Takers — who control Sigil's Hall of Records and tax collection. Darkwood rose to the top through a combination of political brilliance and the willingness to use every advantage available to him. He views anyone who criticises this as someone who hasn't won yet.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["sigil", "fated", "takers", "factol", "ambitious"],
    },
    {
      name: "Lothar the Old",
      race: "Human (Lich-like)",
      alignment: "True Neutral",
      occupation: "Master of Bones / Skull Keeper",
      personality: "Ancient, calm, and operating in a register of time that makes normal conversation feel slightly rushed. Lothar collects skulls of the notable dead and can converse with them. He is not threatening exactly, but his hobby is unsettling and his knowledge is extraordinary.",
      backstory: "An ancient man who operates the City of Skulls — a collection of skulls of the famous dead preserved in Sigil's lower wards. He can speak with any skull in his collection, making him one of the most remarkable information resources in the planes. His own nature is uncertain; he has been here longer than most recall.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["sigil", "skulls", "lore keeper", "undead", "ancient"],
    },
    {
      name: "Alluvius Ruskin",
      race: "Tiefling",
      alignment: "True Neutral",
      occupation: "Information Broker / Lens Merchant",
      personality: "Cheerfully mercantile and utterly without sentiment about the information trade. Alluvius sells what she has to whoever can pay, and she considers this a public service. She is not dishonest — she simply does not volunteer information that wasn't purchased.",
      backstory: "A tiefling who runs a lens and optical goods shop in Sigil as cover for an extensive information brokerage. She competes with Shemeshka in the information trade but specializes in a different tier of client — useful intelligence for people who can't afford an arcanaloth.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["sigil", "information broker", "tiefling", "merchant", "lens shop"],
    },
    {
      name: "Zadara the Titan",
      race: "Titan",
      alignment: "Chaotic Good",
      occupation: "Planar Traveller / Titan Warrior",
      personality: "Enormous in personality as in body — Zadara is passionate, protective of those she considers under her wing, and completely indifferent to the factional politics that consume smaller beings. She has her own agenda, which operates on a scale most find difficult to track.",
      backstory: "A titan who travels the planes and has established a presence in the Outlands. She is not a Sigil native but visits frequently and has alliances across several factions. Her true purposes are her own, but she has helped travellers who impressed her and harmed those who insulted her in about equal measure.",
      status: "alive",
      relationship: "neutral",
      portrait_url: null,
      tags: ["titan", "outlands", "planar traveller", "powerful", "chaotic good"],
    },
  ],
};
