import type { DndSettingDef } from "./types";

export const ravenloftSetting: DndSettingDef = {
  id: "ravenloft",
  label: "Ravenloft",

  defaultAiPrompt:
    "Gothic horror with a desaturated, fog-drenched palette — bone white, slate grey, deep shadow black, and crimson used sparingly and with intent. Candlelight and firelight should feel inadequate against the dark. " +
    "The Mists are always present: at treeline, between buildings, curling under doors. Let them obscure as much as they reveal. " +
    "Architecture is crumbling grandeur — castle stone slick with damp, iron gates rusted open or shut, manor houses with boards on the upper windows, graveyards with tilted stones and fresh turned earth. " +
    "Characters should look haunted: sunken eyes, tattered finery over survival practicality, religious symbols clutched or hidden, faces that have seen too much. Show fear as the reasonable response. " +
    "Creatures should feel wrong — vampires are beautiful and repellent at once, werewolves are mid-transformation agony, ghosts are the shape of grief given form. Anatomy should disturb without being gratuitous. " +
    "Use environmental horror: the torch that keeps almost going out, the dog that won't stop barking, the wagon wheel stuck in mud at the worst moment, the window with something behind it. " +
    "Keep the mood oppressive, dread-soaked, and intimate — the horror is personal, not spectacle.",

  calendar: {
    name: "Ravenloft (Barovian Calendar)",
    epochName: "BC",
    defaultYear: 735,
    weekStyle: "weekly",
    dayLabels: ["Moonday", "Grimday", "Ashenday", "Bleakday", "Dreadday", "Wailday", "Darkday"],
    months: [
      { name: "Deadwinter",  alias: "The Long Dark",  days: 30 },
      { name: "Witchblight", alias: "The Rime",        days: 30 },
      { name: "Thawing",     alias: "False Spring",    days: 30 },
      { name: "Bloodrose",   alias: "Blooming",        days: 30 },
      { name: "Mourning",    alias: "The Weeping",     days: 30 },
      { name: "Mistmonth",   alias: "High Summer",     days: 30 },
      { name: "Swelter",     alias: "The Fever",       days: 30 },
      { name: "Duskfall",    alias: "The Turning",     days: 30 },
      { name: "Darkening",   alias: "The Long Dusk",   days: 30 },
      { name: "Harvestwane", alias: "Last Harvest",    days: 30 },
      { name: "Grimtide",    alias: "The Reckoning",   days: 30 },
      { name: "Deepmist",    alias: "The Vanishing",   days: 30 },
    ],
    intercalaryDays: [
      {
        name: "Mistsday",
        afterMonth: 6,
        description: "The longest night of summer. The Mists draw close and the boundary between life and death blurs. Darklords are said to be at their most powerful.",
      },
      {
        name: "Night of the Walking Dead",
        afterMonth: 12,
        description: "The most dreaded night in Ravenloft — the dead rise from their graves and the Mists swallow entire villages. No one ventures out alone.",
      },
    ],
    leapYearRule: "none",
  },

  locations: [
    { name: "The Mists",              location_type: "plane",   notes: "The supernatural fog that surrounds and separates the Domains of Dread. Travellers who enter without invitation rarely find their way out.", tags: ["mists", "demiplane", "prison"] },
    { name: "Demiplane of Dread",     location_type: "plane",   parent: "The Mists",           notes: "The patchwork pocket dimension created by the Dark Powers — a collection of domains, each a perfect prison for its Darklord.", tags: ["dark powers", "prison plane", "domains"] },
    { name: "Barovia",                location_type: "region",  parent: "Demiplane of Dread",  notes: "The oldest and most famous Domain of Dread. A gloomy valley of superstitious villages, dark forests, and Castle Ravenloft. Darklord: Strahd von Zarovich.", tags: ["strahd", "curse of strahd", "gothic", "vampires"] },
    { name: "Castle Ravenloft",       location_type: "dungeon", parent: "Barovia",             notes: "The ancestral home of Strahd von Zarovich, perched on a basalt crag above the village of Barovia. A maze of crypts, towers, and dark magic.", tags: ["strahd", "castle", "dungeon", "vampires"] },
    { name: "Village of Barovia",     location_type: "village", parent: "Barovia",             notes: "A desolate, fog-choked village of frightened peasants, cowering beneath Castle Ravenloft's shadow.", tags: ["strahd", "ireena", "ismark"] },
    { name: "Vallaki",                location_type: "town",    parent: "Barovia",             notes: "A walled town ruled by Baron Vargas Vallakovich, who forces citizens to attend mandatory 'festivals' to maintain an illusion of happiness.", tags: ["vallakovich", "festivals", "walled town"] },
    { name: "Krezk",                  location_type: "town",    parent: "Barovia",             notes: "A small fortified village at the edge of Barovia, ruled by the Krezkov family. Its holy pool is said to grant visions.", tags: ["krezkov", "holy pool", "abbey"] },
    { name: "Darkon",                 location_type: "region",  parent: "Demiplane of Dread",  notes: "Once one of the largest domains in the Demiplane, ruled by the lich Azalin Rex. Its capital became the Necropolis — a city of the undead.", tags: ["azalin rex", "lich", "necropolis", "undead"] },
    { name: "Necropolis of Il Aluk",  location_type: "city",    parent: "Darkon",              notes: "Once a living city, now populated entirely by the undead after Azalin's ill-fated ritual.", tags: ["undead", "azalin rex", "city of death"] },
    { name: "Falkovnia",              location_type: "region",  parent: "Demiplane of Dread",  notes: "A militaristic, tyrannical domain ruled by the brutal warlord Vlad Drakov. Citizens live in constant fear.", tags: ["vlad drakov", "military", "tyranny"] },
    { name: "Lamordia",               location_type: "region",  parent: "Demiplane of Dread",  notes: "A cold, industrialised domain of gothic science-horror. Darklord: Dr. Viktra Mordenheim, creator of the Flesh Golem Adam.", tags: ["mordenheim", "flesh golem", "gothic science", "cold"] },
    { name: "Mordent",                location_type: "region",  parent: "Demiplane of Dread",  notes: "A fog-drenched coastal domain of haunted manor houses and restless spirits.", tags: ["ghosts", "haunted", "fog", "manor houses"] },
    { name: "Borca",                  location_type: "region",  parent: "Demiplane of Dread",  notes: "A wealthy domain of political intrigue and poison. Darklords: siblings Ivana Boritsi and Ivan Dilisnya.", tags: ["poison", "intrigue", "boritsi", "wealth"] },
    { name: "The Shadowfell",         location_type: "plane",   notes: "The Plane of Shadow — a dark reflection of the Material Plane. Many Domains of Dread are believed to float in or near the Shadowfell.", tags: ["shadowfell", "shadow", "raven queen"] },
  ],

  factions: [
    { name: "The Vistani",                 description: "Wandering clans of fortune-tellers and travellers with unique immunity to the Mists. They can navigate between Domains freely — a power that makes them indispensable, deeply suspect, and occasionally serving agendas far older than any Darklord.", faction_type: "Tribe", alignment: "True Neutral", tags: ["wanderers", "mists", "fortune-tellers", "immunity"] },
    { name: "Church of Ezra",              description: "The dominant religion of the Demiplane — a faith of stoic endurance centred on the deity Ezra, the God in the Mist. Four sects disagree on doctrine while all agree on the core: the world is dark, endure it, protect the flock.", faction_type: "Religion", alignment: "Lawful Neutral", tags: ["religion", "protection", "demiplane", "stoic"] },
    { name: "Van Richten's Society",       description: "A loose network of monster hunters, scholars, and survivors inspired by Rudolph van Richten's published Guides. They share intelligence and safe houses across domains, united by the goal of understanding and destroying the horrors that prey on the living.", faction_type: "Secret Society", alignment: "Neutral Good", tags: ["monster hunters", "scholars", "resistance", "van richten"] },
    { name: "Barovian Militia",            description: "The rough fighters who defend Barovia's villages with pitchforks, torches, and desperation. Not organized enough to be an army, too frightened to be heroes — but sometimes both, when cornered.", faction_type: "Military", alignment: "Neutral Good", tags: ["barovia", "villagers", "defense", "desperate"] },
    { name: "Cult of Strahd",             description: "Mortal servants who have sworn themselves to Strahd in exchange for power, immortality, or simply the privilege of not being a victim. They spy, recruit, and betray — and are never truly trusted by their master.", faction_type: "Cult", alignment: "Neutral Evil", tags: ["strahd", "servants", "cult", "vampire"] },
    { name: "Keepers of the Black Flame",  description: "A religious order from Falkovnia who worship a dark flame said to burn at the centre of existence. They are not evil by intent but have survived under Vlad Drakov's tyranny by becoming hard — very hard.", faction_type: "Religion", alignment: "Lawful Neutral", tags: ["falkovnia", "religion", "fire", "survival", "dark"] },
    { name: "Fraternity of Shadows",       description: "A secret society of scholars devoted to studying the Demiplane of Dread itself — its origins, its rules, and the nature of the Dark Powers. They pursue this knowledge knowing that the Demiplane notices people who look too closely.", faction_type: "Secret Society", alignment: "True Neutral", tags: ["scholars", "secret", "dark powers", "forbidden knowledge", "demiplane"] },
    { name: "The Kin",                     description: "The loose social web of vampire bloodlines within the Demiplane — multiple lineages, each with its own traditions, powers, and territorial claims. They do not cooperate so much as coexist in mutual wariness, held apart by ancient grudges and the fact that betrayal is their native tongue.", faction_type: "Other", alignment: "Neutral Evil", tags: ["vampires", "bloodlines", "undead", "nobility", "political"] },
    { name: "Priests of Osybus",           description: "A cult that worships Osybus, a mysterious dark entity who promises vampiric power to mortals willing to undergo his transformation. They are dangerous recruiters who offer what desperate people want most: the power to stop being prey.", faction_type: "Cult", alignment: "Neutral Evil", tags: ["vampires", "cult", "osybus", "dark entity", "corruption"] },
    { name: "The Carnival",                description: "A travelling carnival that moves through the Mists between domains, offering wonders and refuge to the unusual and the outcast. Its ringmaster Isolde keeps it moving and keeps the Mists from claiming it — barely, and at a cost she does not discuss.", faction_type: "Other", alignment: "Chaotic Neutral", tags: ["carnival", "refuge", "mists", "wanderers", "outcasts"] },
  ],

  heroes: [
    {
      name: "Strahd von Zarovich",
      race: "Vampire",
      alignment: "Lawful Evil",
      occupation: "Darklord of Barovia / Count",
      personality: "Ancient, imperious, and consumed by a love he can never fulfil. Strahd is not a simple monster — he is a brilliant general and ruler who has lived with his curse for centuries. He is capable of charm, generosity, and terrible violence, often in the same conversation.",
      backstory: "Once a great conqueror and warlord, Strahd made a pact with Death to claim his brother Sergei's bride Tatyana. He murdered his brother on Sergei's wedding day, became the first vampire, and has been imprisoned in Barovia ever since — watching Tatyana's soul reincarnate again and again, forever out of reach.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["darklord", "vampire", "barovia", "strahd", "curse of strahd"],
    },
    {
      name: "Madam Eva",
      race: "Vistani",
      alignment: "True Neutral",
      occupation: "Seer / Vistani Elder",
      personality: "Ancient, inscrutable, and radiating an unsettling sense of purpose. Madam Eva does not explain herself. She reads the Tarokka cards, delivers her prophecies, and watches — always watches — to see which fate the players choose.",
      backstory: "The eldest and most powerful Vistani seer in Barovia, Madam Eva has guided countless adventurers to their doom or salvation. Her true nature is debated — some say she is a fragment of the Dark Powers themselves.",
      status: "alive",
      relationship: "indifferent",
      portrait_url: null,
      tags: ["vistani", "seer", "tarokka", "barovia", "mysterious"],
    },
    {
      name: "Rudolph van Richten",
      race: "Human",
      alignment: "Lawful Good",
      occupation: "Monster Hunter / Scholar",
      personality: "Methodical, haunted, and driven by grief transformed into purpose. Van Richten lost his son to vampires and has spent decades building the knowledge to destroy them. He is brilliantly capable and deeply tragic — a man who has become the thing he hunts in terms of ruthlessness.",
      backstory: "The foremost monster hunter in the Demiplane of Dread, author of the Van Richten's Guides to various horrors. He travels under assumed identities because his enemies are numerous and his allies few. He carries tremendous guilt.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["van richten", "monster hunter", "scholar", "barovia", "tragic"],
    },
    {
      name: "Rictavio",
      race: "Human",
      alignment: "Lawful Good",
      occupation: "Monster Hunter (Disguised as Carnival Master)",
      personality: "Theatrical, careful, and operating at least two personas at once. When Rictavio lets the mask slip, the grief and steel underneath are unmistakable. He has been at this long enough that the performance is almost comfortable.",
      backstory: "Van Richten's travelling alias — a jolly carnival master with a covered wagon and a pet saber-toothed tiger. He uses this disguise to move through Barovia without Strahd identifying him. Anyone who looks closely enough will notice the hunter's eyes behind the showman's smile.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["van richten", "disguise", "monster hunter", "barovia", "carnival"],
    },
    {
      name: "Ireena Kolyana",
      race: "Human",
      alignment: "Neutral Good",
      occupation: "Nobleman's Daughter / Fighter",
      personality: "Brave and self-possessed despite living her entire life in the shadow of Castle Ravenloft. Ireena refuses to be a victim. She is stubborn, warm, and somewhat bewildered that anyone has come to help her.",
      backstory: "The adopted daughter of the Burgomaster of the Village of Barovia, Ireena bears the face of Tatyana — the woman Strahd has loved and lost across centuries. She has been bitten twice. The party's job is to get her somewhere safe before the third bite.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["barovia", "tatyana", "strahd", "protected"],
    },
    {
      name: "Ismark the Lesser",
      race: "Human",
      alignment: "Neutral Good",
      occupation: "Fighter / Burgomaster's Son",
      personality: "Earnest, brave, and desperately aware that his nickname 'the Lesser' is probably accurate. Ismark is trying to do right by his sister and his village without the power or resources to succeed alone. He will accept any help offered.",
      backstory: "Son of the Burgomaster of the Village of Barovia, Ismark has watched his father die and his sister become Strahd's obsession. He reached out to adventurers because he has no other options. He is ordinary — and the world needs ordinary people to be brave.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["barovia", "village", "ireena", "burgomaster"],
    },
    {
      name: "Azalin Rex",
      race: "Lich",
      alignment: "Lawful Evil",
      occupation: "Darklord of Darkon / Lich King",
      personality: "Cold, erudite, and possessed of a scholar's obsession with breaking rules that should not be breakable. Azalin is trapped in the Demiplane just as Strahd is, and he hates it with a methodical, academic fury that has not cooled in centuries.",
      backstory: "Once a powerful wizard-king, Azalin achieved lichdom and was drawn into the Demiplane of Dread, where he rules Darkon. He attempted a ritual called the Requiem to break free — it destroyed his domain's capital instead, turning Il Aluk into the Necropolis. He is still searching for an exit.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["darklord", "lich", "darkon", "necropolis", "il aluk"],
    },
    {
      name: "Vlad Drakov",
      race: "Human",
      alignment: "Lawful Evil",
      occupation: "Darklord of Falkovnia / Military Tyrant",
      personality: "A bully who became a warlord who became a tyrant. Drakov is not subtle, not clever, and not interested in being either. He respects only force and interprets every negotiation as an invitation to demonstrate it.",
      backstory: "A mercenary warlord who conquered the domain of Falkovnia through sheer military brutality. He is imprisoned here by the Dark Powers — his curse is that his armies, no matter how large, are perpetually attacked by undead hordes he can never quite defeat. He has never connected these two facts.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["darklord", "falkovnia", "tyrant", "military", "warlord"],
    },
    {
      name: "Doctor Viktra Mordenheim",
      race: "Human",
      alignment: "Neutral Evil",
      occupation: "Darklord of Lamordia / Scientist",
      personality: "Brilliant and utterly convinced that emotion is a defect to be corrected. Mordenheim works with a surgeon's precision and an artist's obsession. She has created the perfect artificial life — and her creation hates her for it.",
      backstory: "The Darklord of Lamordia — a domain of gothic science-horror. She created a flesh golem called Adam, seeking to understand and replicate the miracle of life. Adam's rejection of her and his subsequent suffering is her prison — she cannot truly rest until she recaptures him, and she cannot capture him while he chooses to flee.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["darklord", "lamordia", "scientist", "flesh golem", "gothic science"],
    },
    {
      name: "Adam the Flesh Golem",
      race: "Flesh Golem",
      alignment: "Chaotic Neutral",
      occupation: "Mordenheim's Creation / Fugitive",
      personality: "Wounded, intelligent, and oscillating between grief and rage. Adam did not ask to exist and did not ask to be what he is. He wants only to understand his nature and to be left alone — neither of which the Demiplane is inclined to provide.",
      backstory: "Created by Doctor Mordenheim from cadaver parts as proof that life can be manufactured. Adam's consciousness awakened fully formed — and with full awareness of what he was. He fled his creator and now wanders Lamordia and beyond, a tragic figure too intelligent to be a monster and too monstrous to be a man.",
      status: "alive",
      relationship: "indifferent",
      portrait_url: null,
      tags: ["lamordia", "flesh golem", "creation", "mordenheim", "tragic"],
    },
    {
      name: "Lady Wachter",
      race: "Human",
      alignment: "Lawful Evil",
      occupation: "Noble / Devil Cultist",
      personality: "Controlled, patrician, and absolutely convinced that Strahd's rule is preferable to the chaos that would follow his defeat. Lady Wachter pragmatically worships devils, runs Vallaki's opposition faction, and views anyone who tries to 'save' Barovia as a dangerous idiot.",
      backstory: "The matriarch of Wachterhaus in Vallaki and a secret cult leader who communes with a devil familiar. She believes the way to protect her family and city is to cooperate with Strahd rather than oppose him. She is not wrong exactly — she is just operating on a shorter time horizon than the party.",
      status: "alive",
      relationship: "hostile",
      portrait_url: null,
      tags: ["vallaki", "noble", "cult", "devil", "pragmatist"],
    },
    {
      name: "Father Lucian Petrovich",
      race: "Human",
      alignment: "Lawful Good",
      occupation: "Priest of the Morning Lord",
      personality: "Gentle, fearful, and clinging to faith the way a drowning man clings to a plank. Father Lucian has never stopped believing but he has often stopped hoping. He will help adventurers because it is right, not because he expects it to work.",
      backstory: "The priest of St. Andral's Church in Vallaki, keeper of the bones of St. Andral that protect the church from Strahd. He is a decent man in a terrible place, doing what he can. Someone has stolen the bones. He knows he should tell someone. He is afraid of what comes next.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["vallaki", "priest", "morning lord", "church", "st andral"],
    },
    {
      name: "Esmeralda d'Avenir",
      race: "Half-Vistani",
      alignment: "Neutral Good",
      occupation: "Monster Hunter",
      personality: "Fierce, proud, and carrying the particular bitterness of someone who belongs nowhere — too human for the Vistani caravans, too Vistani for most human settlements. She channels this into exceptional competence at killing things that deserve it.",
      backstory: "A half-Vistani monster hunter trained by Van Richten himself. She is one of the most capable monster hunters in the Demiplane of Dread but lacks her mentor's decades of experience — which she compensates for with aggression. She and Van Richten have a complicated history.",
      status: "alive",
      relationship: "helpful",
      portrait_url: null,
      tags: ["monster hunter", "vistani", "half-vistani", "van richten", "hunter"],
    },
    {
      name: "Arturi Radanavich",
      race: "Vistani",
      alignment: "True Neutral",
      occupation: "Vistani Traveller / Bearer of a Curse",
      personality: "Tired and carrying something he cannot put down. Arturi is one of Van Richten's oldest connections to the Vistani — and one of the Vistani who placed a curse on the doctor that he has never quite been able to forgive himself for.",
      backstory: "A Vistani man who participated in the curse placed on Van Richten after the doctor used Vistani knowledge destructively. He travels the Demiplane in atonement — or perhaps just in habit — and has a uniquely complicated relationship with the concept of justice.",
      status: "alive",
      relationship: "indifferent",
      portrait_url: null,
      tags: ["vistani", "curse", "van richten", "traveller", "atonement"],
    },
  ],
  pantheons: [],
  deities: [],
};
