import { readFileSync, writeFileSync } from "node:fs";

// Read tight potrace traces (<name>.svg) from cwd, normalize each into a shared
// 0 0 100 100 box (centered, padded), rewrite the hard-coded black fill to
// currentColor so the glyph tints with text colour, and emit a TS data module
// of inner SVG markup.
//
// Usage: node gen-glyphs.mjs <outFile.ts> <name1> <name2> ...
const [, , outFile, ...names] = process.argv;
if (!outFile || !names.length) {
  console.error("usage: node gen-glyphs.mjs <outFile> <name...>");
  process.exit(1);
}

const BOX = 100;
const PAD = 6; // small padding so glyphs fill the box like the Lucide neighbours
const LIVE = BOX - PAD * 2;
const t = (n) => Number(n.toFixed(3));

const entries = names.map((name) => {
  const src = readFileSync(`${name}.svg`, "utf8");
  const vb = src.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
  if (!vb) throw new Error(`no viewBox in ${name}.svg`);
  const w = parseFloat(vb[1]);
  const h = parseFloat(vb[2]);
  let g = src.match(/<g transform=[\s\S]*?<\/g>/)?.[0];
  if (!g) throw new Error(`no <g> in ${name}.svg`);
  g = g.replace(/fill="#000000"/g, 'fill="currentColor"'); // tint from the <svg> (potrace emits this on its own line, so match the attr, not a leading space)

  const scale = LIVE / Math.max(w, h);
  const tx = (BOX - w * scale) / 2;
  const ty = (BOX - h * scale) / 2;
  const inner = `<g transform="translate(${t(tx)} ${t(ty)}) scale(${t(scale)})">${g}</g>`;
  return [name, inner];
});

const body = entries
  .map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`)
  .join("\n");
writeFileSync(
  outFile,
  `// AUTO-GENERATED by art-src/dice/gen-glyphs.mjs — do not edit by hand.\n` +
    `// Inner SVG markup for custom polyhedral-dice glyphs, normalized to a 0 0 100 100 viewBox.\n` +
    `export const DICE_GLYPHS = {\n${body}\n} as const;\n`,
);
console.log(`wrote ${outFile} (${entries.length} glyphs)`);
