-- Migration: grimoire_bestiary_stoat
-- The Stoat (#955, 10 Oct 2026): a weasel in its white winter coat, asked for by the maintainer for the wintry
-- northern setting the library art is painted in. One row per ruleset. Its statistics are the System Reference
-- Document's Weasel for that edition (SRD 5.1 and 5.2, CC BY 4.0, attributed in the source's copyright notice), plus one
-- original trait, Winter Coat; the description is original.
--
-- It lives under a new source of its own, `grimoire-bestiary` ("Grimoire Bestiary (homebrew)"): house monsters as an
-- opt-in set, apart from every book and from Grimoire Species, so a DM switches it on per campaign like any non-SRD
-- source. A source with monsters already appears in the Monster Sources picker (get_library_monster_sources).

insert into public.content_sources (key, open5e_key, title, publisher, license_keys, copyright_notice, product_url, gamesystem, is_redistributable, is_metadata_curated, sort_order)
values ('grimoire-bestiary', null, 'Grimoire Bestiary (homebrew)', 'Dungeon Grimoire', '{cc-by-40}', 'Original homebrew creatures written for Dungeon Grimoire. Statistics adapted from the System Reference Document 5.1 and 5.2 by Wizards of the Coast LLC, used under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/legalcode).', null, null, true, true, 84)
on conflict (key) do nothing;

insert into public.library_monsters (id, name, monster_type, size, alignment, source, source_title, is_shared, open5e_import, tags, stat_block, ruleset, conceptual_key, source_document_key, source_record_key, source_revision, source_license, provenance, description)
values
  ('grimoire_stoat', 'Stoat', 'beast', 'tiny', 'unaligned', 'grimoire-bestiary', 'Grimoire Bestiary (homebrew)', true, false, array[]::text[], '{"cha": 3, "con": 8, "dex": 16, "int": 2, "str": 3, "wis": 12, "speed": "30 ft.", "skills": {"stealth": "+5", "perception": "+3"}, "actions": [{"name": "Bite", "description": "Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 1 piercing damage."}], "hit_points": "1 (1d4-1)", "armor_class": 13, "challenge_rating": "0", "special_abilities": [{"name": "Keen Hearing and Smell", "description": "The stoat has advantage on Wisdom (Perception) checks that rely on hearing or smell."}, {"name": "Winter Coat", "description": "In snowy terrain, the stoat has advantage on Dexterity (Stealth) checks made to hide."}]}'::jsonb, '2014', 'stoat', 'grimoire-bestiary', 'grimoire_2014_stoat', 'Dungeon Grimoire homebrew, October 2026', 'cc-by-40', '{"provider": "grimoire", "document": {"key": "grimoire-bestiary", "publisher": {"key": "grimoire", "name": "Dungeon Grimoire"}}, "based_on": "Weasel (System Reference Document 5.1 and 5.2)"}'::jsonb, '{"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "A small, lithe hunter with a long sinuous body, short legs and bright black eyes. In winter its coat turns snow-white from nose to tail, all but the tip of the tail, which stays jet black; in summer it wears russet brown with a cream belly."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Stoats hunt voles, rabbits and birds far larger than themselves, slipping through burrows and snow tunnels and killing with a quick bite to the neck. Northern furriers prize the white winter pelt, which they call ermine, and a stoat seen dancing in the snow is said to be a sign of a hard winter coming."}]}]}'),
  ('grimoire_2024_stoat', 'Stoat', 'beast', 'tiny', 'unaligned', 'grimoire-bestiary', 'Grimoire Bestiary (homebrew)', true, false, array[]::text[], '{"cha": 3, "con": 8, "dex": 16, "int": 2, "str": 3, "wis": 12, "speed": "30 ft., climb 30 ft.", "senses": "darkvision 60 ft.", "skills": {"stealth": "+5", "acrobatics": "+5", "perception": "+3"}, "actions": [{"name": "Bite", "description": "Melee Attack Roll: +5, reach 5 ft. 1 Piercing damage."}], "hit_points": "1 (1d4 - 1)", "armor_class": 13, "challenge_rating": "0", "initiative_bonus": 3, "special_abilities": [{"name": "Winter Coat", "description": "While in snowy terrain, the stoat has Advantage on Dexterity (Stealth) checks made to hide."}]}'::jsonb, '2024', 'stoat', 'grimoire-bestiary', 'grimoire_2024_stoat', 'Dungeon Grimoire homebrew, October 2026', 'cc-by-40', '{"provider": "grimoire", "document": {"key": "grimoire-bestiary", "publisher": {"key": "grimoire", "name": "Dungeon Grimoire"}}, "based_on": "Weasel (System Reference Document 5.1 and 5.2)"}'::jsonb, '{"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "A small, lithe hunter with a long sinuous body, short legs and bright black eyes. In winter its coat turns snow-white from nose to tail, all but the tip of the tail, which stays jet black; in summer it wears russet brown with a cream belly."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Stoats hunt voles, rabbits and birds far larger than themselves, slipping through burrows and snow tunnels and killing with a quick bite to the neck. Northern furriers prize the white winter pelt, which they call ermine, and a stoat seen dancing in the snow is said to be a sign of a hard winter coming."}]}]}')
on conflict (id) do nothing;
