-- Migration: library_tile_pack_generation_lane
-- The generation engine learns to produce a library pack (#889 S3).
--
-- `tile_pack_generation_runs` was written for one lane: a Pro subscriber
-- generating a private pack inside one of their campaigns, paying credits per
-- slot. The engine around it is production-grade — proof → approve → full,
-- resumable, a 4-attempt budget per slot, reserve/settle credits — and none of
-- that wants rewriting to also produce a library pack. What changes is only
-- *what the run points at* and *who pays*.
--
-- So: a run targets exactly one of a `user_tile_packs` row or a
-- `library_tile_packs` row, and the columns that only make sense for the user
-- lane become nullable rather than being faked for the other.
--
-- WHY campaign_id BECOMES NULLABLE RATHER THAN POINTING SOMEWHERE:
-- The campaign is load-bearing in the user lane — it carries `ai_enabled`, the
-- BYOK key, and the DM check that authorizes the run. A library pack has none
-- of those: it is platform content, authorized by `private.is_app_admin()` and
-- generated with the platform key only. Pointing it at some house campaign
-- would be inventing a fact so a NOT NULL could stay, and every read of that
-- column downstream would then have to know the fiction.
--
-- `user_id` stays NOT NULL in both lanes. In the library lane it is the admin
-- who started the run — not an owner, but the accountable party, which is what
-- the column is actually for here.

alter table public.tile_pack_generation_runs
  add column library_tile_pack_id uuid references public.library_tile_packs(id) on delete cascade;

alter table public.tile_pack_generation_runs
  alter column campaign_id drop not null,
  alter column tile_pack_id drop not null;

-- Exactly one target, and the campaign travels with the lane that has one.
-- Two constraints rather than one compound check, so a violation says which
-- half is wrong.
alter table public.tile_pack_generation_runs
  add constraint tile_pack_generation_runs_one_target check (
    (tile_pack_id is not null) <> (library_tile_pack_id is not null)
  );

alter table public.tile_pack_generation_runs
  add constraint tile_pack_generation_runs_campaign_matches_lane check (
    case
      when tile_pack_id is not null then campaign_id is not null
      else campaign_id is null
    end
  );

create index tile_pack_generation_runs_library_idx
  on public.tile_pack_generation_runs (library_tile_pack_id)
  where library_tile_pack_id is not null;

comment on column public.tile_pack_generation_runs.library_tile_pack_id is
  'Set when this run produces a shared library pack instead of a DM''s private one. Mutually exclusive with tile_pack_id; a library run has no campaign, charges no credits, and is authorized by private.is_app_admin() inside the edge function rather than by campaign DM membership.';

-- ── Visibility ────────────────────────────────────────────────────────────
--
-- The existing policies (`auth.uid() = user_id`) already show an admin the
-- library runs they started, so the panel works without touching them. What
-- they do not give is one admin seeing another admin's library run, which a
-- shared authoring surface needs — otherwise a pack half-generated by whoever
-- is on holiday is invisible to everyone else.
--
-- Deliberately scoped to `library_tile_pack_id is not null` rather than
-- granting admins a blanket read of the table. Users' private generation runs
-- carry their prompts and their spend; nothing in this epic needs an admin to
-- see them, so nothing here grants it.

drop policy if exists "tile_pack_generation_runs_select" on public.tile_pack_generation_runs;
create policy "tile_pack_generation_runs_select" on public.tile_pack_generation_runs
  for select using (
    auth.uid() = user_id
    or (library_tile_pack_id is not null and private.is_app_admin())
  );

drop policy if exists "tile_pack_generation_jobs_select" on public.tile_pack_generation_jobs;
create policy "tile_pack_generation_jobs_select" on public.tile_pack_generation_jobs
  for select using (
    exists (
      select 1 from public.tile_pack_generation_runs r
      where r.id = run_id
        and (
          r.user_id = auth.uid()
          or (r.library_tile_pack_id is not null and private.is_app_admin())
        )
    )
  );
