-- The 2014 class spell lists, as the SRD 5.1 prints them. Open5e's srd-2014 data
-- tags a spell with every class that can reach it, subclasses included, so the
-- library let any Cleric take every domain's spells (Burning Hands, Speak with
-- Animals), any Druid every Land circle's (Misty Step, Spider Climb), and held
-- no 2014 Paladin spells at all, not one being tagged Paladin. Measured against
-- the official PDF on 8 Oct 2026: 37 Cleric and 21 Druid tags too many, the 31
-- Paladin spells and Druid's Plane Shift missing. A subclass's spells are granted
-- always-prepared, which validate_character_spell_source already admits.
-- No saved character pick in production used any of the removed tags (checked
-- the same day), so nothing is stranded.
--
-- Recomputes every srd-2014 spell's classes from the lists below, the same table
-- src/data/srd2014ClassSpellLists.ts gives the Open5e import, so the library and
-- a re-seed agree. Classes the lists do not cover keep the tag the row has:
-- Warlock, whose patron spells widen the list it picks from and need the
-- spell-source check to know a subclass's expanded list before they can go, and
-- the Artificer delta. A stack with an empty library (CI replays migrations
-- before any seed) updates nothing.
with lists(class_name, spell_name) as (values
  ('Bard', 'Animal Friendship'),
  ('Bard', 'Animal Messenger'),
  ('Bard', 'Animate Objects'),
  ('Bard', 'Arcane Sword'),
  ('Bard', 'Awaken'),
  ('Bard', 'Bane'),
  ('Bard', 'Bestow Curse'),
  ('Bard', 'Blindness/Deafness'),
  ('Bard', 'Calm Emotions'),
  ('Bard', 'Charm Person'),
  ('Bard', 'Clairvoyance'),
  ('Bard', 'Comprehend Languages'),
  ('Bard', 'Compulsion'),
  ('Bard', 'Confusion'),
  ('Bard', 'Cure Wounds'),
  ('Bard', 'Dancing Lights'),
  ('Bard', 'Detect Magic'),
  ('Bard', 'Detect Thoughts'),
  ('Bard', 'Dimension Door'),
  ('Bard', 'Disguise Self'),
  ('Bard', 'Dispel Magic'),
  ('Bard', 'Dominate Monster'),
  ('Bard', 'Dominate Person'),
  ('Bard', 'Dream'),
  ('Bard', 'Enhance Ability'),
  ('Bard', 'Enthrall'),
  ('Bard', 'Etherealness'),
  ('Bard', 'Eyebite'),
  ('Bard', 'Faerie Fire'),
  ('Bard', 'Fear'),
  ('Bard', 'Feather Fall'),
  ('Bard', 'Feeblemind'),
  ('Bard', 'Find the Path'),
  ('Bard', 'Forcecage'),
  ('Bard', 'Foresight'),
  ('Bard', 'Freedom of Movement'),
  ('Bard', 'Geas'),
  ('Bard', 'Glibness'),
  ('Bard', 'Glyph of Warding'),
  ('Bard', 'Greater Invisibility'),
  ('Bard', 'Greater Restoration'),
  ('Bard', 'Guards and Wards'),
  ('Bard', 'Hallucinatory Terrain'),
  ('Bard', 'Healing Word'),
  ('Bard', 'Heat Metal'),
  ('Bard', 'Heroism'),
  ('Bard', 'Hideous Laughter'),
  ('Bard', 'Hold Monster'),
  ('Bard', 'Hold Person'),
  ('Bard', 'Hypnotic Pattern'),
  ('Bard', 'Identify'),
  ('Bard', 'Illusory Script'),
  ('Bard', 'Invisibility'),
  ('Bard', 'Irresistible Dance'),
  ('Bard', 'Knock'),
  ('Bard', 'Legend Lore'),
  ('Bard', 'Lesser Restoration'),
  ('Bard', 'Light'),
  ('Bard', 'Locate Animals or Plants'),
  ('Bard', 'Locate Creature'),
  ('Bard', 'Locate Object'),
  ('Bard', 'Longstrider'),
  ('Bard', 'Mage Hand'),
  ('Bard', 'Magic Mouth'),
  ('Bard', 'Magnificent Mansion'),
  ('Bard', 'Major Image'),
  ('Bard', 'Mass Cure Wounds'),
  ('Bard', 'Mass Suggestion'),
  ('Bard', 'Mending'),
  ('Bard', 'Message'),
  ('Bard', 'Mind Blank'),
  ('Bard', 'Minor Illusion'),
  ('Bard', 'Mirage Arcane'),
  ('Bard', 'Mislead'),
  ('Bard', 'Modify Memory'),
  ('Bard', 'Nondetection'),
  ('Bard', 'Planar Binding'),
  ('Bard', 'Plant Growth'),
  ('Bard', 'Polymorph'),
  ('Bard', 'Power Word Kill'),
  ('Bard', 'Power Word Stun'),
  ('Bard', 'Prestidigitation'),
  ('Bard', 'Programmed Illusion'),
  ('Bard', 'Project Image'),
  ('Bard', 'Raise Dead'),
  ('Bard', 'Regenerate'),
  ('Bard', 'Resurrection'),
  ('Bard', 'Scrying'),
  ('Bard', 'See Invisibility'),
  ('Bard', 'Seeming'),
  ('Bard', 'Sending'),
  ('Bard', 'Shatter'),
  ('Bard', 'Silence'),
  ('Bard', 'Silent Image'),
  ('Bard', 'Sleep'),
  ('Bard', 'Speak with Animals'),
  ('Bard', 'Speak with Dead'),
  ('Bard', 'Speak with Plants'),
  ('Bard', 'Stinking Cloud'),
  ('Bard', 'Suggestion'),
  ('Bard', 'Symbol'),
  ('Bard', 'Teleport'),
  ('Bard', 'Teleportation Circle'),
  ('Bard', 'Thunderwave'),
  ('Bard', 'Tiny Hut'),
  ('Bard', 'Tongues'),
  ('Bard', 'True Polymorph'),
  ('Bard', 'True Seeing'),
  ('Bard', 'True Strike'),
  ('Bard', 'Unseen Servant'),
  ('Bard', 'Vicious Mockery'),
  ('Bard', 'Zone of Truth'),
  ('Cleric', 'Aid'),
  ('Cleric', 'Animate Dead'),
  ('Cleric', 'Antimagic Field'),
  ('Cleric', 'Astral Projection'),
  ('Cleric', 'Augury'),
  ('Cleric', 'Bane'),
  ('Cleric', 'Banishment'),
  ('Cleric', 'Beacon of Hope'),
  ('Cleric', 'Bestow Curse'),
  ('Cleric', 'Blade Barrier'),
  ('Cleric', 'Bless'),
  ('Cleric', 'Blindness/Deafness'),
  ('Cleric', 'Calm Emotions'),
  ('Cleric', 'Clairvoyance'),
  ('Cleric', 'Command'),
  ('Cleric', 'Commune'),
  ('Cleric', 'Conjure Celestial'),
  ('Cleric', 'Contagion'),
  ('Cleric', 'Continual Flame'),
  ('Cleric', 'Control Water'),
  ('Cleric', 'Control Weather'),
  ('Cleric', 'Create Food and Water'),
  ('Cleric', 'Create or Destroy Water'),
  ('Cleric', 'Create Undead'),
  ('Cleric', 'Cure Wounds'),
  ('Cleric', 'Daylight'),
  ('Cleric', 'Death Ward'),
  ('Cleric', 'Detect Evil and Good'),
  ('Cleric', 'Detect Magic'),
  ('Cleric', 'Detect Poison and Disease'),
  ('Cleric', 'Dispel Evil and Good'),
  ('Cleric', 'Dispel Magic'),
  ('Cleric', 'Divination'),
  ('Cleric', 'Divine Word'),
  ('Cleric', 'Earthquake'),
  ('Cleric', 'Enhance Ability'),
  ('Cleric', 'Etherealness'),
  ('Cleric', 'Find the Path'),
  ('Cleric', 'Find Traps'),
  ('Cleric', 'Fire Storm'),
  ('Cleric', 'Flame Strike'),
  ('Cleric', 'Forbiddance'),
  ('Cleric', 'Freedom of Movement'),
  ('Cleric', 'Gate'),
  ('Cleric', 'Geas'),
  ('Cleric', 'Gentle Repose'),
  ('Cleric', 'Glyph of Warding'),
  ('Cleric', 'Greater Restoration'),
  ('Cleric', 'Guardian of Faith'),
  ('Cleric', 'Guidance'),
  ('Cleric', 'Guiding Bolt'),
  ('Cleric', 'Hallow'),
  ('Cleric', 'Harm'),
  ('Cleric', 'Heal'),
  ('Cleric', 'Healing Word'),
  ('Cleric', 'Heroes'' Feast'),
  ('Cleric', 'Hold Person'),
  ('Cleric', 'Holy Aura'),
  ('Cleric', 'Inflict Wounds'),
  ('Cleric', 'Insect Plague'),
  ('Cleric', 'Legend Lore'),
  ('Cleric', 'Lesser Restoration'),
  ('Cleric', 'Light'),
  ('Cleric', 'Locate Creature'),
  ('Cleric', 'Locate Object'),
  ('Cleric', 'Magic Circle'),
  ('Cleric', 'Mass Cure Wounds'),
  ('Cleric', 'Mass Heal'),
  ('Cleric', 'Mass Healing Word'),
  ('Cleric', 'Meld into Stone'),
  ('Cleric', 'Mending'),
  ('Cleric', 'Planar Ally'),
  ('Cleric', 'Planar Binding'),
  ('Cleric', 'Plane Shift'),
  ('Cleric', 'Prayer of Healing'),
  ('Cleric', 'Protection from Energy'),
  ('Cleric', 'Protection from Evil and Good'),
  ('Cleric', 'Protection from Poison'),
  ('Cleric', 'Purify Food and Drink'),
  ('Cleric', 'Raise Dead'),
  ('Cleric', 'Regenerate'),
  ('Cleric', 'Remove Curse'),
  ('Cleric', 'Resistance'),
  ('Cleric', 'Resurrection'),
  ('Cleric', 'Revivify'),
  ('Cleric', 'Sacred Flame'),
  ('Cleric', 'Sanctuary'),
  ('Cleric', 'Scrying'),
  ('Cleric', 'Sending'),
  ('Cleric', 'Shield of Faith'),
  ('Cleric', 'Silence'),
  ('Cleric', 'Spare the Dying'),
  ('Cleric', 'Speak with Dead'),
  ('Cleric', 'Spirit Guardians'),
  ('Cleric', 'Spiritual Weapon'),
  ('Cleric', 'Stone Shape'),
  ('Cleric', 'Symbol'),
  ('Cleric', 'Thaumaturgy'),
  ('Cleric', 'Tongues'),
  ('Cleric', 'True Resurrection'),
  ('Cleric', 'True Seeing'),
  ('Cleric', 'Warding Bond'),
  ('Cleric', 'Water Walk'),
  ('Cleric', 'Word of Recall'),
  ('Cleric', 'Zone of Truth'),
  ('Druid', 'Animal Friendship'),
  ('Druid', 'Animal Messenger'),
  ('Druid', 'Animal Shapes'),
  ('Druid', 'Antilife Shell'),
  ('Druid', 'Antipathy/Sympathy'),
  ('Druid', 'Awaken'),
  ('Druid', 'Barkskin'),
  ('Druid', 'Blight'),
  ('Druid', 'Call Lightning'),
  ('Druid', 'Charm Person'),
  ('Druid', 'Commune with Nature'),
  ('Druid', 'Confusion'),
  ('Druid', 'Conjure Animals'),
  ('Druid', 'Conjure Elemental'),
  ('Druid', 'Conjure Fey'),
  ('Druid', 'Conjure Minor Elementals'),
  ('Druid', 'Conjure Woodland Beings'),
  ('Druid', 'Contagion'),
  ('Druid', 'Control Water'),
  ('Druid', 'Control Weather'),
  ('Druid', 'Create or Destroy Water'),
  ('Druid', 'Cure Wounds'),
  ('Druid', 'Darkvision'),
  ('Druid', 'Daylight'),
  ('Druid', 'Detect Magic'),
  ('Druid', 'Detect Poison and Disease'),
  ('Druid', 'Dispel Magic'),
  ('Druid', 'Dominate Beast'),
  ('Druid', 'Druidcraft'),
  ('Druid', 'Earthquake'),
  ('Druid', 'Enhance Ability'),
  ('Druid', 'Entangle'),
  ('Druid', 'Faerie Fire'),
  ('Druid', 'Feeblemind'),
  ('Druid', 'Find the Path'),
  ('Druid', 'Find Traps'),
  ('Druid', 'Fire Storm'),
  ('Druid', 'Flame Blade'),
  ('Druid', 'Flaming Sphere'),
  ('Druid', 'Fog Cloud'),
  ('Druid', 'Foresight'),
  ('Druid', 'Freedom of Movement'),
  ('Druid', 'Geas'),
  ('Druid', 'Giant Insect'),
  ('Druid', 'Goodberry'),
  ('Druid', 'Greater Restoration'),
  ('Druid', 'Guidance'),
  ('Druid', 'Gust of Wind'),
  ('Druid', 'Hallucinatory Terrain'),
  ('Druid', 'Heal'),
  ('Druid', 'Healing Word'),
  ('Druid', 'Heat Metal'),
  ('Druid', 'Heroes'' Feast'),
  ('Druid', 'Hold Person'),
  ('Druid', 'Ice Storm'),
  ('Druid', 'Insect Plague'),
  ('Druid', 'Jump'),
  ('Druid', 'Lesser Restoration'),
  ('Druid', 'Locate Animals or Plants'),
  ('Druid', 'Locate Creature'),
  ('Druid', 'Locate Object'),
  ('Druid', 'Longstrider'),
  ('Druid', 'Mass Cure Wounds'),
  ('Druid', 'Meld into Stone'),
  ('Druid', 'Mending'),
  ('Druid', 'Mirage Arcane'),
  ('Druid', 'Moonbeam'),
  ('Druid', 'Move Earth'),
  ('Druid', 'Pass without Trace'),
  ('Druid', 'Planar Binding'),
  ('Druid', 'Plane Shift'),
  ('Druid', 'Plant Growth'),
  ('Druid', 'Poison Spray'),
  ('Druid', 'Polymorph'),
  ('Druid', 'Produce Flame'),
  ('Druid', 'Protection from Energy'),
  ('Druid', 'Protection from Poison'),
  ('Druid', 'Purify Food and Drink'),
  ('Druid', 'Regenerate'),
  ('Druid', 'Reincarnate'),
  ('Druid', 'Resistance'),
  ('Druid', 'Reverse Gravity'),
  ('Druid', 'Scrying'),
  ('Druid', 'Shapechange'),
  ('Druid', 'Shillelagh'),
  ('Druid', 'Sleet Storm'),
  ('Druid', 'Speak with Animals'),
  ('Druid', 'Speak with Plants'),
  ('Druid', 'Spike Growth'),
  ('Druid', 'Stone Shape'),
  ('Druid', 'Stoneskin'),
  ('Druid', 'Storm of Vengeance'),
  ('Druid', 'Sunbeam'),
  ('Druid', 'Sunburst'),
  ('Druid', 'Thunderwave'),
  ('Druid', 'Transport via Plants'),
  ('Druid', 'Tree Stride'),
  ('Druid', 'True Resurrection'),
  ('Druid', 'Wall of Fire'),
  ('Druid', 'Wall of Stone'),
  ('Druid', 'Wall of Thorns'),
  ('Druid', 'Water Breathing'),
  ('Druid', 'Water Walk'),
  ('Druid', 'Wind Walk'),
  ('Druid', 'Wind Wall'),
  ('Paladin', 'Aid'),
  ('Paladin', 'Banishment'),
  ('Paladin', 'Bless'),
  ('Paladin', 'Branding Smite'),
  ('Paladin', 'Command'),
  ('Paladin', 'Create Food and Water'),
  ('Paladin', 'Cure Wounds'),
  ('Paladin', 'Daylight'),
  ('Paladin', 'Death Ward'),
  ('Paladin', 'Detect Evil and Good'),
  ('Paladin', 'Detect Magic'),
  ('Paladin', 'Detect Poison and Disease'),
  ('Paladin', 'Dispel Evil and Good'),
  ('Paladin', 'Dispel Magic'),
  ('Paladin', 'Divine Favor'),
  ('Paladin', 'Find Steed'),
  ('Paladin', 'Geas'),
  ('Paladin', 'Heroism'),
  ('Paladin', 'Lesser Restoration'),
  ('Paladin', 'Locate Creature'),
  ('Paladin', 'Locate Object'),
  ('Paladin', 'Magic Circle'),
  ('Paladin', 'Magic Weapon'),
  ('Paladin', 'Protection from Evil and Good'),
  ('Paladin', 'Protection from Poison'),
  ('Paladin', 'Purify Food and Drink'),
  ('Paladin', 'Raise Dead'),
  ('Paladin', 'Remove Curse'),
  ('Paladin', 'Revivify'),
  ('Paladin', 'Shield of Faith'),
  ('Paladin', 'Zone of Truth'),
  ('Ranger', 'Alarm'),
  ('Ranger', 'Animal Friendship'),
  ('Ranger', 'Animal Messenger'),
  ('Ranger', 'Barkskin'),
  ('Ranger', 'Commune with Nature'),
  ('Ranger', 'Conjure Animals'),
  ('Ranger', 'Conjure Woodland Beings'),
  ('Ranger', 'Cure Wounds'),
  ('Ranger', 'Darkvision'),
  ('Ranger', 'Daylight'),
  ('Ranger', 'Detect Magic'),
  ('Ranger', 'Detect Poison and Disease'),
  ('Ranger', 'Find Traps'),
  ('Ranger', 'Fog Cloud'),
  ('Ranger', 'Freedom of Movement'),
  ('Ranger', 'Goodberry'),
  ('Ranger', 'Hunter''s Mark'),
  ('Ranger', 'Jump'),
  ('Ranger', 'Lesser Restoration'),
  ('Ranger', 'Locate Animals or Plants'),
  ('Ranger', 'Locate Creature'),
  ('Ranger', 'Locate Object'),
  ('Ranger', 'Longstrider'),
  ('Ranger', 'Nondetection'),
  ('Ranger', 'Pass without Trace'),
  ('Ranger', 'Plant Growth'),
  ('Ranger', 'Protection from Energy'),
  ('Ranger', 'Protection from Poison'),
  ('Ranger', 'Silence'),
  ('Ranger', 'Speak with Animals'),
  ('Ranger', 'Speak with Plants'),
  ('Ranger', 'Spike Growth'),
  ('Ranger', 'Stoneskin'),
  ('Ranger', 'Tree Stride'),
  ('Ranger', 'Water Breathing'),
  ('Ranger', 'Water Walk'),
  ('Ranger', 'Wind Wall'),
  ('Sorcerer', 'Acid Splash'),
  ('Sorcerer', 'Alter Self'),
  ('Sorcerer', 'Animate Objects'),
  ('Sorcerer', 'Banishment'),
  ('Sorcerer', 'Blight'),
  ('Sorcerer', 'Blindness/Deafness'),
  ('Sorcerer', 'Blink'),
  ('Sorcerer', 'Blur'),
  ('Sorcerer', 'Burning Hands'),
  ('Sorcerer', 'Chain Lightning'),
  ('Sorcerer', 'Charm Person'),
  ('Sorcerer', 'Chill Touch'),
  ('Sorcerer', 'Circle of Death'),
  ('Sorcerer', 'Clairvoyance'),
  ('Sorcerer', 'Cloudkill'),
  ('Sorcerer', 'Color Spray'),
  ('Sorcerer', 'Comprehend Languages'),
  ('Sorcerer', 'Cone of Cold'),
  ('Sorcerer', 'Confusion'),
  ('Sorcerer', 'Counterspell'),
  ('Sorcerer', 'Creation'),
  ('Sorcerer', 'Dancing Lights'),
  ('Sorcerer', 'Darkness'),
  ('Sorcerer', 'Darkvision'),
  ('Sorcerer', 'Daylight'),
  ('Sorcerer', 'Delayed Blast Fireball'),
  ('Sorcerer', 'Detect Magic'),
  ('Sorcerer', 'Detect Thoughts'),
  ('Sorcerer', 'Dimension Door'),
  ('Sorcerer', 'Disguise Self'),
  ('Sorcerer', 'Disintegrate'),
  ('Sorcerer', 'Dispel Magic'),
  ('Sorcerer', 'Dominate Beast'),
  ('Sorcerer', 'Dominate Monster'),
  ('Sorcerer', 'Dominate Person'),
  ('Sorcerer', 'Earthquake'),
  ('Sorcerer', 'Enhance Ability'),
  ('Sorcerer', 'Enlarge/Reduce'),
  ('Sorcerer', 'Etherealness'),
  ('Sorcerer', 'Expeditious Retreat'),
  ('Sorcerer', 'Eyebite'),
  ('Sorcerer', 'False Life'),
  ('Sorcerer', 'Fear'),
  ('Sorcerer', 'Feather Fall'),
  ('Sorcerer', 'Finger of Death'),
  ('Sorcerer', 'Fire Bolt'),
  ('Sorcerer', 'Fire Storm'),
  ('Sorcerer', 'Fireball'),
  ('Sorcerer', 'Fly'),
  ('Sorcerer', 'Fog Cloud'),
  ('Sorcerer', 'Gaseous Form'),
  ('Sorcerer', 'Gate'),
  ('Sorcerer', 'Globe of Invulnerability'),
  ('Sorcerer', 'Greater Invisibility'),
  ('Sorcerer', 'Gust of Wind'),
  ('Sorcerer', 'Haste'),
  ('Sorcerer', 'Hold Monster'),
  ('Sorcerer', 'Hold Person'),
  ('Sorcerer', 'Hypnotic Pattern'),
  ('Sorcerer', 'Ice Storm'),
  ('Sorcerer', 'Incendiary Cloud'),
  ('Sorcerer', 'Insect Plague'),
  ('Sorcerer', 'Invisibility'),
  ('Sorcerer', 'Jump'),
  ('Sorcerer', 'Knock'),
  ('Sorcerer', 'Levitate'),
  ('Sorcerer', 'Light'),
  ('Sorcerer', 'Lightning Bolt'),
  ('Sorcerer', 'Mage Armor'),
  ('Sorcerer', 'Mage Hand'),
  ('Sorcerer', 'Magic Missile'),
  ('Sorcerer', 'Major Image'),
  ('Sorcerer', 'Mass Suggestion'),
  ('Sorcerer', 'Mending'),
  ('Sorcerer', 'Message'),
  ('Sorcerer', 'Meteor Swarm'),
  ('Sorcerer', 'Minor Illusion'),
  ('Sorcerer', 'Mirror Image'),
  ('Sorcerer', 'Misty Step'),
  ('Sorcerer', 'Move Earth'),
  ('Sorcerer', 'Plane Shift'),
  ('Sorcerer', 'Poison Spray'),
  ('Sorcerer', 'Polymorph'),
  ('Sorcerer', 'Power Word Kill'),
  ('Sorcerer', 'Power Word Stun'),
  ('Sorcerer', 'Prestidigitation'),
  ('Sorcerer', 'Prismatic Spray'),
  ('Sorcerer', 'Protection from Energy'),
  ('Sorcerer', 'Ray of Frost'),
  ('Sorcerer', 'Reverse Gravity'),
  ('Sorcerer', 'Scorching Ray'),
  ('Sorcerer', 'See Invisibility'),
  ('Sorcerer', 'Seeming'),
  ('Sorcerer', 'Shatter'),
  ('Sorcerer', 'Shield'),
  ('Sorcerer', 'Shocking Grasp'),
  ('Sorcerer', 'Silent Image'),
  ('Sorcerer', 'Sleep'),
  ('Sorcerer', 'Sleet Storm'),
  ('Sorcerer', 'Slow'),
  ('Sorcerer', 'Spider Climb'),
  ('Sorcerer', 'Stinking Cloud'),
  ('Sorcerer', 'Stoneskin'),
  ('Sorcerer', 'Suggestion'),
  ('Sorcerer', 'Sunbeam'),
  ('Sorcerer', 'Sunburst'),
  ('Sorcerer', 'Telekinesis'),
  ('Sorcerer', 'Teleport'),
  ('Sorcerer', 'Teleportation Circle'),
  ('Sorcerer', 'Thunderwave'),
  ('Sorcerer', 'Time Stop'),
  ('Sorcerer', 'Tongues'),
  ('Sorcerer', 'True Seeing'),
  ('Sorcerer', 'True Strike'),
  ('Sorcerer', 'Wall of Fire'),
  ('Sorcerer', 'Wall of Stone'),
  ('Sorcerer', 'Water Breathing'),
  ('Sorcerer', 'Water Walk'),
  ('Sorcerer', 'Web'),
  ('Sorcerer', 'Wish'),
  ('Wizard', 'Acid Arrow'),
  ('Wizard', 'Acid Splash'),
  ('Wizard', 'Alarm'),
  ('Wizard', 'Alter Self'),
  ('Wizard', 'Animate Dead'),
  ('Wizard', 'Animate Objects'),
  ('Wizard', 'Antimagic Field'),
  ('Wizard', 'Antipathy/Sympathy'),
  ('Wizard', 'Arcane Eye'),
  ('Wizard', 'Arcane Hand'),
  ('Wizard', 'Arcane Lock'),
  ('Wizard', 'Arcane Sword'),
  ('Wizard', 'Arcanist''s Magic Aura'),
  ('Wizard', 'Astral Projection'),
  ('Wizard', 'Banishment'),
  ('Wizard', 'Bestow Curse'),
  ('Wizard', 'Black Tentacles'),
  ('Wizard', 'Blight'),
  ('Wizard', 'Blindness/Deafness'),
  ('Wizard', 'Blink'),
  ('Wizard', 'Blur'),
  ('Wizard', 'Burning Hands'),
  ('Wizard', 'Chain Lightning'),
  ('Wizard', 'Charm Person'),
  ('Wizard', 'Chill Touch'),
  ('Wizard', 'Circle of Death'),
  ('Wizard', 'Clairvoyance'),
  ('Wizard', 'Clone'),
  ('Wizard', 'Cloudkill'),
  ('Wizard', 'Color Spray'),
  ('Wizard', 'Comprehend Languages'),
  ('Wizard', 'Cone of Cold'),
  ('Wizard', 'Confusion'),
  ('Wizard', 'Conjure Elemental'),
  ('Wizard', 'Conjure Minor Elementals'),
  ('Wizard', 'Contact Other Plane'),
  ('Wizard', 'Contingency'),
  ('Wizard', 'Continual Flame'),
  ('Wizard', 'Control Water'),
  ('Wizard', 'Control Weather'),
  ('Wizard', 'Counterspell'),
  ('Wizard', 'Create Undead'),
  ('Wizard', 'Creation'),
  ('Wizard', 'Dancing Lights'),
  ('Wizard', 'Darkness'),
  ('Wizard', 'Darkvision'),
  ('Wizard', 'Delayed Blast Fireball'),
  ('Wizard', 'Demiplane'),
  ('Wizard', 'Detect Magic'),
  ('Wizard', 'Detect Thoughts'),
  ('Wizard', 'Dimension Door'),
  ('Wizard', 'Disguise Self'),
  ('Wizard', 'Disintegrate'),
  ('Wizard', 'Dispel Magic'),
  ('Wizard', 'Dominate Monster'),
  ('Wizard', 'Dominate Person'),
  ('Wizard', 'Dream'),
  ('Wizard', 'Enlarge/Reduce'),
  ('Wizard', 'Etherealness'),
  ('Wizard', 'Expeditious Retreat'),
  ('Wizard', 'Eyebite'),
  ('Wizard', 'Fabricate'),
  ('Wizard', 'Faithful Hound'),
  ('Wizard', 'False Life'),
  ('Wizard', 'Fear'),
  ('Wizard', 'Feather Fall'),
  ('Wizard', 'Feeblemind'),
  ('Wizard', 'Find Familiar'),
  ('Wizard', 'Finger of Death'),
  ('Wizard', 'Fire Bolt'),
  ('Wizard', 'Fire Shield'),
  ('Wizard', 'Fireball'),
  ('Wizard', 'Flaming Sphere'),
  ('Wizard', 'Flesh to Stone'),
  ('Wizard', 'Floating Disk'),
  ('Wizard', 'Fly'),
  ('Wizard', 'Fog Cloud'),
  ('Wizard', 'Forcecage'),
  ('Wizard', 'Foresight'),
  ('Wizard', 'Freezing Sphere'),
  ('Wizard', 'Gaseous Form'),
  ('Wizard', 'Gate'),
  ('Wizard', 'Geas'),
  ('Wizard', 'Gentle Repose'),
  ('Wizard', 'Globe of Invulnerability'),
  ('Wizard', 'Glyph of Warding'),
  ('Wizard', 'Grease'),
  ('Wizard', 'Greater Invisibility'),
  ('Wizard', 'Guards and Wards'),
  ('Wizard', 'Gust of Wind'),
  ('Wizard', 'Hallucinatory Terrain'),
  ('Wizard', 'Haste'),
  ('Wizard', 'Hideous Laughter'),
  ('Wizard', 'Hold Monster'),
  ('Wizard', 'Hold Person'),
  ('Wizard', 'Hypnotic Pattern'),
  ('Wizard', 'Ice Storm'),
  ('Wizard', 'Identify'),
  ('Wizard', 'Illusory Script'),
  ('Wizard', 'Imprisonment'),
  ('Wizard', 'Incendiary Cloud'),
  ('Wizard', 'Instant Summons'),
  ('Wizard', 'Invisibility'),
  ('Wizard', 'Irresistible Dance'),
  ('Wizard', 'Jump'),
  ('Wizard', 'Knock'),
  ('Wizard', 'Legend Lore'),
  ('Wizard', 'Levitate'),
  ('Wizard', 'Light'),
  ('Wizard', 'Lightning Bolt'),
  ('Wizard', 'Locate Creature'),
  ('Wizard', 'Locate Object'),
  ('Wizard', 'Longstrider'),
  ('Wizard', 'Mage Armor'),
  ('Wizard', 'Mage Hand'),
  ('Wizard', 'Magic Circle'),
  ('Wizard', 'Magic Jar'),
  ('Wizard', 'Magic Missile'),
  ('Wizard', 'Magic Mouth'),
  ('Wizard', 'Magic Weapon'),
  ('Wizard', 'Magnificent Mansion'),
  ('Wizard', 'Major Image'),
  ('Wizard', 'Mass Suggestion'),
  ('Wizard', 'Maze'),
  ('Wizard', 'Mending'),
  ('Wizard', 'Message'),
  ('Wizard', 'Meteor Swarm'),
  ('Wizard', 'Mind Blank'),
  ('Wizard', 'Minor Illusion'),
  ('Wizard', 'Mirage Arcane'),
  ('Wizard', 'Mirror Image'),
  ('Wizard', 'Mislead'),
  ('Wizard', 'Misty Step'),
  ('Wizard', 'Modify Memory'),
  ('Wizard', 'Move Earth'),
  ('Wizard', 'Nondetection'),
  ('Wizard', 'Passwall'),
  ('Wizard', 'Phantasmal Killer'),
  ('Wizard', 'Phantom Steed'),
  ('Wizard', 'Planar Binding'),
  ('Wizard', 'Plane Shift'),
  ('Wizard', 'Poison Spray'),
  ('Wizard', 'Polymorph'),
  ('Wizard', 'Power Word Kill'),
  ('Wizard', 'Power Word Stun'),
  ('Wizard', 'Prestidigitation'),
  ('Wizard', 'Prismatic Spray'),
  ('Wizard', 'Prismatic Wall'),
  ('Wizard', 'Private Sanctum'),
  ('Wizard', 'Programmed Illusion'),
  ('Wizard', 'Project Image'),
  ('Wizard', 'Protection from Energy'),
  ('Wizard', 'Protection from Evil and Good'),
  ('Wizard', 'Ray of Enfeeblement'),
  ('Wizard', 'Ray of Frost'),
  ('Wizard', 'Remove Curse'),
  ('Wizard', 'Resilient Sphere'),
  ('Wizard', 'Reverse Gravity'),
  ('Wizard', 'Rope Trick'),
  ('Wizard', 'Scorching Ray'),
  ('Wizard', 'Scrying'),
  ('Wizard', 'Secret Chest'),
  ('Wizard', 'See Invisibility'),
  ('Wizard', 'Seeming'),
  ('Wizard', 'Sending'),
  ('Wizard', 'Sequester'),
  ('Wizard', 'Shapechange'),
  ('Wizard', 'Shatter'),
  ('Wizard', 'Shield'),
  ('Wizard', 'Shocking Grasp'),
  ('Wizard', 'Silent Image'),
  ('Wizard', 'Simulacrum'),
  ('Wizard', 'Sleep'),
  ('Wizard', 'Sleet Storm'),
  ('Wizard', 'Slow'),
  ('Wizard', 'Spider Climb'),
  ('Wizard', 'Stinking Cloud'),
  ('Wizard', 'Stone Shape'),
  ('Wizard', 'Stoneskin'),
  ('Wizard', 'Suggestion'),
  ('Wizard', 'Sunbeam'),
  ('Wizard', 'Sunburst'),
  ('Wizard', 'Symbol'),
  ('Wizard', 'Telekinesis'),
  ('Wizard', 'Telepathic Bond'),
  ('Wizard', 'Teleport'),
  ('Wizard', 'Teleportation Circle'),
  ('Wizard', 'Thunderwave'),
  ('Wizard', 'Time Stop'),
  ('Wizard', 'Tiny Hut'),
  ('Wizard', 'Tongues'),
  ('Wizard', 'True Polymorph'),
  ('Wizard', 'True Seeing'),
  ('Wizard', 'True Strike'),
  ('Wizard', 'Unseen Servant'),
  ('Wizard', 'Vampiric Touch'),
  ('Wizard', 'Wall of Fire'),
  ('Wizard', 'Wall of Force'),
  ('Wizard', 'Wall of Ice'),
  ('Wizard', 'Wall of Stone'),
  ('Wizard', 'Water Breathing'),
  ('Wizard', 'Web'),
  ('Wizard', 'Weird'),
  ('Wizard', 'Wish')
)
update public.library_spells ls
set classes =
  coalesce(
    (select array_agg(l.class_name order by array_position(array['Artificer','Bard','Cleric','Druid','Paladin','Ranger','Sorcerer','Warlock','Wizard'], l.class_name))
       from lists l where l.spell_name = ls.name),
    '{}'::text[]
  )
  || array(
    select c from unnest(ls.classes) with ordinality as t(c, n)
    where c not in ('Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Wizard')
    order by n
  )
where ls.source = 'srd-2014';
