-- Library subclass spells: the spells each official subclass gives a character.
--
-- GENERATED by scripts/library-subclass-spells.ts from the same data as
-- src/data/librarySubclassSpells.ts, so a newly imported subclass and a row that
-- exists today hold the same thing. Read that file's header for the sources
-- (SRD 5.1 / 5.2.1 under CC-BY-4.0; Tome of Heroes, Open5e and Tal'Dorei content
-- under OGL 1.0a via Open5e) and for what was left out.
--
-- Rows are matched on the official identity (source_document_key,
-- source_record_key, ruleset), never on uuid. Only library rows (user_id is
-- null) are touched, and only while all four columns are still empty, so a
-- hand edit made in the Codex is never overwritten and a second run changes
-- nothing. An empty library (CI, a fresh database) matches no row.

update public.custom_subclasses s
   set granted_spells = v.granted_spells,
       spell_variants = v.spell_variants,
       spell_variant_label = v.spell_variant_label,
       expanded_spells = v.expanded_spells,
       expanded_spell_variants = v.expanded_spell_variants
  from (values
    -- Cleric / Demise Domain (2014, open5e)
    ('open5e', 'open5e_demise-domain', '2014', '{"1":["srd_false_life","srd_ray_of_sickness"],"3":["srd_blindnessdeafness","srd_ray_of_enfeeblement"],"5":["srd_srd_animate_dead","srd_vampiric_touch"],"7":["srd_blight","srd_srd_death_ward"],"9":["srd_antilife_shell","srd_cloudkill"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Cleric / Mischief Domain (2014, open5e)
    ('open5e', 'open5e_mischief-domain', '2014', '{"1":["srd_srd_charm_person","srd_disguise_self"],"3":["srd_mirror_image","srd_pass_without_trace"],"5":["srd_srd_blink","srd_srd_dispel_magic"],"7":["srd_dimension_door","srd_polymorph"],"9":["srd_dominate_person","srd_modify_memory"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Paladin / Oathless Betrayer (2014, open5e)
    ('open5e', 'open5e_oathless-betrayer', '2014', '{"3":["srd_hellish_rebuke","srd_inflict_wounds"],"5":["srd_darkness"],"9":["srd_srd_animate_dead","srd_bestow_curse"],"13":["srd_blight","srd_confusion"],"17":["srd_contagion","srd_dominate_person"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Cleric / Storm Domain (2014, open5e)
    ('open5e', 'open5e_storm-domain', '2014', '{"1":["srd_fog_cloud","srd_thunderwave"],"3":["srd_gust_of_wind","srd_shatter"],"5":["srd_call_lightning","srd_sleet_storm"],"7":["srd_control_water","srd_ice_storm"],"9":["srd_insect_plague"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Warlock / The Ancient Fey Court (2014, open5e)
    ('open5e', 'open5e_the-ancient-fey-court', '2014', '{}'::jsonb, '{}'::jsonb, null::text, '{"1":["srd_faerie_fire","srd_sleep"],"2":["srd_calm_emotions"],"3":["srd_srd_blink","srd_plant_growth"],"4":["srd_dominate_beast","srd_greater_invisibility"],"5":["srd_dominate_person","srd_seeming"]}'::jsonb, '{}'::jsonb),
    -- Warlock / The Great Elder Thing (2014, open5e)
    ('open5e', 'open5e_the-great-elder-thing', '2014', '{}'::jsonb, '{}'::jsonb, null::text, '{"1":["srd_hideous_laughter"],"2":["srd_detect_thoughts"],"3":["srd_clairvoyance","srd_sending"],"4":["srd_dominate_beast","srd_black_tentacles"],"5":["srd_dominate_person","srd_telekinesis"]}'::jsonb, '{}'::jsonb),
    -- Druid / Circle of the Land (2014, srd-2014)
    ('srd-2014', 'srd_circle-of-the-land', '2014', '{}'::jsonb, '{"Arctic":{"3":["srd_hold_person","srd_spike_growth"],"5":["srd_sleet_storm","srd_slow"],"7":["srd_freedom_of_movement","srd_ice_storm"],"9":["srd_commune_with_nature","srd_cone_of_cold"]},"Coast":{"3":["srd_mirror_image","srd_misty_step"],"5":["srd_water_breathing","srd_water_walk"],"7":["srd_control_water","srd_freedom_of_movement"],"9":["srd_conjure_elemental","srd_scrying"]},"Desert":{"3":["srd_blur","srd_silence"],"5":["srd_srd_create_food_and_water","srd_protection_from_energy"],"7":["srd_blight","srd_hallucinatory_terrain"],"9":["srd_insect_plague","srd_wall_of_stone"]},"Forest":{"3":["srd_srd_barkskin","srd_spider_climb"],"5":["srd_call_lightning","srd_plant_growth"],"7":["srd_divination","srd_freedom_of_movement"],"9":["srd_commune_with_nature","srd_tree_stride"]},"Grassland":{"3":["srd_invisibility","srd_pass_without_trace"],"5":["srd_srd_daylight","srd_haste"],"7":["srd_divination","srd_freedom_of_movement"],"9":["srd_dream","srd_insect_plague"]},"Mountain":{"3":["srd_spider_climb","srd_spike_growth"],"5":["srd_lightning_bolt","srd_meld_into_stone"],"7":["srd_stone_shape","srd_stoneskin"],"9":["srd_passwall","srd_wall_of_stone"]},"Swamp":{"3":["srd_acid_arrow","srd_darkness"],"5":["srd_water_walk","srd_stinking_cloud"],"7":["srd_freedom_of_movement","srd_srd_locate_creature"],"9":["srd_insect_plague","srd_scrying"]}}'::jsonb, 'Terrain', '{}'::jsonb, '{}'::jsonb),
    -- Cleric / Life Domain (2014, srd-2014)
    ('srd-2014', 'srd_life-domain', '2014', '{"1":["srd_srd_bless","srd_srd_cure_wounds"],"3":["srd_srd_lesser_restoration","srd_spiritual_weapon"],"5":["srd_beacon_of_hope","srd_srd_revivify"],"7":["srd_srd_death_ward","srd_guardian_of_faith"],"9":["srd_mass_cure_wounds","srd_srd_raise_dead"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Paladin / Oath of Devotion (2014, srd-2014)
    ('srd-2014', 'srd_oath-of-devotion', '2014', '{"3":["srd_srd_protection_from_evil_and_good","srd_sanctuary"],"5":["srd_srd_lesser_restoration","srd_srd_zone_of_truth"],"9":["srd_beacon_of_hope","srd_srd_dispel_magic"],"13":["srd_freedom_of_movement","srd_guardian_of_faith"],"17":["srd_commune","srd_flame_strike"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Warlock / The Fiend (2014, srd-2014)
    ('srd-2014', 'srd_the-fiend', '2014', '{}'::jsonb, '{}'::jsonb, null::text, '{"1":["srd_burning_hands","srd_srd_command"],"2":["srd_blindnessdeafness","srd_scorching_ray"],"3":["srd_fireball","srd_stinking_cloud"],"4":["srd_fire_shield","srd_wall_of_fire"],"5":["srd_flame_strike","srd_hallow"]}'::jsonb, '{}'::jsonb),
    -- Druid / Circle of the Land (2024, srd-2024)
    ('srd-2024', 'srd-2024_circle-of-the-land', '2024', '{}'::jsonb, '{"Arid":{"3":["srd_srd_2024_blur","srd_srd_2024_burning_hands","srd_srd_2024_fire_bolt"],"5":["srd_srd_2024_fireball"],"7":["srd_srd_2024_blight"],"9":["srd_srd_2024_wall_of_stone"]},"Polar":{"3":["srd_srd_2024_fog_cloud","srd_srd_2024_hold_person","srd_srd_2024_ray_of_frost"],"5":["srd_srd_2024_sleet_storm"],"7":["srd_srd_2024_ice_storm"],"9":["srd_srd_2024_cone_of_cold"]},"Temperate":{"3":["srd_srd_2024_misty_step","srd_srd_2024_shocking_grasp","srd_srd_2024_sleep"],"5":["srd_srd_2024_lightning_bolt"],"7":["srd_srd_2024_freedom_of_movement"],"9":["srd_srd_2024_tree_stride"]},"Tropical":{"3":["srd_srd_2024_acid_splash","srd_srd_2024_ray_of_sickness","srd_srd_2024_web"],"5":["srd_srd_2024_stinking_cloud"],"7":["srd_srd_2024_polymorph"],"9":["srd_srd_2024_insect_plague"]}}'::jsonb, 'Land type', '{}'::jsonb, '{}'::jsonb),
    -- Warlock / Fiend Patron (2024, srd-2024)
    ('srd-2024', 'srd-2024_fiend-patron', '2024', '{"3":["srd_srd_2024_burning_hands","srd_srd_2024_command","srd_srd_2024_scorching_ray","srd_srd_2024_suggestion"],"5":["srd_srd_2024_fireball","srd_srd_2024_stinking_cloud"],"7":["srd_srd_2024_fire_shield","srd_srd_2024_wall_of_fire"],"9":["srd_srd_2024_geas","srd_srd_2024_insect_plague"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Cleric / Life Domain (2024, srd-2024)
    ('srd-2024', 'srd-2024_life-domain', '2024', '{"3":["srd_srd_2024_aid","srd_srd_2024_bless","srd_srd_2024_cure_wounds","srd_srd_2024_lesser_restoration"],"5":["srd_srd_2024_mass_healing_word","srd_srd_2024_revivify"],"7":["srd_srd_2024_aura_of_life","srd_srd_2024_death_ward"],"9":["srd_srd_2024_greater_restoration","srd_srd_2024_mass_cure_wounds"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Paladin / Oath of Devotion (2024, srd-2024)
    ('srd-2024', 'srd-2024_oath-of-devotion', '2024', '{"3":["srd_srd_2024_protection_from_evil_and_good","srd_srd_2024_shield_of_faith"],"5":["srd_srd_2024_aid","srd_srd_2024_zone_of_truth"],"9":["srd_srd_2024_beacon_of_hope","srd_srd_2024_dispel_magic"],"13":["srd_srd_2024_freedom_of_movement","srd_srd_2024_guardian_of_faith"],"17":["srd_srd_2024_commune","srd_srd_2024_flame_strike"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Cleric / Blood Domain (2014, tdcs)
    ('tdcs', 'tdcs_blood-domain', '2014', '{"1":["srd_sleep","srd_ray_of_sickness"],"3":["srd_ray_of_enfeeblement"],"5":["srd_haste","srd_slow"],"7":["srd_blight","srd_stoneskin"],"9":["srd_dominate_person","srd_hold_monster"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Warlock / Ancient Dragons (2014, toh)
    ('toh', 'toh_ancient-dragons', '2014', '{}'::jsonb, '{}'::jsonb, null::text, '{"1":["srd_inflict_wounds","srd_magic_missile"],"2":["srd_heat_metal","srd_scorching_ray"],"3":["srd_srd_dispel_magic","srd_lightning_bolt"],"4":["srd_greater_invisibility","srd_ice_storm"],"5":["srd_cloudkill","srd_flame_strike"]}'::jsonb, '{}'::jsonb),
    -- Warlock / Animal Lords (2014, toh)
    ('toh', 'toh_animal-lords', '2014', '{}'::jsonb, '{}'::jsonb, 'Affinity', '{"1":["srd_speak_with_animals"],"2":["srd_mark_prey"],"3":["srd_srd_conjure_animals"],"4":["srd_polymorph"],"5":["srd_commune_with_nature"]}'::jsonb, '{"Air":{"1":["srd_thunderwave"],"2":["srd_gust_of_wind"],"3":["srd_fly"],"4":["srd_storm_of_wings"],"5":["srd_insect_plague"]},"Earth":{"1":["srd_longstrider"],"2":["srd_pass_without_trace"],"4":["srd_sudden_stampede"],"5":["srd_hold_monster"]},"Water":{"1":["srd_fog_cloud"],"2":["srd_misty_step"],"3":["srd_water_breathing"],"4":["srd_control_water"],"5":["srd_cloudkill"]}}'::jsonb),
    -- Druid / Circle of Bees (2014, toh)
    ('toh', 'toh_circle-of-bees', '2014', '{"3":["srd_blur","srd_bombardment_of_stings"],"5":["srd_fly","srd_haste"],"7":["srd_giant_insect","srd_srd_locate_creature"],"9":["srd_insect_plague","srd_telepathic_bond"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Druid / Circle of the Green (2014, toh)
    ('toh', 'toh_circle-of-the-green', '2014', '{"2":["srd_srd_entangle","srd_goodberry"],"3":["srd_srd_barkskin","srd_spike_growth"],"5":["srd_speak_with_plants","srd_vine_carpet"],"7":["srd_dreamwine","srd_hallucinatory_terrain"],"9":["srd_enchanted_bloom","srd_tree_stride"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Druid / Circle of the Shapeless (2014, toh)
    ('toh', 'toh_circle-of-the-shapeless', '2014', '{"3":["srd_enlargereduce","srd_spider_climb"],"5":["srd_iron_gut","srd_meld_into_stone"],"7":["srd_blight","srd_freedom_of_movement"],"9":["srd_contagion","srd_seeming"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Druid / Circle of Wind (2014, toh)
    ('toh', 'toh_circle-of-wind', '2014', '{"3":["srd_blur","srd_gust_of_wind"],"5":["srd_fly","srd_lightning_bolt"],"7":["srd_conjure_minor_elementals","srd_freedom_of_movement"],"9":["srd_cloudkill","srd_conjure_elemental"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Ranger / Grove Warden (2014, toh)
    ('toh', 'toh_grove-warden', '2014', '{"3":["srd_srd_entangle"],"5":["srd_srd_branding_smite"],"9":["srd_speak_with_plants"],"13":["srd_hallucinatory_terrain"],"17":["srd_animate_objects"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Ranger / Haunted Warden (2014, toh)
    ('toh', 'toh_haunted-warden', '2014', '{"3":["srd_false_life"],"5":["srd_invisibility"],"9":["srd_speak_with_dead"],"13":["srd_srd_death_ward"],"17":["srd_srd_dispel_evil_and_good"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Cleric / Hunt Domain (2014, toh)
    ('toh', 'toh_hunt-domain', '2014', '{"1":["srd_illuminate_spoor"],"3":["srd_instant_snare","srd_mark_prey"],"5":["srd_going_in_circles","srd_tracer"],"7":["srd_heart_seeking_arrow","srd_hunting_stand"],"9":["srd_harrying_hounds","srd_maim"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Warlock / Hunter in Darkness (2014, toh)
    ('toh', 'toh_hunter-in-darkness', '2014', '{}'::jsonb, '{}'::jsonb, null::text, '{"1":["srd_bloodhound","srd_hunters_endurance"],"2":["srd_instant_snare","srd_mark_prey"],"3":["srd_clairvoyance","srd_nondetection"],"4":["srd_harry","srd_heart_seeking_arrow"],"5":["srd_killing_fields","srd_legend_lore"]}'::jsonb, '{}'::jsonb),
    -- Cleric / Mercy Domain (2014, toh)
    ('toh', 'toh_mercy-domain', '2014', '{"1":["srd_srd_divine_favor","srd_healing_word"],"3":["srd_srd_aid","srd_ray_of_enfeeblement"],"5":["srd_bardo","srd_srd_revivify"],"7":["srd_srd_death_ward","srd_sacrificial_healing"],"9":["srd_antilife_shell","srd_srd_raise_dead"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Paladin / Oath of Justice (2014, toh)
    ('toh', 'toh_oath-of-justice', '2014', '{"3":["srd_color_spray","srd_guiding_bolt"],"5":["srd_guiding_bolt","srd_srd_zone_of_truth"],"9":["srd_lightning_bolt","srd_slow"],"13":["srd_faithful_hound","srd_srd_locate_creature"],"17":["srd_arcane_hand","srd_hold_monster"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Paladin / Oath of Safeguarding (2014, toh)
    ('toh', 'toh_oath-of-safeguarding', '2014', '{"3":["srd_longstrider","srd_srd_shield_of_faith"],"5":["srd_hold_person","srd_spike_growth"],"9":["srd_beacon_of_hope","srd_spirit_guardians"],"13":["srd_dimension_door","srd_stoneskin"],"17":["srd_greater_restoration","srd_wall_of_stone"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Paladin / Oath of the Elements (2014, toh)
    ('toh', 'toh_oath-of-the-elements', '2014', '{"3":["srd_burning_hands","srd_thunderwave"],"5":["srd_acid_arrow","srd_flaming_sphere"],"9":["srd_call_lightning","srd_protection_from_energy"],"13":["srd_conjure_minor_elementals","srd_ice_storm"],"17":["srd_conjure_elemental","srd_wall_of_stone"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Paladin / Oath of the Guardian (2014, toh)
    ('toh', 'toh_oath-of-the-guardian', '2014', '{"3":["srd_litany_of_sure_hands","srd_srd_shield_of_faith"],"5":["srd_mantle_of_the_brave","srd_spiritual_weapon"],"9":["srd_beacon_of_hope","srd_invested_champion"],"13":["srd_srd_banishment","srd_inspiring_speech"],"17":["srd_creation","srd_hallow"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Paladin / Oath of the Hearth (2014, toh)
    ('toh', 'toh_oath-of-the-hearth', '2014', '{"3":["srd_burning_hands","srd_sanctuary"],"5":["srd_calm_emotions","srd_flame_blade"],"9":["srd_protection_from_energy","srd_tiny_hut"],"13":["srd_guardian_of_faith","srd_wall_of_fire"],"17":["srd_flame_strike","srd_hallow"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Paladin / Oath of the Plaguetouched (2014, toh)
    ('toh', 'toh_oath-of-the-plaguetouched', '2014', '{"3":["srd_bane","srd_srd_protection_from_evil_and_good"],"5":["srd_enhance_ability","srd_srd_lesser_restoration"],"9":["srd_life_from_death","srd_srd_remove_curse"],"13":["srd_blight","srd_freedom_of_movement"],"17":["srd_greater_restoration","srd_hold_monster"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Warlock / Old Wood (2014, toh)
    ('toh', 'toh_old-wood', '2014', '{}'::jsonb, '{}'::jsonb, null::text, '{"1":["srd_srd_animal_friendship","srd_faerie_fire"],"2":["srd_animal_messenger","srd_spike_growth"],"3":["srd_srd_conjure_animals","srd_protection_from_energy"],"4":["srd_conjure_woodland_beings","srd_giant_insect"],"5":["srd_greater_restoration","srd_tree_stride"]}'::jsonb, '{}'::jsonb),
    -- Cleric / Portal Domain (2014, toh)
    ('toh', 'toh_portal-domain', '2014', '{"1":["srd_adjust_position","srd_srd_expeditious_retreat"],"3":["srd_glyph_of_shifting","srd_misty_step"],"5":["srd_dimensional_shove","srd_portal_jaunt"],"7":["srd_dimension_door","srd_reposition"],"9":["srd_pierce_the_veil","srd_teleportation_circle"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Warlock / Primordial (2014, toh)
    ('toh', 'toh_primordial', '2014', '{}'::jsonb, '{}'::jsonb, null::text, '{"1":["srd_srd_command","srd_healing_word"],"2":["srd_srd_lesser_restoration","srd_mud"],"3":["srd_power_word_fling","srd_srd_revivify"],"4":["srd_power_word_rend","srd_stone_shape"],"5":["srd_conjure_elemental","srd_creation"]}'::jsonb, '{}'::jsonb),
    -- Cleric / Serpent Domain (2014, toh)
    ('toh', 'toh_serpent-domain', '2014', '{"1":["srd_srd_charm_person","srd_srd_find_familiar"],"3":["srd_enthrall","srd_srd_protection_from_poison"],"5":["srd_srd_conjure_animals","srd_hypnotic_pattern"],"7":["srd_freedom_of_movement","srd_polymorph"],"9":["srd_dominate_person","srd_mislead"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Cleric / Shadow Domain (2014, toh)
    ('toh', 'toh_shadow-domain', '2014', '{"1":["srd_bane","srd_false_life"],"3":["srd_blindnessdeafness","srd_darkness"],"5":["srd_srd_blink","srd_fear"],"7":["srd_black_tentacles","srd_greater_invisibility"],"9":["srd_cone_of_cold","srd_dream"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Ranger / Snake Speaker (2014, toh)
    ('toh', 'toh_snake-speaker', '2014', '{"3":["srd_srd_charm_person"],"5":["srd_suggestion"],"9":["srd_tongues"],"13":["srd_confusion"],"17":["srd_dominate_person"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Cleric / Vermin Domain (2014, toh)
    ('toh', 'toh_vermin-domain', '2014', '{"1":["srd_srd_detect_poison_and_disease","srd_speak_with_animals"],"3":["srd_spider_climb","srd_web"],"5":["srd_srd_conjure_animals","srd_fear"],"7":["srd_dominate_beast","srd_giant_insect"],"9":["srd_contagion","srd_insect_plague"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Ranger / Wasteland Strider (2014, toh)
    ('toh', 'toh_wasteland-strider', '2014', '{"3":["srd_protection_from_the_void"],"5":["srd_calm_emotions"],"9":["srd_srd_dispel_magic"],"13":["srd_srd_banishment"],"17":["srd_hold_monster"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Cleric / Wind Domain (2014, toh)
    ('toh', 'toh_wind-domain', '2014', '{"1":["srd_feather_fall","srd_thunderwave"],"3":["srd_gust_of_wind","srd_misty_step"],"5":["srd_fly","srd_wind_wall"],"7":["srd_conjure_minor_elementals","srd_freedom_of_movement"],"9":["srd_cloudkill","srd_conjure_elemental"]}'::jsonb, '{}'::jsonb, null::text, '{}'::jsonb, '{}'::jsonb),
    -- Warlock / Wyrdweaver (2014, toh)
    ('toh', 'toh_wyrdweaver', '2014', '{}'::jsonb, '{}'::jsonb, null::text, '{"1":["srd_bane","srd_faerie_fire"],"2":["srd_blur","srd_frenzied_bolt"],"3":["srd_bestow_curse","srd_hypnotic_pattern"],"4":["srd_compulsion","srd_reset"],"5":["srd_battle_mind","srd_mislead"]}'::jsonb, '{}'::jsonb)
  ) as v(source_document_key, source_record_key, ruleset, granted_spells, spell_variants, spell_variant_label, expanded_spells, expanded_spell_variants)
 where s.user_id is null
   and s.source_document_key = v.source_document_key
   and s.source_record_key = v.source_record_key
   and s.ruleset = v.ruleset
   and s.granted_spells = '{}'::jsonb
   and s.spell_variants = '{}'::jsonb
   and s.expanded_spells = '{}'::jsonb
   and s.expanded_spell_variants = '{}'::jsonb;
