// GENERATED by `npm run doll:templates` (scripts/generate-dolls.ts). Never edit by hand:
// the sheets are AI renders and the layouts are measured from them, so a hand edit
// describes a picture that does not exist. Regenerate the command to change either.
import type { DollLayout, DollSheetKey, DollTemplateSize } from "@edge-shared/paperDoll/types.ts";
import { artUrl } from "@/lib/assets/artUrl";

/** The template sheets' URLs (app art, through the CDN). */
export const DOLL_TEMPLATE_SHEETS: Record<DollTemplateSize, Record<DollSheetKey, string>> = {
  small: {
    garb: artUrl("/assets/doll/small-garb.webp"),
    armour: artUrl("/assets/doll/small-armour.webp"),
    burden: artUrl("/assets/doll/small-burden.webp"),
  },
  medium: {
    garb: artUrl("/assets/doll/medium-garb.webp"),
    armour: artUrl("/assets/doll/medium-armour.webp"),
    burden: artUrl("/assets/doll/medium-burden.webp"),
  },
};

/** Per-piece fits measured from each template's own sheets. */
export const DOLL_TEMPLATE_LAYOUTS: Record<DollTemplateSize, DollLayout> = {
  "small": {
    "anatomy": {
      "head": {
        "x0": 172,
        "x1": 353,
        "y0": 75,
        "y1": 243
      },
      "shoulders": {
        "x0": 118,
        "x1": 409,
        "y": 347
      },
      "feetY": 945,
      "centerX": 264
    },
    "figureShift": {
      "underclothes": {
        "dx": 0,
        "dy": 0
      },
      "clothes": {
        "dx": 4,
        "dy": -1
      },
      "robes": {
        "dx": 17,
        "dy": -2
      },
      "armour_light": {
        "dx": 1,
        "dy": -3
      },
      "armour_medium": {
        "dx": 6,
        "dy": -3
      },
      "armour_heavy": {
        "dx": 18,
        "dy": -4
      }
    },
    "cuts": {
      "garb": [
        517,
        1012
      ],
      "armour": [
        517,
        1022
      ],
      "burden": [
        478,
        981
      ]
    }
  },
  "medium": {
    "anatomy": {
      "head": {
        "x0": 200,
        "x1": 313,
        "y0": 69,
        "y1": 193
      },
      "shoulders": {
        "x0": 128,
        "x1": 389,
        "y": 298
      },
      "feetY": 946,
      "centerX": 257
    },
    "figureShift": {
      "underclothes": {
        "dx": 0,
        "dy": 0
      },
      "clothes": {
        "dx": 1,
        "dy": 0
      },
      "robes": {
        "dx": 3,
        "dy": 0
      },
      "armour_light": {
        "dx": -1,
        "dy": -2
      },
      "armour_medium": {
        "dx": 0,
        "dy": -2
      },
      "armour_heavy": {
        "dx": 0,
        "dy": -3
      }
    },
    "cuts": {
      "garb": [
        513,
        1019
      ],
      "armour": [
        513,
        1024
      ],
      "burden": [
        475,
        995
      ]
    }
  }
};
