// GENERATED by scripts/library-subclass-spells.ts. Do not edit by hand; edit the
// script's inputs in scripts/data/ and run it again.
/**
 * The spells the library subclasses give a character (the subclass-spells epic).
 *
 * Each entry is matched to its library row by the identity every official row
 * already carries, (source_document_key, source_record_key, ruleset), never by
 * uuid, which differs between databases. The importer reads this for a newly
 * created library subclass; the migration writes the same data into the rows
 * that exist. Both come from one generator run.
 *
 * - `granted_spells`: always prepared, keyed by CLASS level.
 * - `spell_variants` / `spell_variant_label`: grants that depend on a choice
 *   (Circle of the Land's terrain or land type), option then class level.
 * - `expanded_spells`: a 2014 Warlock patron's expanded list, keyed by SPELL
 *   level. The character still picks these, so they are not granted.
 * - `expanded_spell_variants`: the same, when it depends on a choice (Animal
 *   Lords' affinity); option then spell level, labelled by `spell_variant_label`.
 *
 * ## Where it came from
 *
 * - The eight SRD subclasses (SRD 5.1 and SRD 5.2.1, CC-BY-4.0): read from the
 *   official PDFs and cross-checked equal to Open5e's text for the same
 *   subclass, spell by spell.
 * - The third-party subclasses (Tome of Heroes, Open5e's own and Tal'Dorei
 *   Campaign Setting content, OGL 1.0a via Open5e): parsed from the spell
 *   tables in Open5e's v2 class features, then matched to library spell ids
 *   by name within the same ruleset. A spell is never matched across rulesets.
 * - Every id below is checked against the library's spell ids for its ruleset
 *   when the file is generated and again by librarySubclassSpells.test.ts.
 *
 * ## Left out, on purpose
 *
 * Spells the books name that the library lacks:
 *   - Paladin / Oathless Betrayer (2014, open5e): crown of madness (not in the 2014 library)
 *   - Cleric / Storm Domain (2014, open5e): destructive wave (not in the 2014 library)
 *   - Warlock / The Ancient Fey Court (2014, open5e): phantasmal force (not in the 2014 library)
 *   - Warlock / The Great Elder Thing (2014, open5e): dissonant whispers (not in the 2014 library)
 *   - Warlock / The Great Elder Thing (2014, open5e): phantasmal force (not in the 2014 library)
 *   - Cleric / Blood Domain (2014, tdcs): crown of madness (not in the 2014 library)
 *   - Warlock / Animal Lords (2014, toh) Earth: phantom seed (not in the 2014 library)
 *   - Cleric / Hunt Domain (2014, toh): bloodbound (not in the 2014 library)
 *
 * Condition notes in a table ("snakes only") are dropped; the spell is granted.
 * A spell a source lists twice at one level is kept once.
 */

export type LevelMap = Record<string, string[]>;

export interface LibrarySubclassSpells {
  source_document_key: string;
  source_record_key: string;
  ruleset: "2014" | "2024";
  granted_spells: LevelMap;
  spell_variants: Record<string, LevelMap>;
  spell_variant_label: string | null;
  expanded_spells: LevelMap;
  expanded_spell_variants: Record<string, LevelMap>;
}

export const LIBRARY_SUBCLASS_SPELLS: readonly LibrarySubclassSpells[] = [
  // Cleric / Demise Domain (2014, open5e)
  {"source_document_key":"open5e","source_record_key":"open5e_demise-domain","ruleset":"2014","granted_spells":{"1":["srd_false_life","srd_ray_of_sickness"],"3":["srd_blindnessdeafness","srd_ray_of_enfeeblement"],"5":["srd_srd_animate_dead","srd_vampiric_touch"],"7":["srd_blight","srd_srd_death_ward"],"9":["srd_antilife_shell","srd_cloudkill"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Cleric / Mischief Domain (2014, open5e)
  {"source_document_key":"open5e","source_record_key":"open5e_mischief-domain","ruleset":"2014","granted_spells":{"1":["srd_srd_charm_person","srd_disguise_self"],"3":["srd_mirror_image","srd_pass_without_trace"],"5":["srd_srd_blink","srd_srd_dispel_magic"],"7":["srd_dimension_door","srd_polymorph"],"9":["srd_dominate_person","srd_modify_memory"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Paladin / Oathless Betrayer (2014, open5e)
  {"source_document_key":"open5e","source_record_key":"open5e_oathless-betrayer","ruleset":"2014","granted_spells":{"3":["srd_hellish_rebuke","srd_inflict_wounds"],"5":["srd_darkness"],"9":["srd_srd_animate_dead","srd_bestow_curse"],"13":["srd_blight","srd_confusion"],"17":["srd_contagion","srd_dominate_person"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Cleric / Storm Domain (2014, open5e)
  {"source_document_key":"open5e","source_record_key":"open5e_storm-domain","ruleset":"2014","granted_spells":{"1":["srd_fog_cloud","srd_thunderwave"],"3":["srd_gust_of_wind","srd_shatter"],"5":["srd_call_lightning","srd_sleet_storm"],"7":["srd_control_water","srd_ice_storm"],"9":["srd_insect_plague"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Warlock / The Ancient Fey Court (2014, open5e)
  {"source_document_key":"open5e","source_record_key":"open5e_the-ancient-fey-court","ruleset":"2014","granted_spells":{},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{"1":["srd_faerie_fire","srd_sleep"],"2":["srd_calm_emotions"],"3":["srd_srd_blink","srd_plant_growth"],"4":["srd_dominate_beast","srd_greater_invisibility"],"5":["srd_dominate_person","srd_seeming"]},"expanded_spell_variants":{}},
  // Warlock / The Great Elder Thing (2014, open5e)
  {"source_document_key":"open5e","source_record_key":"open5e_the-great-elder-thing","ruleset":"2014","granted_spells":{},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{"1":["srd_hideous_laughter"],"2":["srd_detect_thoughts"],"3":["srd_clairvoyance","srd_sending"],"4":["srd_dominate_beast","srd_black_tentacles"],"5":["srd_dominate_person","srd_telekinesis"]},"expanded_spell_variants":{}},
  // Druid / Circle of the Land (2014, srd-2014)
  {"source_document_key":"srd-2014","source_record_key":"srd_circle-of-the-land","ruleset":"2014","granted_spells":{},"spell_variants":{"Arctic":{"3":["srd_hold_person","srd_spike_growth"],"5":["srd_sleet_storm","srd_slow"],"7":["srd_freedom_of_movement","srd_ice_storm"],"9":["srd_commune_with_nature","srd_cone_of_cold"]},"Coast":{"3":["srd_mirror_image","srd_misty_step"],"5":["srd_water_breathing","srd_water_walk"],"7":["srd_control_water","srd_freedom_of_movement"],"9":["srd_conjure_elemental","srd_scrying"]},"Desert":{"3":["srd_blur","srd_silence"],"5":["srd_srd_create_food_and_water","srd_protection_from_energy"],"7":["srd_blight","srd_hallucinatory_terrain"],"9":["srd_insect_plague","srd_wall_of_stone"]},"Forest":{"3":["srd_srd_barkskin","srd_spider_climb"],"5":["srd_call_lightning","srd_plant_growth"],"7":["srd_divination","srd_freedom_of_movement"],"9":["srd_commune_with_nature","srd_tree_stride"]},"Grassland":{"3":["srd_invisibility","srd_pass_without_trace"],"5":["srd_srd_daylight","srd_haste"],"7":["srd_divination","srd_freedom_of_movement"],"9":["srd_dream","srd_insect_plague"]},"Mountain":{"3":["srd_spider_climb","srd_spike_growth"],"5":["srd_lightning_bolt","srd_meld_into_stone"],"7":["srd_stone_shape","srd_stoneskin"],"9":["srd_passwall","srd_wall_of_stone"]},"Swamp":{"3":["srd_acid_arrow","srd_darkness"],"5":["srd_water_walk","srd_stinking_cloud"],"7":["srd_freedom_of_movement","srd_srd_locate_creature"],"9":["srd_insect_plague","srd_scrying"]}},"spell_variant_label":"Terrain","expanded_spells":{},"expanded_spell_variants":{}},
  // Cleric / Life Domain (2014, srd-2014)
  {"source_document_key":"srd-2014","source_record_key":"srd_life-domain","ruleset":"2014","granted_spells":{"1":["srd_srd_bless","srd_srd_cure_wounds"],"3":["srd_srd_lesser_restoration","srd_spiritual_weapon"],"5":["srd_beacon_of_hope","srd_srd_revivify"],"7":["srd_srd_death_ward","srd_guardian_of_faith"],"9":["srd_mass_cure_wounds","srd_srd_raise_dead"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Paladin / Oath of Devotion (2014, srd-2014)
  {"source_document_key":"srd-2014","source_record_key":"srd_oath-of-devotion","ruleset":"2014","granted_spells":{"3":["srd_srd_protection_from_evil_and_good","srd_sanctuary"],"5":["srd_srd_lesser_restoration","srd_srd_zone_of_truth"],"9":["srd_beacon_of_hope","srd_srd_dispel_magic"],"13":["srd_freedom_of_movement","srd_guardian_of_faith"],"17":["srd_commune","srd_flame_strike"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Warlock / The Fiend (2014, srd-2014)
  {"source_document_key":"srd-2014","source_record_key":"srd_the-fiend","ruleset":"2014","granted_spells":{},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{"1":["srd_burning_hands","srd_srd_command"],"2":["srd_blindnessdeafness","srd_scorching_ray"],"3":["srd_fireball","srd_stinking_cloud"],"4":["srd_fire_shield","srd_wall_of_fire"],"5":["srd_flame_strike","srd_hallow"]},"expanded_spell_variants":{}},
  // Druid / Circle of the Land (2024, srd-2024)
  {"source_document_key":"srd-2024","source_record_key":"srd-2024_circle-of-the-land","ruleset":"2024","granted_spells":{},"spell_variants":{"Arid":{"3":["srd_srd_2024_blur","srd_srd_2024_burning_hands","srd_srd_2024_fire_bolt"],"5":["srd_srd_2024_fireball"],"7":["srd_srd_2024_blight"],"9":["srd_srd_2024_wall_of_stone"]},"Polar":{"3":["srd_srd_2024_fog_cloud","srd_srd_2024_hold_person","srd_srd_2024_ray_of_frost"],"5":["srd_srd_2024_sleet_storm"],"7":["srd_srd_2024_ice_storm"],"9":["srd_srd_2024_cone_of_cold"]},"Temperate":{"3":["srd_srd_2024_misty_step","srd_srd_2024_shocking_grasp","srd_srd_2024_sleep"],"5":["srd_srd_2024_lightning_bolt"],"7":["srd_srd_2024_freedom_of_movement"],"9":["srd_srd_2024_tree_stride"]},"Tropical":{"3":["srd_srd_2024_acid_splash","srd_srd_2024_ray_of_sickness","srd_srd_2024_web"],"5":["srd_srd_2024_stinking_cloud"],"7":["srd_srd_2024_polymorph"],"9":["srd_srd_2024_insect_plague"]}},"spell_variant_label":"Land type","expanded_spells":{},"expanded_spell_variants":{}},
  // Warlock / Fiend Patron (2024, srd-2024)
  {"source_document_key":"srd-2024","source_record_key":"srd-2024_fiend-patron","ruleset":"2024","granted_spells":{"3":["srd_srd_2024_burning_hands","srd_srd_2024_command","srd_srd_2024_scorching_ray","srd_srd_2024_suggestion"],"5":["srd_srd_2024_fireball","srd_srd_2024_stinking_cloud"],"7":["srd_srd_2024_fire_shield","srd_srd_2024_wall_of_fire"],"9":["srd_srd_2024_geas","srd_srd_2024_insect_plague"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Cleric / Life Domain (2024, srd-2024)
  {"source_document_key":"srd-2024","source_record_key":"srd-2024_life-domain","ruleset":"2024","granted_spells":{"3":["srd_srd_2024_aid","srd_srd_2024_bless","srd_srd_2024_cure_wounds","srd_srd_2024_lesser_restoration"],"5":["srd_srd_2024_mass_healing_word","srd_srd_2024_revivify"],"7":["srd_srd_2024_aura_of_life","srd_srd_2024_death_ward"],"9":["srd_srd_2024_greater_restoration","srd_srd_2024_mass_cure_wounds"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Paladin / Oath of Devotion (2024, srd-2024)
  {"source_document_key":"srd-2024","source_record_key":"srd-2024_oath-of-devotion","ruleset":"2024","granted_spells":{"3":["srd_srd_2024_protection_from_evil_and_good","srd_srd_2024_shield_of_faith"],"5":["srd_srd_2024_aid","srd_srd_2024_zone_of_truth"],"9":["srd_srd_2024_beacon_of_hope","srd_srd_2024_dispel_magic"],"13":["srd_srd_2024_freedom_of_movement","srd_srd_2024_guardian_of_faith"],"17":["srd_srd_2024_commune","srd_srd_2024_flame_strike"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Cleric / Blood Domain (2014, tdcs)
  {"source_document_key":"tdcs","source_record_key":"tdcs_blood-domain","ruleset":"2014","granted_spells":{"1":["srd_sleep","srd_ray_of_sickness"],"3":["srd_ray_of_enfeeblement"],"5":["srd_haste","srd_slow"],"7":["srd_blight","srd_stoneskin"],"9":["srd_dominate_person","srd_hold_monster"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Warlock / Ancient Dragons (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_ancient-dragons","ruleset":"2014","granted_spells":{},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{"1":["srd_inflict_wounds","srd_magic_missile"],"2":["srd_heat_metal","srd_scorching_ray"],"3":["srd_srd_dispel_magic","srd_lightning_bolt"],"4":["srd_greater_invisibility","srd_ice_storm"],"5":["srd_cloudkill","srd_flame_strike"]},"expanded_spell_variants":{}},
  // Warlock / Animal Lords (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_animal-lords","ruleset":"2014","granted_spells":{},"spell_variants":{},"spell_variant_label":"Affinity","expanded_spells":{"1":["srd_speak_with_animals"],"2":["srd_mark_prey"],"3":["srd_srd_conjure_animals"],"4":["srd_polymorph"],"5":["srd_commune_with_nature"]},"expanded_spell_variants":{"Air":{"1":["srd_thunderwave"],"2":["srd_gust_of_wind"],"3":["srd_fly"],"4":["srd_storm_of_wings"],"5":["srd_insect_plague"]},"Earth":{"1":["srd_longstrider"],"2":["srd_pass_without_trace"],"4":["srd_sudden_stampede"],"5":["srd_hold_monster"]},"Water":{"1":["srd_fog_cloud"],"2":["srd_misty_step"],"3":["srd_water_breathing"],"4":["srd_control_water"],"5":["srd_cloudkill"]}}},
  // Druid / Circle of Bees (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_circle-of-bees","ruleset":"2014","granted_spells":{"3":["srd_blur","srd_bombardment_of_stings"],"5":["srd_fly","srd_haste"],"7":["srd_giant_insect","srd_srd_locate_creature"],"9":["srd_insect_plague","srd_telepathic_bond"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Druid / Circle of the Green (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_circle-of-the-green","ruleset":"2014","granted_spells":{"2":["srd_srd_entangle","srd_goodberry"],"3":["srd_srd_barkskin","srd_spike_growth"],"5":["srd_speak_with_plants","srd_vine_carpet"],"7":["srd_dreamwine","srd_hallucinatory_terrain"],"9":["srd_enchanted_bloom","srd_tree_stride"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Druid / Circle of the Shapeless (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_circle-of-the-shapeless","ruleset":"2014","granted_spells":{"3":["srd_enlargereduce","srd_spider_climb"],"5":["srd_iron_gut","srd_meld_into_stone"],"7":["srd_blight","srd_freedom_of_movement"],"9":["srd_contagion","srd_seeming"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Druid / Circle of Wind (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_circle-of-wind","ruleset":"2014","granted_spells":{"3":["srd_blur","srd_gust_of_wind"],"5":["srd_fly","srd_lightning_bolt"],"7":["srd_conjure_minor_elementals","srd_freedom_of_movement"],"9":["srd_cloudkill","srd_conjure_elemental"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Ranger / Grove Warden (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_grove-warden","ruleset":"2014","granted_spells":{"3":["srd_srd_entangle"],"5":["srd_srd_branding_smite"],"9":["srd_speak_with_plants"],"13":["srd_hallucinatory_terrain"],"17":["srd_animate_objects"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Ranger / Haunted Warden (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_haunted-warden","ruleset":"2014","granted_spells":{"3":["srd_false_life"],"5":["srd_invisibility"],"9":["srd_speak_with_dead"],"13":["srd_srd_death_ward"],"17":["srd_srd_dispel_evil_and_good"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Cleric / Hunt Domain (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_hunt-domain","ruleset":"2014","granted_spells":{"1":["srd_illuminate_spoor"],"3":["srd_instant_snare","srd_mark_prey"],"5":["srd_going_in_circles","srd_tracer"],"7":["srd_heart_seeking_arrow","srd_hunting_stand"],"9":["srd_harrying_hounds","srd_maim"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Warlock / Hunter in Darkness (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_hunter-in-darkness","ruleset":"2014","granted_spells":{},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{"1":["srd_bloodhound","srd_hunters_endurance"],"2":["srd_instant_snare","srd_mark_prey"],"3":["srd_clairvoyance","srd_nondetection"],"4":["srd_harry","srd_heart_seeking_arrow"],"5":["srd_killing_fields","srd_legend_lore"]},"expanded_spell_variants":{}},
  // Cleric / Mercy Domain (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_mercy-domain","ruleset":"2014","granted_spells":{"1":["srd_srd_divine_favor","srd_healing_word"],"3":["srd_srd_aid","srd_ray_of_enfeeblement"],"5":["srd_bardo","srd_srd_revivify"],"7":["srd_srd_death_ward","srd_sacrificial_healing"],"9":["srd_antilife_shell","srd_srd_raise_dead"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Paladin / Oath of Justice (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_oath-of-justice","ruleset":"2014","granted_spells":{"3":["srd_color_spray","srd_guiding_bolt"],"5":["srd_guiding_bolt","srd_srd_zone_of_truth"],"9":["srd_lightning_bolt","srd_slow"],"13":["srd_faithful_hound","srd_srd_locate_creature"],"17":["srd_arcane_hand","srd_hold_monster"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Paladin / Oath of Safeguarding (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_oath-of-safeguarding","ruleset":"2014","granted_spells":{"3":["srd_longstrider","srd_srd_shield_of_faith"],"5":["srd_hold_person","srd_spike_growth"],"9":["srd_beacon_of_hope","srd_spirit_guardians"],"13":["srd_dimension_door","srd_stoneskin"],"17":["srd_greater_restoration","srd_wall_of_stone"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Paladin / Oath of the Elements (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_oath-of-the-elements","ruleset":"2014","granted_spells":{"3":["srd_burning_hands","srd_thunderwave"],"5":["srd_acid_arrow","srd_flaming_sphere"],"9":["srd_call_lightning","srd_protection_from_energy"],"13":["srd_conjure_minor_elementals","srd_ice_storm"],"17":["srd_conjure_elemental","srd_wall_of_stone"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Paladin / Oath of the Guardian (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_oath-of-the-guardian","ruleset":"2014","granted_spells":{"3":["srd_litany_of_sure_hands","srd_srd_shield_of_faith"],"5":["srd_mantle_of_the_brave","srd_spiritual_weapon"],"9":["srd_beacon_of_hope","srd_invested_champion"],"13":["srd_srd_banishment","srd_inspiring_speech"],"17":["srd_creation","srd_hallow"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Paladin / Oath of the Hearth (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_oath-of-the-hearth","ruleset":"2014","granted_spells":{"3":["srd_burning_hands","srd_sanctuary"],"5":["srd_calm_emotions","srd_flame_blade"],"9":["srd_protection_from_energy","srd_tiny_hut"],"13":["srd_guardian_of_faith","srd_wall_of_fire"],"17":["srd_flame_strike","srd_hallow"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Paladin / Oath of the Plaguetouched (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_oath-of-the-plaguetouched","ruleset":"2014","granted_spells":{"3":["srd_bane","srd_srd_protection_from_evil_and_good"],"5":["srd_enhance_ability","srd_srd_lesser_restoration"],"9":["srd_life_from_death","srd_srd_remove_curse"],"13":["srd_blight","srd_freedom_of_movement"],"17":["srd_greater_restoration","srd_hold_monster"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Warlock / Old Wood (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_old-wood","ruleset":"2014","granted_spells":{},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{"1":["srd_srd_animal_friendship","srd_faerie_fire"],"2":["srd_animal_messenger","srd_spike_growth"],"3":["srd_srd_conjure_animals","srd_protection_from_energy"],"4":["srd_conjure_woodland_beings","srd_giant_insect"],"5":["srd_greater_restoration","srd_tree_stride"]},"expanded_spell_variants":{}},
  // Cleric / Portal Domain (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_portal-domain","ruleset":"2014","granted_spells":{"1":["srd_adjust_position","srd_srd_expeditious_retreat"],"3":["srd_glyph_of_shifting","srd_misty_step"],"5":["srd_dimensional_shove","srd_portal_jaunt"],"7":["srd_dimension_door","srd_reposition"],"9":["srd_pierce_the_veil","srd_teleportation_circle"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Warlock / Primordial (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_primordial","ruleset":"2014","granted_spells":{},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{"1":["srd_srd_command","srd_healing_word"],"2":["srd_srd_lesser_restoration","srd_mud"],"3":["srd_power_word_fling","srd_srd_revivify"],"4":["srd_power_word_rend","srd_stone_shape"],"5":["srd_conjure_elemental","srd_creation"]},"expanded_spell_variants":{}},
  // Cleric / Serpent Domain (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_serpent-domain","ruleset":"2014","granted_spells":{"1":["srd_srd_charm_person","srd_srd_find_familiar"],"3":["srd_enthrall","srd_srd_protection_from_poison"],"5":["srd_srd_conjure_animals","srd_hypnotic_pattern"],"7":["srd_freedom_of_movement","srd_polymorph"],"9":["srd_dominate_person","srd_mislead"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Cleric / Shadow Domain (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_shadow-domain","ruleset":"2014","granted_spells":{"1":["srd_bane","srd_false_life"],"3":["srd_blindnessdeafness","srd_darkness"],"5":["srd_srd_blink","srd_fear"],"7":["srd_black_tentacles","srd_greater_invisibility"],"9":["srd_cone_of_cold","srd_dream"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Ranger / Snake Speaker (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_snake-speaker","ruleset":"2014","granted_spells":{"3":["srd_srd_charm_person"],"5":["srd_suggestion"],"9":["srd_tongues"],"13":["srd_confusion"],"17":["srd_dominate_person"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Cleric / Vermin Domain (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_vermin-domain","ruleset":"2014","granted_spells":{"1":["srd_srd_detect_poison_and_disease","srd_speak_with_animals"],"3":["srd_spider_climb","srd_web"],"5":["srd_srd_conjure_animals","srd_fear"],"7":["srd_dominate_beast","srd_giant_insect"],"9":["srd_contagion","srd_insect_plague"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Ranger / Wasteland Strider (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_wasteland-strider","ruleset":"2014","granted_spells":{"3":["srd_protection_from_the_void"],"5":["srd_calm_emotions"],"9":["srd_srd_dispel_magic"],"13":["srd_srd_banishment"],"17":["srd_hold_monster"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Cleric / Wind Domain (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_wind-domain","ruleset":"2014","granted_spells":{"1":["srd_feather_fall","srd_thunderwave"],"3":["srd_gust_of_wind","srd_misty_step"],"5":["srd_fly","srd_wind_wall"],"7":["srd_conjure_minor_elementals","srd_freedom_of_movement"],"9":["srd_cloudkill","srd_conjure_elemental"]},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{},"expanded_spell_variants":{}},
  // Warlock / Wyrdweaver (2014, toh)
  {"source_document_key":"toh","source_record_key":"toh_wyrdweaver","ruleset":"2014","granted_spells":{},"spell_variants":{},"spell_variant_label":null,"expanded_spells":{"1":["srd_bane","srd_faerie_fire"],"2":["srd_blur","srd_frenzied_bolt"],"3":["srd_bestow_curse","srd_hypnotic_pattern"],"4":["srd_compulsion","srd_reset"],"5":["srd_battle_mind","srd_mislead"]},"expanded_spell_variants":{}},
];
