// AUTO-GENERATED by scripts/fetch-srd-conditions.mjs -- do not edit manually.
// Re-run `node scripts/fetch-srd-conditions.mjs -- --edition=2024` to refresh.
//
// Intended source: Systems Reference Document 5.2 (CC-BY-4.0, Wizards of the
// Coast) via the Open5e v2 rules glossary
// (https://api.open5e.com/v2/rules/?document__key__in=srd-2024), filtered to
// entries whose name matches one of the 15 canonical SRD condition names.
//
// Last fetch: 2026-07-22.
//
// Open5e has no dedicated 2024 conditions endpoint yet (open5e-api#793) — as
// of the fetch date above, `/v2/conditions/` only returns the 2014 core
// conditions (empty `desc` fields, tagged to the 5e-2014 gamesystem) and
// `/v2/rules/?document__key__in=srd-2024` doesn't carry the Conditions
// appendix or Exhaustion at all. Until that upstream gap closes, real 2024
// condition text lives in `CONDITION_PATCHES["2024"]` in
// `conditionPatches.ts` (hand-maintained, each entry flagged
// `// TODO verify against SRD 5.2 PDF`). Once this script starts finding real
// entries, trim that patch map back down to genuine overrides/gaps.
import type { Condition } from "@/types/condition.types";

export const SRD_CONDITIONS_2024: Condition[] = [];
